### ISSUE TITLE
check into Entity Regulation Rule 1. 

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#101]
It looks like this one is missing some assertions that should have passed through the rule:

If R1 has output E1 
and E1 regulates R2 
then R1 directly provides input for Binding reaction 3
Binding reaction 3 regulates R2 

look at http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-163765 from 
https://reactome.org/PathwayBrowser/#/R-HSA-163685&SEL=R-HSA-163765&PATH=R-HSA-1430728

**Comment by deustp01** [comment]
Feeling my way here, "Formation of ChREBP:MLX heterodimer" is a binding reaction and its heterodimer product is annotated in Reactome as positively regulating each of five events in which a gene is expressed to yield a protein product. The binding reaction is also annotated as a preceding event of each of the gene expression ones. So the causal relationships between the binding reaction and and each of the gene expression events are identical.

However, we have identified the gene that is the input for one of the five events, "Transcriptional activation of Citrate lyase monomer gene by ChREBP:MLX" and have not identified the gene input for the other four. Could that explain the difference in links in the model? "Formation of ChREBP:MLX heterodimer"  directly provides input for a binding activity unit which in turn directly positively regulates the "Transcriptional activation of Citrate lyase monomer gene by ChREBP:MLX" activity unit. That binding activity unit also has a part_of link to an activity unit corresponding to the Reactome parent pathway, "ChREBP activates metabolic gene expression". Each of the other four "Transcriptional activation" activity units is positively regulated by its own binding activity unit, which is part_of the parent pathway but which has no directly provides input link from "Formation of ChREBP:MLX heterodimer".

<img width="1229" alt="Screen Shot 2020-09-09 at 1 14 30 PM" src="https://user-images.githubusercontent.com/12737623/92633092-42586580-f2a0-11ea-80b0-fe848006afcb.png">

**Comment by goodb** [comment]
It looks like the problem here was that the four reactions not connected to "Formation of ChREBP:MLX heterodimer" were classified in the BioPAX export as Template reactions - I assume for the reason you elaborate above.  There was a filter in the code that was meant for something else but was also eliminating causal connections to such template reactions.  Taking that out, they all come through and look as expected.  

![Screen Shot 2020-09-09 at 11 25 44 AM](https://user-images.githubusercontent.com/2086122/92638567-4fb92400-f28f-11ea-8fa3-e363e62c365b.png)

**Comment by ukemi** [comment]
@deustp01 , doesn't the location of the 'transcriptional activation...' (cytosol?)look a bit strange in this model? All black boxes, but my guess is that these could be refactored to either a GO process (positive regulation of transcription by RNA polymerase II), or perhaps with one more molecular function DNA-binding transcription activator activity, RNA polymerase II-specific (GO:0001228) with the ChREBP:MLX dimer as the catalyst? Phase II---- Dealing with Reactome black box reactions. :)

**Comment by ukemi** [comment]
It's because the protein products of the transcription activation black box end up in the cytosol. See ACC, it's location is in the cytosol. Once again, the model is correct with respect to the information it was given, but the information was a bit misleading.

**Comment by ukemi** [comment]
This is actually quite fascinating on a number of levels. Also to note that the activation of each of the metabolic genes is enumerated as a separate black box reaction (which really corresponds to gene expression given the location of the outputs), but the curator chose to map the parent process to positive regulation of cellular metabolic process and make each of the activation of gene expression reactions a part of it, rather than to a grouping class of positive regulation of gene expression that includes the set of metabolic genes. It poses interesting questions about instances of each of these processes and how they map onto the biology.

**Comment by deustp01** [comment]
Yes. These black box events are really shorthand "template" pathways, which may not correspond exactly to any GO biological process term, beginning with the whole process of transcription and RNA processing within the nucleus, followed by RNA export through the nuclear pore to the cytosol and translation into protein. And optionally omitting the input gene with its nuclear location complicates things.
We have a lot of these shorthand gene expression events so figuring out a standard shorthand that fits with Ben's rules including ones for events that span more than one compartment, or that is accompanied by a tag that points to the special rule for processing transcription - translation shorthand events is probably going to be worthwhile.

**Comment by ukemi** [comment]
The simple solution we could try at some point, is to assert a process for the black box reactions (by asserting it in reactome) and see how it fits if we insert it into the causal chain. The nice thing about that is that we don't necessarily enumerate all of the causal MFs in the process. A biologist probably wouldn't want to say that the ribosome and RNA polymerase act in the regulation of metabolism, but they are certainly necessary in these steps. I think that is one of the reasons why the black box reactions serve a certain practical purpose.

**Comment by ukemi** [comment]
Are there any transcription factors in reactome for which they are a catalyst in a reaction or do they all feed into black boxes? I'd be curious to see how they are modeled, my money would be on the DNA binding aspect.

**Comment by ukemi** [comment]
Sorry @goodb we are railroading your ticket.

**Comment by deustp01** [comment]
> Are there any transcription factors in reactome for which they are a catalyst in a reaction

Mostly - as done well here - they are positive regulators - https://reactome.org/PathwayBrowser/#/R-HSA-1912415

**Comment by ukemi** [comment]
cup half full---- it is consistent so we can figure out a standard approach.

**Comment by ukemi** [comment]
But it is one case where our regulation inference breaks down. I just checked the fatty acid regulation of AMPK and it looks like they are allosteric, so we are good. However, for ADIPOR looks like the regulation is the result of a signaling cascade and the dimer/trimer does not directly bind AMPK. We will need to try to search these out in the future too. Maybe we can filter them based on location. If the entity to which we infer the binding is not located where the enabler of the regulated reaction occurs, we should not infer the binding-regulation rule. Phase II?

**Comment by ukemi** [comment]
Not to go down the instance representation garden path, but in @goodb' last comment above, we could also consider the instances of the dimer formation. Is it the same instance of dimerization that leads to the transcription activation for each of the genes? I think this visualization is the best way to view the biology, but under the hood, should the dimerization reaction be different instances. At some point being sloppy with how instances in our models map onto the chemistry going on in the cell, or not being rigorous about what the instances represent with that respect may come back to haunt us. It haunts me.

**Comment by deustp01** [comment]
Returning, sort of, to Ben's original issue, I think that regulation of transcription in Reactome is a distinctive can of worms. A good fix may need custom GO-CAM inference rules (a guess based on the fact that one of these events always spans something equivalent to a pathway / process, not a single chemical reaction or binding) and clean-up on the Reactome side to get rid of irregularities like sometimes but not always making the gene that sets off the transcription - translation event an input.

Separately, and maybe less of a can of worms, we need to identify instances of allosteric regulation involving small molecule regulators that act on enzyme targets (as in fructose-2,6-bisphosphate regulation of PFK1-mediated synthesis of fructose-1,6-bisphosphaye in glycolysis) to figure out how to handle those consistently.

**Comment by ukemi** [comment]
I think for the PFK and other allosteric interactions, what we have works. But it may be not be how GO handles them in the future. We specifically designed our strategy for those. It's for the cases where there is not a direct binding event that we run into problems with the current strategy.

**Comment by deustp01** [comment]
> In the end, the curator uses the shorthand to say that regulating the genes is the mechanism for regulating the metabolism.

Right. Another place where we have lumped a process and its regulation together. We do this quite often for transcriptional regulation. But that may also give us a fairly easy test and patch - if the product of the transcription - translation event is a participant in a process, then the transcription factors involved in the transcription - translation event are participants in regulation of that process. Not quite a scripted automated clean-up but still not too bad.

**Comment by goodb** [comment]
@ukemi @deustp01 feel free to keep figuring this out here, but if you don't mind, assuming that what I describe in the comment above https://github.com/geneontology/pathways2GO/issues/101#issuecomment-689738311 is valid for now, could you close the issue when you are done ?

**Comment by deustp01** [comment]
@ukemi time to close?

**Comment by ukemi** [comment]
I think so. We should keep these things in mind for future developments though.
