### ISSUE TITLE
neurotransmitter clearance

### ISSUE THREAD

**Issue by cmungall** [geneontology/pathways2GO#113]
Having difficulties understanding:

http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-112311?

![image](https://user-images.githubusercontent.com/50745/98335677-43fd8b80-1fba-11eb-94b9-ff0c33689a49.png)

 - I don't see any causal ordering between activities
 - the mapping to the GO BP seems odd - should clearance be mapped to biosynthesis? Are neutotransmitters really being synthesized here?
 - we see two activities, one for nAD, other for Cho - is part-of correct here?

**Comment by deustp01** [comment]
Two technical issues here that, I think, make the GO-CAM hard to understand. One is purely Reactome: the "pathway" is a grouping term for two events that have no causal connection annotated in Reactome, and I don't see anything in the reaction attributes that would allow pathways2GO to infer one. The second looks like a pathways2GO issue: the event "ACHEIs bind ACHE" is a drug reaction and should have been found and eliminated from the GO-CAM by the no-drugs filter.

**Comment by ukemi** [comment]
Note also that the final issue is a curation question. Processes are directly asserted.
This pathway is directly asserted to be a neuotransmitter biosynthetic process. I would say this curation question falls into what I hope will be a general curation synchronization/QC effort.
@deustp01 od @goodb are the inhibitors tagged as drugs in the biopax?

**Comment by ukemi** [comment]
Actually in Reactome I see that the inhibitors are drugs. We have left them out of the import as entities, but have left the reaction in as a molecular event.

**Comment by deustp01** [comment]
> but have left the reaction in as a molecular event.

But can that work? With no drug input and output complex component, the reaction consists of transforming ACHE into itself. In other cases where a drug binds a protein, I think the whole binding event is filtered out. @goodb ?

**Comment by ukemi** [comment]
we see two activities, one for nAD, other for Cho - is part-of correct here?

I think part-of is correct, but the specific processes are missing, which results in assigning both reactions as part of the same isntance of neurotransmitter clearance.  The first Reactome reaction is the transport of the noradrenaline back into the cell. I don't know if there are any other kinds of reactions that get rid of noradrenaline in the synaptic cleft, but if not, then this is a classic case if there is only one function in a process is there a process debate. I think I've made my view on that clear over the years. In the second case we have the same issue, the process of acetylcholine hydrolysis is the only function captured so far that is part of the process of removing acetylcholine from the synaptic cleft. 

If we decide there is no process, perhaps we can look at more examples of this kind of pattern. we could either invoke the noradrenaline and acetylcholine processes. Or, we could introduce another rule: if there is no causal connection between reaction in Reactome, separate them into different instances of the of the pathway. So in this case we would have two models for neurotransmitter clearance, one that represents the acetylcholine clearance and one that represents the noradrenaline clearance. But then we are admitting that these single molecular functions are part of a process.

**Comment by ukemi** [comment]
Pathways are human constructs--------- It would not be absurd in my mind to include the choline transporter of the presynaptic cell as part of acetylcholine clearance. I don't know if a neurobiologist would agree.

**Comment by deustp01** [comment]
> Pathways are human constructs

And here, in retrospect, we may have some doubts about the humans who did the constructing. The next steps are to confirm that the difficulties Chris flagged at the start of this ticket are a localized problem (mainly to confirm that the rules intended to exclude drugs and reactions involving them are working correctly), to spot-check GO-CAMs generated from some other Reactome grouping pathways for similar difficulties, and then think about possible new filters or rules in the GO-CAM process, or more stringent Reactome criteria for allowing a grouping pathway, to get a durable fix.

**Comment by ukemi** [comment]
Last comment, I promise. Note here also that in the noradrenaline reaction, there are two possible enablers. If these both contribute to the clearance of the neurotransmitter from the cleft, then I would invoke a transport process here. This is similar to what I think we will have to do in the kidney.

**Comment by goodb** [comment]
Boy, woke up late for the party here..  

1. The pathways in noctua-dev don't reflect the most recent iteration of the code that [cured a bug ](https://github.com/geneontology/pathways2GO/issues/108)in the drug-reaction deletion protocol.  So that reaction is now gone:
<img width="824" alt="Screen Shot 2020-11-06 at 9 12 15 AM" src="https://user-images.githubusercontent.com/2086122/98394834-2d821f00-2010-11eb-98ab-6d5c646fb03e.png">

2. The rest of the conversion is as Reactome indicates (with all of the problems elaborated on above about how they did it).  @cmungall its often really helpful to look at the text view of the pathway hierarchy to understand what is in the converted pathway - which will only contain the directly contained reactions and not all the sub pathways.  Note there are no 'prevEvent' links on any of the reactions in that pathway, hence no causal relations.
<img width="364" alt="Screen Shot 2020-11-06 at 9 14 50 AM" src="https://user-images.githubusercontent.com/2086122/98395059-88b41180-2010-11eb-9c3b-23ec213266bf.png">

This is another great example of why GO should start thinking hard about building integrated views containing multiple GO-CAMs and why we need to deal with the pathway hierarchy situation specifically for the Reactome conversion.

**Comment by deustp01** [comment]
> criteria for allowing a grouping pathway

This could also be fixed, perhaps, by clarifying is_a and part_of relationships of reactions and sub-pathways to pathways. Events in a grouping pathway have an is_a relationship to it while the causally linked event steps are part_of. So if this distinction is reliably sorted out in Reactome (and there are probably other good reasons to want to do this), then we should at least have an attribute that could be reasoning and filtering.

**Comment by ukemi** [comment]
Can we close this one?

**Comment by ukemi** [comment]
@deustp01 let's try to create a curation ticket for this issue. I'll leave it open until then.

**Comment by deustp01** [comment]
Two possible curation tickets.
First, a narrow one to ask about the rationale(?!) for assigning GO:0042136 "neurotransmitter biosynthetic process" to this pathway that groups several quite distinct strategies for removing released neurotransmitters from the synaptic cleft ("The neurotransmitter is cleared by either re-uptake by the pre-synaptic neuron, diffusion in the perisynaptic area, uptake by astrocytes surrounding the synaptic cleft or enzymatic degradation of the neurotransmitter.")
The fix would be to assign appropriate GO BP terms to the individual reactions and subpathways that are grouped here and leave the grouping pathway itself with no BP term.
Second, a grand strategy one to figure out how to distinguish part_of and is_a reaction children in Reactome pathways reliably and on that basis identify grouping pathways from X pathways. (A subsidiary task is to invent a terse descriptive name X for pathways whose parts are causally connected.)
