### ISSUE TITLE
models should not assert labels for classes and properties

### ISSUE THREAD

**Issue by balhoff** [geneontology/pathways2GO#114]
In the Reactome models I see in the `dev` branch of https://github.com/geneontology/noctua-models, it looks like `rdfs:label` annotations are inserted for various GO and RO terms. This ends up creating duplicated and/or conflicting labels for downstream users of the models. For example, I am inserting each model into its own named graph, and so I end up with these triples being present in the database thousands of times. Could we remove these annotations from the model generation?

**Comment by ukemi** [comment]
@balhoff  can you check to see this is working, or does it require a new round of import?

**Comment by balhoff** [comment]
@ukemi I believe this is fixed.
