### ISSUE TITLE
Define Victory

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#12]
How should we decide when biopax 2 go-cam or go-cam 2 biopax is good enough to stop (and then move on to providing access to the results)

**Comment by goodb** [comment]
Note that I can't seem to add @thomaspd as an assignee.  If he is the 'owner' of this, then I ought to be able to do that.  @pgaudet does he need to be added to the repo or something?

**Comment by goodb** [comment]
Perhaps @selewis might have an opinion about this?

**Comment by pgaudet** [comment]
This is a problem with all these repos. @kltm  How can you add someone to a specific repo ? I only know how to do this via teams

**Comment by kltm** [comment]
@pgaudet The choices are either teams or collaborators. https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/
In general, we should probably be using teams.

**Comment by pgaudet** [comment]
Right - should I edit teams to include other repos ? 

Who should do that ?

**Comment by goodb** [comment]
For biopax2go-cam, check whether GAFs generated directly by Reactome are different from GAFs generated from the go-cams.  Step one they should have 100% recall, step two, do the additional GAFs recapitulate more annotations generated in other ways?

**Comment by goodb** [comment]
closing as too ambiguous
