### ISSUE TITLE
The group is incorrect in the Reactome imports

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#120]
In the Reactome imports on the production server, we noticed that we couldn't filter on the group and that in the annotation output, the group looks like a URL. We think this is because in the models, the URI for Reactome has an https while in the YAML file that resolves groups, the URI is http. 
@kltm and @vanaukenk , did I express this correctly?

**Comment by kltm** [comment]
@ukemi I believe so. Essentially, there is an inconsistency between what is in the model file and what is in groups.yaml. groups.yaml has precedence here.
Even if this is not the cause of the problem, it will need to be fixed.

**Comment by ukemi** [comment]
@dustine32, I believe you fixed this. Just for bookeeping, we might want to attach the pull request to this ticket, but I will close this now. I tested it on production and it works!!!!

**Comment by dustine32** [comment]
Oh wow, thank you @ukemi for finding this ticket!

Link to go-site change ticket: https://github.com/geneontology/go-site/issues/1924
Link to go-site change PR: https://github.com/geneontology/go-site/pull/1925
