### ISSUE TITLE
Filtering by gene does not return Reactome models

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#121]
When filtering by gene, Reactome models are not returned. It doesn't matter whether the GP acts as a monomer or in a complex. @deustp01 @vanaukenk 

Example:
MANBA Hsap should return gomodel:R-HSA-8853383  from instance Instance: gomodel:R-HSA-8853710

**Comment by goodb** [comment]
This is because of the use of gene classes from the REACTO ontology (subclasses of Neo entities).  The search could be adapted to traverse to the gene ids.  tagging @tmushayahama

**Comment by vanaukenk** [comment]
This is a duplicate of https://github.com/geneontology/minerva/issues/430
where I think the work would actually need to be done, so I'm closing this ticket.
