### ISSUE TITLE
Change mapping of R-HSA-2395873 from GO:0044715 to GO:0044716

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#128]
The R-HSA-2395873 reaction is:NUDT18 hydrolyses 8-oxo-GDP to 8-oxo-GMP------ note the ribo.
GO:0044715 is Catalysis of the reaction 8-oxo-dGDP + H2O = 8-oxo-dGMP + phosphate. ----note the deoxyribo

We should change this mapping to ---- GO:0044716: Catalysis of the reaction 8-oxo-GDP + H2O = 8-oxo-GMP + phosphate.

**Comment by deustp01** [comment]
Done - [changed reaction on development site](https://curator.reactome.org/PathwayBrowser/#/R-HSA-8956319&SEL=R-HSA-2395873&PATH=R-HSA-1430728,R-HSA-15869) will propagate to public site with June 2021 release.
