### ISSUE TITLE
Change R-HSA-2395876 mapping from GO:0017110 to GO:0044716

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#129]
R-HSA-2395876 is: NUDT15 hydrolyses 8-oxo-dGDP to 8-oxo-dGMP

GO:0017110 is: Catalysis of the reaction: a nucleoside diphosphate + H2O = a nucleoside monophosphate + phosphate. 

For this reaction, we can be more specific since it is only a single substrate:
GO:0044716: Catalysis of the reaction 8-oxo-GDP + H2O = 8-oxo-GMP + phosphate.

**Comment by deustp01** [comment]
Don't we want GO:0044715; Catalysis of the reaction 8-oxo-**_d_**GDP + H2O = 8-oxo-**_d_**GMP + phosphate (complement to #128). If so, it's done, visible on [dev site](https://curator.reactome.org/PathwayBrowser/#/R-HSA-8956319&SEL=R-HSA-2395876&PATH=R-HSA-1430728,R-HSA-15869), for release in June.
