### ISSUE TITLE
Change mapping of  R-HSA-2395872 from GO:0008828 to  GO:0016818 or request a new term

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#130]
R-HSA-2395872 is: NUDT1 hydrolyses 2-OH-ATP to 2-OH-AMP
GO:0008828 is: Catalysis of the reaction: deoxy-ATP + H2O = dAMP + diphosphate.

I think we need to either move this up to the very generic parent: GO:0016818--Catalysis of the hydrolysis of any acid anhydride which contains phosphorus.

Or request a new term:
term 2-hydroxy-ATP hydrolase activity
def: Catalysis of the reaction: 2-hydroxy-ATP + H2O = 2-hydroxy-AMP + diphosphate.
rhea: new reaction
ref: PMID:11139615
is_a parent: GO:0016818

I think the latter, do you agree?

**Comment by ukemi** [comment]
I think we have a similar issue with R-HSA-2395818

**Comment by deustp01** [comment]
Yes, that looks right - made the NTR request on github/.../go-ontology with pathways2GO label, so closing this one.
