### ISSUE TITLE
RHEA2GO?

### ISSUE THREAD

**Issue by mileswhen** [geneontology/pathways2GO#138]
Dear Team,

Quick question and would really appreciate your thoughts on this. At the moment is it possible to use pathways2go to convert RHEA (in BioPAX 3 with PAXTools) to GO-CAM?

Thanks in advance :)

**Comment by deustp01** [comment]
@lpalbou is this something "we" (you) can do? I'm not sure what the result would look like - Rhea content is exclusively single reactions as far as I know and while many are linked to GO molecular function terms, none is associated with gene products (except as one can reason onward from the associated MF terms to identify gene products annotated with those terms.

**Comment by lpalbou** [comment]
I know we have some level of integration of RHEA but I don't think we are converting them into GO-CAMs yet.  Provided the BIOPAX export is good, it should be possible indeed and @dustine32 would be the person to work on that if we decide to do it.

Also tagging @cmungall as he may know more than me on that question !

**Comment by mileswhen** [comment]
@lpalbou cheers for the quick reply! Happy to hear that it should be possible, I did give it a try already with the following (omitting `-e REACTO`):

```
$ java -Xmx4g -jar biopax2go.jar -b biopax_files/rhea_biopax3.owl -o ./gocam_files/ -lego go-lego.owl 
Warning, no catalog file provided for for go-lego.   Specify one with -c catalog.xml
xref map created, size: 32448
Reasoner provided - 
Setting up Arachne reasoner for Qrunner, extracting rules from tbox
2021-07-21 09:24:19,025 INFO org.biopax.paxtools.util.BPCollections - System property: paxtools.CollectionProvider=null
2021-07-21 09:24:19,028 INFO org.biopax.paxtools.util.BPCollections - Using the default CollectionProvider (creates HashMap, HashSet).
done with file biopax_files/rhea_biopax3.owl 
```
however, the output directory remained empty.

Given that the CollectionProvider is null, is there perhaps some alignment map that I could provide? Such as the one [here](http://geneontology.org/docs/download-mappings/)?

**Comment by cmungall** [comment]
Peter is correct, rhea is single reactions. Ideally the conversation code would produce a more informative message though. Can you say more on what you're trying to do? Rhea is often used with metabolic pathway databases which are more appropriate targets for conversion

**Comment by mileswhen** [comment]
@cmungall thanks for the reply. The reason I'd like to convert Rhea is that it provides better detail for metabolic reactions than Reactome — having it as GO-CAM would allow better integration with other CAM models, and it also makes consistency checking easier.

**Comment by deustp01** [comment]
> Rhea ... provides better detail for metabolic reactions than Reactome

True, alas. However, we are working to align Reactome reactions with Rhea ones wherever a Rhea one exists. When we're done (months, a year? Sooner if the funding we've applied for is approved) Reactome will have the same detail and accuracy (no more missing protons or incorrect charge states) as Rhea does now and in addition will provide a direction under physiological conditions for each reaction. So depending on the timing needs of your project, you might want to wait on this or not invest too much effort into what should be a temporary workaround.

**Comment by goodb** [comment]
@mileswhen could you post the rhea biopax file you are using?  The system should in theory produce something but, because of the various interpretations of the biopax standard, it usually needs some customizations to make it work for a new resource.  If you compare the rhea biopax to the reactome biopax you might be able to figure out what is missing.  @dustine32 will need that file if he is to help you ;)..

**Comment by mileswhen** [comment]
@deustp01 Ah brilliant, thank you for the information. And great to hear that there are plans to incorporate more detail in Reactome. I will keep the timeline in mind.

**Comment by mileswhen** [comment]
@goodb yes absolutely, here's the file: [rhea_biopax3.owl.zip](https://github.com/geneontology/pathways2GO/files/6870922/rhea_biopax3.owl.zip). I used PAXtools for the conversion from BioPAX 2 to 3. Large differences between this and the Reactome BioPAX don't stand out to me, but would appreciate a more experienced eye :)

**Comment by dustine32** [comment]
Thank you @mileswhen for the file and thanks @goodb for the suggestion! I'll try this file myself to see why there's no output.
