### ISSUE TITLE
Do not use ChEBI roles as physical entities - fall back on chemical entity

### ISSUE THREAD

**Issue by dustine32** [geneontology/pathways2GO#139]
Originated from an OWL consistency error in the GO-CAM for `gomodel:PWY3O-981` translated from [SGD pathways](https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=NIL&object=PWY3O-981&redirect=T) BioPAX.

We determined the issue was a ChEBI term (CHEBI:15339 - acceptor) for a chemical role being used as a physical entity:
![image](https://user-images.githubusercontent.com/2678599/135535065-74e1b05c-d0c1-4b4e-a513-cb13e7ab5712.png)

A check should be implemented to fall back on using CHEBI:24431 chemical entity if the attempted [term](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15339) is a role (CHEBI:50906) or descendant term:
![image](https://user-images.githubusercontent.com/2678599/135535451-03a87e25-fbe0-4a34-a6cd-24d390b27f83.png)

Tagging @thomaspd @ukemi @cmungall @deustp01

**Comment by dustine32** [comment]
Suggestion from @balhoff https://github.com/geneontology/pathways2GO/pull/158#discussion_r853304938 to retain the chemical role by adding a "has role" edge. So, in this example we would now have:
```
Molecular Event -has_input-> chemical entity -has_role-> acceptor
```
@thomaspd What do you think? We would also need to add "has_role" (RO:0000087) to the ShEx [spec](https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shex).

**Comment by cmungall** [comment]
Indeed - and we can just get from Rhea if needed
