### ISSUE TITLE
For YeastPathways, use stepDirection instead of conversionDirection

### ISSUE THREAD

**Issue by dustine32** [geneontology/pathways2GO#142]
Currently, the pathways2go [code](https://github.com/geneontology/pathways2GO/blob/97fe498080ddba4339c233ffffe109c15431209c/exchange/src/main/java/org/geneontology/gocam/exchange/BioPaxtoGO.java#L1155) will only use the `conversionDirection` field on `BiochemicalReaction` to determine how to arrange the `left` and `right` molecules in an activity. In YeastPathways BioPAX, the `conversionDirection` field is only used when a reaction is `REVERSIBLE` - direction information is primarily in the `BiochemicalPathwayStep` `stepDirection` field.

For YeastPathways, we should use `stepDirection` to give us the direction of the reaction in the pathway, and ignore `conversionDirection`. Some example models/reactions where both are present and contradict each other:

1. PENTOSE-P-PWY
   * StepDirection LEFT_TO_RIGHT not equal to ConversionDirection REVERSIBLE in TRANSALDOL-RXN
2. FOLSYN-PWY-1
   * StepDirection LEFT_TO_RIGHT not equal to ConversionDirection REVERSIBLE in FORMATETHFLIG-RXN
3. NONOXIPENT-PWY
   * StepDirection RIGHT_TO_LEFT not equal to ConversionDirection REVERSIBLE in RIB5PISOM-RXN

Tagging @thomaspd

**Comment by dustine32** [comment]
@suzialeksander @thomaspd Here's the full list of pathways having a reaction step with stepDirection = `RIGHT-TO-LEFT`:
https://docs.google.com/spreadsheets/d/1bbDSJ5uNhgWhCg4y6llfGazKbMGILsjz2J3hsuU1B5Y/edit#gid=0

These are currently loaded into noctua-dev and the stepDirection fix is ready for testing. Enjoy!

**Comment by dustine32** [comment]
@thomaspd @suzialeksander Just checking if any changes need to be made for this `stepDirection` code. If not, I can merge the [PR](https://github.com/geneontology/pathways2GO/pull/184) and close this ticket. Noctua-dev still has the test models with this change loaded (example: [NONOXIPENT-PWY](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:NONOXIPENT-PWY?)).

**Comment by suzialeksander** [comment]
Hey @dustine32, this sounds correct.  No objections here!

**Comment by dustine32** [comment]
Wonderful, thank you @suzialeksander !
