### ISSUE TITLE
Write a script to capture the status of Reactome entities in PRO

### ISSUE THREAD

**Issue by nataled** [geneontology/pathways2GO#144]
Need to write a script that will create a status report.

**Comment by nataled** [comment]
Current status:
<pre>
Total in-scope EWAS:    26522

                     Reactome          PRO
Total intersection:     14670        11221
In-scope EWAS:          14498        11065
  Canonical:             8826         7042
  Isoforms:               198          172
  Subseq:                3629         2429
  PTM:                   1845         1422
Variants:                   3            3
Complex:                  145          138
Set:                       24           15

Reactome (in-scope EWAS) accounted for: 55% (14498/26522)
</pre>
Each row shows the number of Reactome entities (release 79) that map to the indicated number of PRO entities (release 65).

Considered out of scope: variants of any type (insertions, deletions, replacements), non-proteins (genes, various RNAs), modifying proteins when 'modified' by target (e.g., if there is an EWAS “ABC1 modified by SUMO1”, the complementary EWAS "SUMO1 'modified' by ABC1" is ignored)

**Comment by ukemi** [comment]
Thanks @nataled 
ping @deustp01

**Comment by ukemi** [comment]
@nataled 
Is there a typo?
(e.g., if there is an EWAS “ABC1 modified by SUMO1”, the complementary EWAS "SUMO1 'modified' by ABC1" is ignored)
should be
(e.g., if there is an EWAS “ABC1 modified by SUMO1”, the complementary EWAS "SUMO1 'modifies' ABC1" is ignored)

**Comment by ukemi** [comment]
Got it! Thanks!

**Comment by deustp01** [comment]
The basic problem is that we got carried away. When a ubiquitin molecule is covalently attached to a molecule of protein ABC1, that can be annotated as a ubiquitin-modified amino acid side chain of ABC1. It can equally well be annotated as an ABC1-modified amino acid side chain of ubiquitin. The first annotation makes sense when talking about ubiquitination (or SUMOylation, etc.) and the second one doesn't, so our plan is to find and remove all annotations of the second kind, and to improve our curation process to prevent this.
A list of problems from Darren will be good, both as a check and as a reminder to get the job done soon!
