### ISSUE TITLE
Reactome: GPI-anchored proteins with incorrect sequence range

### ISSUE THREAD

**Issue by nataled** [geneontology/pathways2GO#148]
The following EWASes represent GPI-anchored proteins (or shed versions thereof) in which the position of GPI anchor is correct, but the sequence range is not. Like issue #147, as it stands the GPI anchor position given appears to be internal to the sequence instead of the C-terminus, but unlike that issue the fix is to the sequence range. The sequence ranges given as the fix in each case comes from evidence based on UniProtKB. Bear in mind, however, that some of the endpoints are predictions or inferences (indicated by an asterisk); based on other entries, I don't believe this is an issue.

R-HSA-8941100 & R-HSA-8940695:
  P31358  ?-?       (GPI at 36)   range should be 25-36*

R-HSA-8941078 & R-HSA-8940791:
  Q7Z553  21-956     (GPI at 931)   range should be 26*-931* (original UniProt prediction of start was 21, later revised to 26)

R-HSA-8941062 & R-HSA-8940783:  
  Q8IV16  21-184     (GPI at 151)   range should be 21*-151*

**Comment by deustp01** [comment]
Agreed - fixed the Reactome annotations to conform to current UniProt. DONE and CLOSED
