### ISSUE TITLE
Infer Molecular Function = Binding 

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#15]
If Reactome did not provide a GO molecular function term, and there’s either 1) an output protein complex but no input protein complex, or 2) there’s an output protein complex that is different from all the input complexes, you can infer that the activity is a protein binding function.  So you can label it that way (GO:0005515) instead of the root molecular function (GO:0003674).

**Comment by goodb** [comment]
@thomaspd @ukemi @cmungall @deustp01 

I've adjusted the suggested rule in the issue comment such that the output complex must contain a part that is one of the inputs.  I think its working pretty well (gets all of the untagged reactions with 'binding' in their names that I've looked at so far), but it also hits some of the more complicated reactions.  For example "[APC promotes disassembly of beta-catenin transactivation complex](https://reactome.org/PathwayBrowser/#/R-HSA-201681&SEL=R-HSA-3364042&PATH=R-HSA-162582,R-HSA-195721)" and [Beta-catenin displaces TLE:HDAC1 from TCF/LEF](https://reactome.org/PathwayBrowser/#/R-HSA-201681&SEL=R-HSA-3299569&PATH=R-HSA-162582,R-HSA-195721)" get tagged with 'protein binding'.  

Thoughts on this?  I think it is more informative than the previous typing as 'molecular function' as some level of binding clearly happens, but that could be said for most of the more complicated reactions.

**Comment by deustp01** [comment]
@fabregat
This is a version of our internal discussion of how to identify binding reactions in Reactome computationally, coupled to the discussion of whether displacement (A:B + C -> A:C + B) is a legitimate reaction type and, if so whether it is a kind of binding.
Time to revive the Reactome discussion, with the GO people interested in Reactome - GO alignment joining in?

**Comment by ukemi** [comment]
This isn't surprising since Reactome captures the details of complex formation, rearrangement and dissociation. I suspect that there are a lot of reactions that represent GO binding in some way. For a while there was some discussion about the meaning of 'recruitment' in GO and whether we should have it. Some of these clearly represent that.

**Comment by fabregat** [comment]
@deustp01 
I think it's a good idea to revive such a discussion with the GO people joining this time.
Count me in!

**Comment by goodb** [comment]
Hi @fabregat , @deustp01 mentioned that you have worked before on rules for inferring which reactions can be annotated as 'binding' reactions.  Could you share these?  How do they compare to the rule proposed above?

**Comment by goodb** [comment]
No action for 2 months.  Existing rule seems to meet objective.  Re-open if people get interested.

**Comment by goodb** [comment]
From @fabregat "These days I am retaking some of the pending stuff. About this, what I've done is to run the classifier at https://github.com/reactome/rxn-classifier for the latest slice (data for the upcoming release 67).

Please find attached a report with the 4,926 proposed binding reactions.

A disclaimer here is that the classifier is based on a paper published in 2011 in the Database journal by Jupe et al. (https://doi.org/10.1093/database/bau060).

In this paper, binding events are defined as those where there are more input entities than output entities. The test applied to determine binding can also be useful for verifying stoichiometric balance; at least one input entity should become a component of (one of) the output entities, or one of the input entities should include more entities as an output than it did as an input."

[Binding.csv.txt](https://github.com/geneontology/pathways2GO/files/2605147/Binding.csv.txt)

**Comment by goodb** [comment]
Bug found.  Some reactions that have the same inputs and outputs are getting called Binding.  Need to add a constraint to the rule to filter these out.

**Comment by goodb** [comment]
See pathway 'activated TAK1 mediates p38 MAPK activation' and reaction 'Phosphorylated MKK3/MKK6 migrates to nucleus' which should not be a binding reaction

**Comment by deustp01** [comment]
In this specific case, a translocation / transport event (an otherwise unchanged entity moves from one location (GO cellular component) to another has been identified as binding. That pattern (entity unchanged except for its location) could be a constraint. A complication in applying it to Reactome is that the identical physical entity in two different locations is treated as two entirely different physical entities (so cytosolic glucose is as different from extracellular glucose as it is from cytosolic fructose). The shared name is a strong indication but would need to be confirmed by looking at the reference entities (UniProt, ChEBI) that the entities in question inherit their attributes from to see that they are the same.

**Comment by goodb** [comment]
The simple test of whether there are more inputs than outputs as suggested by @fabregat seems to work very well.  About to close this issue based on that change.  If we need to revisit, there are good positive examples in Signaling by BMP and negative examples in 'activated TAK1 mediates p38 MAPK activation'

**Comment by goodb** [comment]
Bug introduced when complexes converted back from intersections to parts lists.  Not detected protein complex binding.
