### ISSUE TITLE
Reactome: review of 'acyl-GPI' cases

### ISSUE THREAD

**Issue by nataled** [geneontology/pathways2GO#152]
Among the various ways GPI anchors are represented in Reactome are the cases where the modification is given using a specific amino acid amide (such as 'L-serine amide') + acyl-GPI (e.g., R-HSA-8940797). In seeking to understand what acyl-GPI is--and how it might differ from GPI, if at all--I checked the CHEBI definition for acyl-GPI. The definition is
<pre>
 A glycosylphosphatidylinositol that can be attached to the C-terminal amino acid of a mature protein
 during posttranslational modification. The phosphatidylinositol group is linked through a carbohydrate-containing
 linker (glucosamine and mannose glycosidically bound to the inositol residue) and via an ethanolamine phosphate
 bridge to the C-terminal amino acid, while the two fatty acids within the hydrophobic phosphatidylinositol group
 anchor the protein to the cell membrane.
</pre>
This sounds exactly like what my understanding of 'regular' GPI is, so I did some further digging. Here is what I found:

(from https://royalsocietypublishing.org/doi/10.1098/rsob.190290)

- EtNP6Manα2(EtNP)6Manα6(EtNP)2Manα4GlcN-(acyl)PI is a mature GPI precursor competent for attachment to proteins.
- The fourth Man (Man4) may further be transferred from Dol-P-Man to the 2-position of Man3 in the mature GPI precursor as a side chain to generate Manα2(EtNP)6Manα2 (EtNP)6Manα6(EtNP)2Manα4GlcN-(acyl)PI, which is also competent for attachment to proteins.
- The GPI moiety in the nascent GPI-APs is immature in its structure and undergoes remodelling reactions to become mature during transport to the PM. Soon after generation of the nascent GPI-APs, the acyl chain linked to the inositol ring is usually removed by GPI-deacylase PGAP1. In some cases, the acyl chain remains in the mature GPI-APs. For example, GPI-APs in erythrocytes maintain the inositol-linked acyl chain. GPI-APs that have (acyl)PI, which has three hydrocarbon chains, associate with the membrane more stably than those that have PI, which has two hydrocarbon chains. The former structure might be useful for maintaining levels of GPI-APs during the very long life of erythrocytes by reducing spontaneous release from the PM.

(from https://www.ncbi.nlm.nih.gov/books/NBK453072/)

- Some GPI anchors are acylated at C-2 of inositol and therefore resistant to PI-PLC but all are sensitive to serum GPI-phospholipase D (GPI-PLD)
- The GPI-PLD reaction also leaves one fatty acid attached to the protein (the inositol acyl group)

My takeaways from this are:
- There is indeed a difference between acyl-GPI and GPI.
- The acyl-GPI definition given in CHEBI is very poor at indicating the difference. The definition almost implies that the acyl-GPI form is the version competent for anchoring, and might be the reason it was chosen as modifier. While true, there are other forms competent for anchoring (at least 3, based on the second bullet point from the first reference). The true difference is that acyl-GPI has an acyl group attached to the inositol, **but this is normally removed**. It is for this reason that I mentioned (in issue #149) that the modifications indicated _might_ be incorrect.
- Unless specifically known to use the acyl form, the CHEBI modifier should probably be CHEBI:24410 "glycosylphosphatidylinositol". These would all be legitimately called GPI-<protein> while those that use the acyl form would be (following from your previous response) acGPI-<protein>.

**Comment by deustp01** [comment]
> * The true difference is that acyl-GPI has an acyl group attached to the inositol, **but this is normally removed**.

Going through the UniProt entries for the first 10 proteins in set R-HSA-8940388 of GPI-anchored proteins that are substrates for cleavage from the plasma membrane shows 9 of 10 with no indication in UniProt as to whether the anchor is GPI or acyl-GPI, and the handy UniProt review of [protein lipidation](https://www.uniprot.org/help/lipid) avoids this distinction as well. More thought required here, but it is tempting to assume, given the ambiguity / lack of evidence in UniProt and protein specific literature to make GPI (no acyl) the modifying group in all cases unless there is specific published evidence for retention of the third fatty acid, in which case we annotate acyl-GPI. Sloppy but acceptable?

In the other non-sloppy direction, all the UniProt entries clearly identify the amino acid residue that the GPI is attached to so we can capture this in the Reactome groupModifiedResidue instance as suggested in #153.

**Comment by nataled** [comment]
Doesn't seem a sloppy solution to me. The fact that it took quite a bit of checking to see what the difference is between 'acyl-GPI' and 'GPI' indicates the potential for confusion, and the CHEBI definition went a long way toward fostering that confusion by blurring the distinction.

**Comment by deustp01** [comment]
Remaining irregular proteoforms cleaned up as described in #153 , so this issue can be closed.
