### ISSUE TITLE
Translate complexes for SGD pathways

### ISSUE THREAD

**Issue by dustine32** [geneontology/pathways2GO#154]
Currently for non-Reactome pathways, reaction controller entities of type Complex are simply translated as a `GO:0032991` "protein-containing complex" individual:
https://github.com/geneontology/pathways2GO/blob/97fe498080ddba4339c233ffffe109c15431209c/exchange/src/main/java/org/geneontology/gocam/exchange/BioPaxtoGO.java#L1525-L1526

For SGD pathways, we should be able to pull out the component proteins and attach them to this `GO:0032991` individual with `has_part` edges. Proposed example (from [SO4ASSIM-PWY](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:SO4ASSIM-PWY?)):
![image](https://user-images.githubusercontent.com/2678599/151675537-f5968aee-d46b-45d7-9a6d-41a7030e2869.png)

An extra step is required to fetch the correct component protein SGD ID given the ID in the BioPAX. For example, the ID in BioPAX for MET5 is "MONOMER3O-22," which isn't in our [SGD lookup file](https://github.com/geneontology/pathways2GO/blob/master/exchange/src/main/resources/YeastCyc/gp_information.559292_sgd). We'll need to supply another lookup file and, as @suzialeksander discovered, these can be pulled from [PANTHER](http://www.pantherdb.org/genes/gene.do?acc=YEAST%7CSGD%3DS000003898%7CUniProtKB%3DP47169). I will create this "MONOMER##-## -> SGD:ID" lookup file from current PANTHER data.

Tagging @thomaspd to ensure these requirements look right.

**Comment by nataled** [comment]
A suggestion here is to use 'has component' (RO:0002180) instead of 'has part'. This will make the description consistent with the standard used by the Protein Ontology, and will allow for specification of stoichiometry when needed.

**Comment by dustine32** [comment]
Good suggestion @nataled! Checking with @thomaspd to see if 'has component' should replace 'has part' here.

One existing blocker is that 'has component' is not encoded in our [ShEx spec](https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shex), which we use to control allowable relations in GO-CAM. We can look at adding it if we need to. Tagging @vanaukenk on this part in case there's already a good reason to exclude it.
