### ISSUE TITLE
Infer locations for activities based on their actors

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#16]
Try to add locations for each activity, and connect them with the occurs_in edge.  If Reactome labels the reactants and products with a GO cellular component term, and it’s the same for all reactants and products, then you can use that GO term for the activity.

**Comment by deustp01** [comment]
The reasoning in @goodb comment on 4 Sep sounds risky. Will this approach correctly handle cases where an activity (enzyme) is located in a membrane and accessible to substrates in an adjoining lumen, so the reaction actually occurs at the membrane - lumen interface and substrates / inputs / left bucket and products / output / right bucket are all in the lumen? And the cases where a protein with transport activity moves physical entities between the two cell components separated by that membrane?

**Comment by goodb** [comment]
@deustp01 just to clarify, we can't generate a MF occurs_in CC relation assertion directly from what I see in the BioPAX as the CC annotations only hang on the physical entities.  The above logic (or adaptations you can suggest) is needed to produce those relations based on the participant CC annotations.  I think we are safe here in that the rule will only activate if all of the participants are annotated to the same CC.  And, if it goes haywire and we end up getting reactions that occur in multiple locations at once, the reasoner raises an alarm.
