### ISSUE TITLE
Confirm correct directionality of Physical Entity regulates Function assertions

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#18]
> I’m not sure where the “involved in positive regulation of [entity]” triplets are coming from.  In GO-CAM a process/function can be regulated but not an entity, so we’d need a way to fix that if we want to keep it.  But I can’t see how this comes out of the Reactome representation.

See e.g. 'Beta-catenin is released from the destruction complex' in http://noctua-dev.berkeleybop.org/editor/graph/gomodel:-80976963

**Comment by goodb** [comment]
To get this converted to GO-CAM, you can try modifying your rule to link the activity that creates the physical entity, rather than the entity itself.  So in your example, if physical_entity is an output of reaction_A, then reaction_A directly_negatively_regulates reaction.

**Comment by goodb** [comment]
Forgot, this rule is actually already in place.  See rule slides 14 and 15 in https://docs.google.com/presentation/d/1_UAQN09WPCA5win5mbMs1ORMALNwiRwMBgZDPuyJEW8/edit?slide=id.g355425beec_0_3#slide=id.g360932a148_0_36 

You can see in the reaction linked above that "Beta-catenin is released from the destruction complex" is positively regulated by 'Phosphorylation of LRP5/6 cytoplasmic domain by CSNKI'

**Comment by deustp01** [comment]
This looks like a legacy problem that Reactome has now fixed. It used to be legal to annotate regulation of an entity. We decided that wasn't useful, removed all such annotations, and changed the curation process so no more can be made. However, depending when the BioPax used here was generated, it might have included some old regulation_of_entity instances.
