### ISSUE TITLE
ABO blood group biosynthesis (R-HSA-9033807)

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#180]
- Create mouse models for this pathway.
      I have created four models for A and B and secreted versus non-secreted respectively. The evidence for the secreted forms are weak in mice, but I though it would be better to have them out there than not. Since the O type is a loss of function, there is  no model and the Reactome Pathways are reflective of that. 
- For the mouse, I have renamed the entities slightly since it looks like these antigens are actually expressed on more than just blood cells and are important developmentally.

**Comment by deustp01** [comment]
It would be orderly to align the human Reactome reactions in this pathway with their RHEA counterparts. I tried and the carbohydrate chemistry involved is too much for me, so defer this until we can get some expert help.

**Comment by ukemi** [comment]
This one was actually done because I found a nice paper about the Abo enzyme. However, this comment applies directly to the Lewis antigens too. I will copy and move that one to tabled.
