### ISSUE TITLE
Gluconeogenesis (R-HSA-70263)

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#186]
- [x] Is the direction of R-HSA-372449 physiologically correct. Most of the references I am looking at say it exports citrate from the mitochondrion. I made this pathway, but the evidence for this transport being accomplished by this gene product is slim, some old experiments with isolated rabbit mitochondria as near as I can tell. So I left the gene product and the evidence off of the mouse pathway. I could add as a TAS because lots of reviews have un-referenced statements saying this is true????
Leads to complicated question about role of this reaction in gluconeogenesis (see comment)
- [x] Should we tidy up the arrows in the Reactome pathway diagram for R-HSA-372448?
Looks hard (see comment)
- [x] Check Reactome subpathways for correctness (i.e., generalize task 1).
- [x] Check Reactome reactions and small molecules for conformity to RHEA.

**Comment by deustp01** [comment]
> * Is the direction of R-HSA-372449 physiologically correct. Most of the references I am looking at say it exports citrate from the mitochondrion.

I need to review the gluconeogenesis pathway. The role of this reaction is to export mitochondrial PEP. On the one hand, this reaction as part of a variant source of carbon skeletons for gluconeogenesis was reviewed and accepted by R.A. Harris who is (was?) an authority. On the other, the standard pathway has oxaloacetate as the entity exported from the mitochondrial matrix to the cytosol, which is then converted to PEP in the cytosol. So is PEP export a bogus alternative source of carbons for gluconeogenesis? In that case the direction of citrate transport is irrelevant because there's no role for it here. Or not? Here is a paragraph from Wikipedia

> In all species, the formation of [oxaloacetate](https://en.wikipedia.org/wiki/Oxaloacetate) from [pyruvate](https://en.wikipedia.org/wiki/Pyruvate) and TCA cycle intermediates is restricted to the mitochondrion, and the enzymes that convert [Phosphoenolpyruvic acid](https://en.wikipedia.org/wiki/Phosphoenolpyruvic_acid) (PEP) to glucose-6-phosphate are found in the cytosol.[[27]](https://en.wikipedia.org/wiki/Gluconeogenesis#cite_note-Voet556-27) The location of the enzyme that links these two parts of gluconeogenesis by converting [oxaloacetate](https://en.wikipedia.org/wiki/Oxaloacetate) to PEP – [PEP carboxykinase](https://en.wikipedia.org/wiki/Phosphoenolpyruvate_carboxykinase) (PEPCK) – is variable by species: it can be found entirely within the [mitochondria](https://en.wikipedia.org/wiki/Mitochondria), entirely within the [cytosol](https://en.wikipedia.org/wiki/Cytosol), or dispersed evenly between the two, as it is in humans.[[27]](https://en.wikipedia.org/wiki/Gluconeogenesis#cite_note-Voet556-27) Transport of PEP across the [mitochondrial membrane](https://en.wikipedia.org/wiki/Mitochondrial_membrane) is accomplished by dedicated transport proteins; however no such proteins exist for [oxaloacetate](https://en.wikipedia.org/wiki/Oxaloacetate).[[27]](https://en.wikipedia.org/wiki/Gluconeogenesis#cite_note-Voet556-27) Therefore, in species that lack intra-mitochondrial PEPCK, [oxaloacetate](https://en.wikipedia.org/wiki/Oxaloacetate) must be converted into [malate](https://en.wikipedia.org/wiki/Malate) or [aspartate](https://en.wikipedia.org/wiki/Aspartate), exported from the [mitochondrion](https://en.wikipedia.org/wiki/Mitochondrion), and converted back into [oxaloacetate](https://en.wikipedia.org/wiki/Oxaloacetate) in order to allow gluconeogenesis to continue.[[27]](https://en.wikipedia.org/wiki/Gluconeogenesis#cite_note-Voet556-27)

**Comment by deustp01** [comment]
> * Should we tidy up the arrows in the Reactome pathway diagram for R-HSA-372448?

Played some with the diagram and couldn't find a way to reduce the number of crossing reaction edges.

**Comment by ukemi** [comment]
Let's talk about the PEP transport on a weeds call. Isn't citrate transport a requirement as the function is an antiporter?

**Comment by deustp01** [comment]
> Let's talk about the PEP transport on a weeds call. Isn't citrate transport a requirement as the function is an antiporter? Early experiments show that you can get PEP out of isolated mitochondria by adding citrate to the media.

That could well be true, and then the Reactome reaction is backwards and we need some othe3r mechanism for PEP export from mitoochondria to cytosol, unless we can evade the need for PEP export. That's the weeds agenda item.

**Comment by deustp01** [comment]
Revisions of Reactome "Gluconeogenesis" to correct errors, align with Rhea, and (partly) sort out fate of mitochondrial PEP are finished. Note are here (David_and_Peter_notes > Gluconeogenesis 2022 > [gluconeogenesis_notes](https://docs.google.com/document/d/1w79lt0CwoALGtl_3MCHwtG8SYBr6Zq7Tq5ekeEXKkjU/edit#) and the pathway details exported from the Reactome web site as a document are in the same folder as [gluconeogenesis_DB_ID_70263](https://docs.google.com/document/d/1GXgqqMOEHo0CPu6iADKlxRWD6jfTMjsbGsEvMDTm3Yo/edit). @ukemi could you review the pathway document and, as time permits, use it to create mouse reactions?

**Comment by ukemi** [comment]
I'll go through these one by one and compare them to the mouse models I made. I know we talked about it, but I can't remember what we decide I should do about hypothetical reactions like "SLC25A1 may exchange mitochondrial PEP for cytosolic anion ". I think we decided I would go ahead and model this one. Apologies for my forgetfulness.

**Comment by ukemi** [comment]
Notes: NB. I don't have ll the reactants in the mouse models yet.

- I'm not seeing the Hrea xrefs on the curators site (eg R-HSA-71783 -> RHEA:21434)). Am I supposed to?
- Reaction Reaction:R-HSA-71783 is called "MDH1 reduces OAA to MAL" but it's catalyzed by MDH2. In mouse model: Gluconeogenesis 1.
- SLC25A10 reaction leads us to mouse Gluconeogenesis 1. 
- R-HSA-198505 In the diagram oxaloacetate is called OA, but in the description is is referred to as OAA. There is also inconsistency in the overall pathway wrt OA or OAA (see R-HSA-198505 vs the output of R-HSA-70501.
- R-HSA-70613 represents the branch in mouse Gluconeogenesis 3.
- Mouse Slc25a11 branch still needs to be done.
- Mouse Slc25a13 was done but not Slc25a12. I added Slc25a12 to gluconeogenesis 3. Evidence for the function is IMP, but I can't find evidence that this paralog is used for gluconeogenesis. Should I leave the function and an evidenceless process?
- For mouse, GOT1 to Pck1 is gluconeogenesis 3. Mdh1 to Pck1 is gluconeogenesis 1.
- For mouse, the Pck2 branch is gluconeogenesis 2. There is no enabler for the mitochondrial transporter yet.

**Comment by deustp01** [comment]
@ukemi OK to close? We'll surely come back to aspects of this as part of insulin signaling / integration of energy metabolism, but all the chore specific to gluconeogenesis look finished.
