### ISSUE TITLE
Signaling by Type 1 Insulin-like Growth Factor 1 Receptor (IGF1R) (R-HSA-2404192)

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#191]
- [x] Create mouse pathways

- gomodel:62e3212700000469--- Igf1 through PI3K
- gomodel:62d0afa500001077--- Igf1 through Shc1 MAp kinase
- gomodel:62f58d8800000378---Igf2 through PI3K (in progress)
- gomodel:62e3212700000469---Igf2 through Shc1 MAP kinase (in progress)

- [x] Should R-HSA-2404199 be mapped to [GO:0048009] insulin-like growth factor receptor signaling pathway?
Better, map its parent [R-HSA-2404192](https://curator.reactome.org/PathwayBrowser/#/R-HSA-2404192&PATH=R-HSA-162582,R-HSA-9006934) "Signaling by Type 1 Insulin-like Growth Factor 1 Receptor (IGF1R)" so the process term propagates onto this reaction ans also its sibling parts "IGF1,2 binds IGF1R" and "IGF1R signaling cascade", and also their children.

- [x] Should R-HSA-2404192, R-HSA-2428933 and R-HSA-2428928 all be mapped to 'insulin-like growth factor receptor signaling pathway' (GO:0048009)? Until we can traverse the Reactome hierarchy, should we assert the GO process to the pathways even if they are parts of the overall pathway? Done as part of the previous fix. If an event lacks a process term, Reactome GAF-generator looks at its parent and grandparent in the event hierarchy to find one, so the fix will propagate this far.

**Comment by deustp01** [comment]
Tasks done (subject to review) so I'm closing this.
