### ISSUE TITLE
Insulin Receptor Recycling  (R-HSA-77387)

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#192]
- [x] Make mouse model---gomodel:62f58d8800001119
- [x] Should the pathway be assigned to insulin receptor recycling (GO:0038020)?
- [x] Should IDA in R-HSA-74723 be IDE (UniProtKB:P14735)?
Typo here? R-HSA-74723 is "endodome acidification". "Insulin degradation" is [R-HSA-74730](https://curator.reactome.org/PathwayBrowser/#/R-HSA-74752&SEL=R-HSA-74730&PATH=R-HSA-162582,R-HSA-9006934), and that reaction has been updated to have IDE ([P14735](https://www.uniprot.org/uniprotkb/P14735/entry)) as catalyst.
- [x] Can cathepsin D ([P07339](https://www.uniprot.org/uniprotkb/P07339/entry)) also catalyze endosomal insulin degradation - check PMID: 9793760 (review of evidence that IDE can degrade insulin), PMID:27703010 (perturbing Zn++ transport into endosomes reduces both IDE and cathepsin D activities)  However- PMID: 8300632 presents evidence that IDE is unlikely to mediate most insulin degradation and suggests a cathepsin D-like activity is the major relevant enzyme, and Authier et al. 2002 [PMID: 11779865](https://pubmed.ncbi.nlm.nih.gov/11779865/) - a later paper from the same group - shows the activity to be cathepsin D. Meanwhile Shen et al. 2006 - [PMID: 17051221](https://pubmed.ncbi.nlm.nih.gov/17051221/) - provide more evidence for a physiological role for IDE in insulin degradation. Focus on these two papers to clean up Reactome annotation of insulin degradation.
DONE by making a candidate set of CTSD and IDE and making this set the physical entity in the catlystActivity for the reaction - same use of candidates to cover weak and contradictory evidence as in the afterthought item in #183 , with the same need for future thought
- [x] #199

**Comment by deustp01** [comment]
Last to-do item converted into its own ticket, #199, so what's left of this ticket is completed.
