### ISSUE TITLE
Change all 'transports_or_maintains_localization_of' relations to 'has_primary_input' 

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#200]
The ontology group recently decided to retire the 'transports_or_maintains_localization_of' relation and replace it with 'has_primary_input'. We need to update the import code to reflect this and be consistent with the way transporters are represented in the ontology and in manually generated GO-CAM models. In addition, if there is already a 'has_input' of the same entity, then we should remove it.

For example, in this model: gomodel:R-HSA-8949215

The individual shown here:
![image](https://user-images.githubusercontent.com/11067494/188132450-76573c37-1916-4018-92b8-57b4f57a200b.png)

should have the 'transports or maintains localization' of Ca2+ changed to 'has primary input' Ca2+ and the 'has input' Ca2+ should be removed.

In fact, since transporter activities do not have the more generic 'has input' and 'has output' relations wrt the transported molecules in ontology definitions, these relations can be removed from the imported models. For transported molecules, the only relationship will be 'transporter activity' has_primary_input some 'transported molecule'.

**Comment by deustp01** [comment]
Should no be easy change before v 82 GO-CAMs because it's simply a swap of "transports or maintains relation" (old) for "has primary input" (new) @dustine32

**Comment by deustp01** [comment]
But what about antiporters? Will it be sufficient to have two primary inputs, in the example here Ca++ [here] and 2 H+ [there]. Note that Ben didn't handle the H+ @ukemi @vanaukenk

**Comment by ukemi** [comment]
Also see #174

**Comment by ukemi** [comment]
Checking:

- [ ] gluconeogenesis
- [ ] cobalamin transport
- [ ] pyruvate metabolism
- [ ] Transport of the SLBP Dependant Mature mRNA
- [ ] GDP-fucose biosynthesis (SLC35A)
- [ ] Olfactory Signaling Pathway (ANO2)
- [ ] ABC transporters in lipid homeostasis (goldmine for testing)

**Comment by ukemi** [comment]
In model R-HSA-9759218, we somehow missed the transported CHEBI:140785 as a primary inputon the R-HSA-9759206 reaction. Instead, it is an input and an output. Is this because the transporter activity is asserted and nothing is inferred?

**Comment by ukemi** [comment]
I think based on the discussion on June 19, 2023 and commented on in #204, we can close this ticket.

**Comment by ukemi** [comment]
Checking:

- [] gluconeogenesis
- [] cobalamin transport---- but see below for weirdness
- [] pyruvate metabolism
- [] Transport of the SLBP Dependant Mature mRNA-- but there are orphan entities in the model that are not in the production model. They seem to be functions of the nuclear pore complex.
- [] GDP-fucose biosynthesis (SLC35A)
- [] Olfactory Signaling Pathway (ANO2)
- [] ABC transporters in lipid homeostasis (goldmine for testing)

**Comment by ukemi** [comment]
@dustine32 
This still looks like it's not working correctly. Even models I checked before (see above) seem to be reverted. 
Model  gomodel:R-HSA-9758890 has reactions that are part of the process that still have the transports_or_maintains_localization_of relations.

**Comment by ukemi** [comment]
WAIT!!!!! My bad. I somhow started looking on production. Sorry @dustine32!

**Comment by ukemi** [comment]
I'm glad you have a good sense of humor. THis all looks good with the known caveat about the reactions not in the pathway that we decided would let slide on Monday's call.
