### ISSUE TITLE
Pyruvate metabolism (R-HSA-70268)

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#209]
- [ ] Make mouse models
       - [ ] Split Reactome pathway into catabolism and biosynthesis. If we don't think this is correct, split into several pyruvate metabolism models
- [x] Missing upstream reaction for R-HSA-373875, R-HSA-71849? YES - fixed
- [x] PMID:21041631 argues that Ldha dirves the reverse reaction while Ldhb drive the forward one. @deustp01, what do you think? Is this good enough circumstantial evidence to split the enablers? Refuted in PMID:21278331. But is that valid? Is the reaction a dead-end steady state? Presumably the products of both directions are consumed. PMID:24686273
NO. A big problem, I think: in PMID:24686273, analyses are done on "[f]rozen brain samples from nonhuman primates ... acquired from naturally deceased or humanely euthanized animals from various zoos and research facilities," not exactly good material to study metabolic fluxes in healthy normal tissue. So while the basic idea is intriguing, that bigger brains handle lactate differently than smaller ones, I don't see the kind of clean cut experimental data that we want for a GO annotation. The fact that the proposed differences are quantitative rate differences, rather than qualitative ones, makes things worse because we aren't good at annotating quantitative differences.
- [x] Reaction R-HSA-71397 can be mapped to GO:0034604. YES - fixed. Also added DLD as activeUnit of catalystActivity

**Comment by deustp01** [comment]
@ukemi  If the mouse models are finished, this ticket can be closed.
