### ISSUE TITLE
glucose metabolism patches

### ISSUE THREAD

**Issue by deustp01** [geneontology/pathways2GO#217]
- [X] add HKDC1 to set of mediators of glucose phosphorylation - reaction [R-HSA-70420](https://curator.reactome.org/PathwayBrowser/#/R-HSA-70326&SEL=R-HSA-70420&PATH=R-HSA-1430728,R-HSA-71387)
- [x] sanity check / review of revised reaction and blurb @ukemi   Sanity confirmed. :)
- [x] is there a mouse ortholog of human GAPDHS? Yes. It is in Table2 on sheet 1, line 13. I used it in the latest analysis on the 'shared' genes.
- [x] confirm absence of human ortholog of mouse Eno1b (expressed retroposon). According to MGI, the human ortholog is ENO1. We allow many-to-one relationships, so ENO1 is also the ortholog of Eno1. Is this good enough? Yes - so in the table, the row for Eno1b will simply have no entry.
- [x] add human ENO4 to set of mediators of [R-HSA-71660 (glycolysis)](https://curator.reactome.org/PathwayBrowser/#/R-HSA-70326&SEL=R-HSA-71660&PATH=R-HSA-1430728,R-HSA-71387) and its reverse reaction [R-HSA-70494 (gluconeogenesis)](https://curator.reactome.org/PathwayBrowser/#/R-HSA-70326&SEL=R-HSA-70494&PATH=R-HSA-1430728,R-HSA-71387). @deustp01 - done. Sanity check, please, (then OK to close again) @ukemi

**Comment by ukemi** [comment]
@deustp01   See above and feel free to close unless there is more.
