### ISSUE TITLE
Deprecated or suboptimal UniProtKB accessions referenced in Reactome

### ISSUE THREAD

**Issue by nataled** [geneontology/pathways2GO#226]
The lists below were found by checking to see if the sub-sequence range indicated in Reactome exists in UniProtKB. Except for the first case, each of these fail because the indicated accessions no longer exist in UniProtKB. I can't guarantee that all such cases were found, as these fit a specific criteria that was easy to detect. That is to say, there might be more complicated cases that were missed by my quick and dirty procedure. I plan on adding additional things to check for as time progresses.

The following accession is a TrEMBL entry fragment that is shorter than the indicated chain segment in Reactome. The issue can be fixed by replacing with the full-length entry P0DTE7:
R-HSA-189001 Q5T084

The following accessions have all been merged into another entry in UniProtKB:
R-HSA-3318212 P01891
R-HSA-3318233 P01891
R-HSA-3318262 P01891
R-HSA-3318272 P01891
R-HSA-3318283 P01891
R-HSA-3318310 P01891
R-HSA-8863968 P01891
R-HSA-1236884 P01892
R-HSA-182252 P01892
R-HSA-182267 P01892
R-HSA-198892 P01892
R-HSA-8863857 P01892
R-HSA-8943104 P01892
R-HSA-983075 P01892
R-HSA-983389 P01892
R-HSA-197573 P01912
R-HSA-2130310 P01912
R-HSA-2130313 P01912
R-HSA-2130521 P01912
R-HSA-2130524 P01912
R-HSA-2130554 P01912
R-HSA-2130668 P01912
R-HSA-2130670 P01912
R-HSA-2214379 P01912
R-HSA-1236774 P03989
R-HSA-1236869 P03989
R-HSA-167770 P03989
R-HSA-198883 P03989
R-HSA-8863980 P03989
R-HSA-983042 P03989
R-HSA-983348 P03989
R-HSA-1236731 P04222
R-HSA-1236883 P04222
R-HSA-199561 P04222
R-HSA-8863872 P04222
R-HSA-983086 P04222
R-HSA-983338 P04222
R-HSA-983365 P04222
R-HSA-2130338 P04229
R-HSA-2130398 P04229
R-HSA-2130410 P04229
R-HSA-2130411 P04229
R-HSA-2130481 P04229
R-HSA-2130507 P04229
R-HSA-2130546 P04229
R-HSA-2214386 P04229
R-HSA-882034 P04229
R-HSA-3318221 P05534
R-HSA-3318227 P05534
R-HSA-3318251 P05534
R-HSA-3318263 P05534
R-HSA-3318284 P05534
R-HSA-3318317 P05534
R-HSA-8863952 P05534
R-HSA-3318222 P10314
R-HSA-3318240 P10314
R-HSA-3318247 P10314
R-HSA-3318279 P10314
R-HSA-3318300 P10314
R-HSA-3318318 P10314
R-HSA-8863904 P10314
R-HSA-1236780 P10319
R-HSA-1236829 P10319
R-HSA-167771 P10319
R-HSA-8863873 P10319
R-HSA-983079 P10319
R-HSA-983345 P10319
R-HSA-983350 P10319
R-HSA-3318217 P13746
R-HSA-3318234 P13746
R-HSA-3318261 P13746
R-HSA-3318270 P13746
R-HSA-3318282 P13746
R-HSA-3318305 P13746
R-HSA-8863901 P13746
R-HSA-2130366 P13760
R-HSA-2130368 P13760
R-HSA-2130409 P13760
R-HSA-2130420 P13760
R-HSA-2130444 P13760
R-HSA-2130572 P13760
R-HSA-2130609 P13760
R-HSA-2214380 P13760
R-HSA-882031 P13760
R-HSA-1235085 P13761
R-HSA-2130401 P13761
R-HSA-2130496 P13761
R-HSA-2130501 P13761
R-HSA-2130562 P13761
R-HSA-2130614 P13761
R-HSA-2130636 P13761
R-HSA-2130702 P13761
R-HSA-2214378 P13761
R-HSA-3318223 P16188
R-HSA-3318238 P16188
R-HSA-3318249 P16188
R-HSA-3318269 P16188
R-HSA-3318298 P16188
R-HSA-3318316 P16188
R-HSA-8863911 P16188
R-HSA-3318209 P16189
R-HSA-3318225 P16189
R-HSA-3318254 P16189
R-HSA-3318271 P16189
R-HSA-3318295 P16189
R-HSA-3318313 P16189
R-HSA-8863846 P16189
R-HSA-3318208 P16190
R-HSA-3318242 P16190
R-HSA-3318252 P16190
R-HSA-3318280 P16190
R-HSA-3318289 P16190
R-HSA-3318311 P16190
R-HSA-8863950 P16190
R-HSA-3318215 P18462
R-HSA-3318228 P18462
R-HSA-3318245 P18462
R-HSA-3318274 P18462
R-HSA-3318287 P18462
R-HSA-3318303 P18462
R-HSA-8863844 P18462
R-HSA-1236790 P18463
R-HSA-1236797 P18463
R-HSA-167757 P18463
R-HSA-198893 P18463
R-HSA-8863890 P18463
R-HSA-983052 P18463
R-HSA-983386 P18463
R-HSA-1236815 P18464
R-HSA-1236833 P18464
R-HSA-167747 P18464
R-HSA-8863931 P18464
R-HSA-983106 P18464
R-HSA-983352 P18464
R-HSA-983392 P18464
R-HSA-1236766 P18465
R-HSA-1236779 P18465
R-HSA-167739 P18465
R-HSA-8863903 P18465
R-HSA-983105 P18465
R-HSA-983346 P18465
R-HSA-983358 P18465
R-HSA-1235089 P20039
R-HSA-2130294 P20039
R-HSA-2130300 P20039
R-HSA-2130346 P20039
R-HSA-2130347 P20039
R-HSA-2130561 P20039
R-HSA-2130573 P20039
R-HSA-2130604 P20039
R-HSA-2214384 P20039
R-HSA-1236783 P30443
R-HSA-1236792 P30443
R-HSA-197579 P30443
R-HSA-8863984 P30443
R-HSA-983102 P30443
R-HSA-983353 P30443
R-HSA-983399 P30443
R-HSA-3318224 P30447
R-HSA-3318229 P30447
R-HSA-3318260 P30447
R-HSA-3318264 P30447
R-HSA-3318293 P30447
R-HSA-3318312 P30447
R-HSA-8863868 P30447
R-HSA-3318210 P30450
R-HSA-3318243 P30450
R-HSA-3318250 P30450
R-HSA-3318273 P30450
R-HSA-3318290 P30450
R-HSA-3318304 P30450
R-HSA-8863924 P30450
R-HSA-3318207 P30453
R-HSA-3318237 P30453
R-HSA-3318244 P30453
R-HSA-3318266 P30453
R-HSA-3318297 P30453
R-HSA-3318319 P30453
R-HSA-6804807 P30453
R-HSA-8863882 P30453
R-HSA-3318218 P30455
R-HSA-3318231 P30455
R-HSA-3318253 P30455
R-HSA-3318281 P30455
R-HSA-3318299 P30455
R-HSA-3318308 P30455
R-HSA-8863959 P30455
R-HSA-3318220 P30456
R-HSA-3318235 P30456
R-HSA-3318255 P30456
R-HSA-3318267 P30456
R-HSA-3318294 P30456
R-HSA-3318309 P30456
R-HSA-8863978 P30456
R-HSA-3318206 P30457
R-HSA-3318230 P30457
R-HSA-3318259 P30457
R-HSA-3318265 P30457
R-HSA-3318288 P30457
R-HSA-3318302 P30457
R-HSA-8863921 P30457
R-HSA-3318216 P30459
R-HSA-3318232 P30459
R-HSA-3318257 P30459
R-HSA-3318268 P30459
R-HSA-3318285 P30459
R-HSA-3318315 P30459
R-HSA-6804781 P30459
R-HSA-8863949 P30459
R-HSA-1236733 P30460
R-HSA-1236819 P30460
R-HSA-167752 P30460
R-HSA-8863902 P30460
R-HSA-983107 P30460
R-HSA-983336 P30460
R-HSA-983397 P30460
R-HSA-1236807 P30461
R-HSA-1236836 P30461
R-HSA-167749 P30461
R-HSA-198881 P30461
R-HSA-8863886 P30461
R-HSA-983066 P30461
R-HSA-983373 P30461
R-HSA-1236738 P30462
R-HSA-1236846 P30462
R-HSA-167761 P30462
R-HSA-198887 P30462
R-HSA-8863970 P30462
R-HSA-983096 P30462
R-HSA-983390 P30462
R-HSA-1236794 P30464
R-HSA-1236822 P30464
R-HSA-167748 P30464
R-HSA-198882 P30464
R-HSA-8863971 P30464
R-HSA-983069 P30464
R-HSA-983393 P30464
R-HSA-1236757 P30466
R-HSA-1236830 P30466
R-HSA-167741 P30466
R-HSA-198885 P30466
R-HSA-8863955 P30466
R-HSA-983045 P30466
R-HSA-983384 P30466
R-HSA-1236772 P30475
R-HSA-1236875 P30475
R-HSA-167753 P30475
R-HSA-198880 P30475
R-HSA-8863937 P30475
R-HSA-983072 P30475
R-HSA-983385 P30475
R-HSA-1236754 P30479
R-HSA-1236862 P30479
R-HSA-167742 P30479
R-HSA-198879 P30479
R-HSA-8863964 P30479
R-HSA-983080 P30479
R-HSA-983360 P30479
R-HSA-1236809 P30480
R-HSA-1236889 P30480
R-HSA-167772 P30480
R-HSA-198890 P30480
R-HSA-8863864 P30480
R-HSA-983087 P30480
R-HSA-983332 P30480
R-HSA-1236886 P30481
R-HSA-1236896 P30481
R-HSA-167735 P30481
R-HSA-8863905 P30481
R-HSA-983061 P30481
R-HSA-983330 P30481
R-HSA-983359 P30481
R-HSA-1236758 P30483
R-HSA-1236842 P30483
R-HSA-167746 P30483
R-HSA-8863928 P30483
R-HSA-983094 P30483
R-HSA-983370 P30483
R-HSA-983405 P30483
R-HSA-1236825 P30484
R-HSA-1236840 P30484
R-HSA-167758 P30484
R-HSA-8863853 P30484
R-HSA-983049 P30484
R-HSA-983328 P30484
R-HSA-983374 P30484
R-HSA-1236747 P30485
R-HSA-1236748 P30485
R-HSA-167745 P30485
R-HSA-8863967 P30485
R-HSA-983041 P30485
R-HSA-983342 P30485
R-HSA-983371 P30485
R-HSA-8855890 P30486
R-HSA-8855893 P30486
R-HSA-8855897 P30486
R-HSA-8855900 P30486
R-HSA-8855902 P30486
R-HSA-8855905 P30486
R-HSA-8863869 P30486
R-HSA-1236874 P30487
R-HSA-1236880 P30487
R-HSA-167766 P30487
R-HSA-8863969 P30487
R-HSA-983067 P30487
R-HSA-983366 P30487
R-HSA-983401 P30487
R-HSA-1236805 P30488
R-HSA-1236843 P30488
R-HSA-167750 P30488
R-HSA-8863929 P30488
R-HSA-983092 P30488
R-HSA-983334 P30488
R-HSA-983404 P30488
R-HSA-1236739 P30490
R-HSA-1236841 P30490
R-HSA-167737 P30490
R-HSA-8863979 P30490
R-HSA-983108 P30490
R-HSA-983372 P30490
R-HSA-983400 P30490
R-HSA-1236763 P30491
R-HSA-1236796 P30491
R-HSA-167764 P30491
R-HSA-8863894 P30491
R-HSA-983071 P30491
R-HSA-983391 P30491
R-HSA-983395 P30491
R-HSA-1236791 P30492
R-HSA-1236848 P30492
R-HSA-167769 P30492
R-HSA-8863985 P30492
R-HSA-983046 P30492
R-HSA-983337 P30492
R-HSA-983396 P30492
R-HSA-1236752 P30493
R-HSA-1236768 P30493
R-HSA-167740 P30493
R-HSA-8863887 P30493
R-HSA-983110 P30493
R-HSA-983364 P30493
R-HSA-983369 P30493
R-HSA-1236789 P30495
R-HSA-1236861 P30495
R-HSA-167765 P30495
R-HSA-8863888 P30495
R-HSA-983109 P30495
R-HSA-983368 P30495
R-HSA-983380 P30495
R-HSA-1236735 P30498
R-HSA-1236801 P30498
R-HSA-167768 P30498
R-HSA-8863958 P30498
R-HSA-983047 P30498
R-HSA-983341 P30498
R-HSA-983355 P30498
R-HSA-2159795 P30499
R-HSA-2220884 P30499
R-HSA-2220895 P30499
R-HSA-2220899 P30499
R-HSA-2220915 P30499
R-HSA-2220924 P30499
R-HSA-8863927 P30499
R-HSA-2159798 P30501
R-HSA-2220877 P30501
R-HSA-2220886 P30501
R-HSA-2220903 P30501
R-HSA-2220914 P30501
R-HSA-2220918 P30501
R-HSA-8863948 P30501
R-HSA-1236854 P30504
R-HSA-1236865 P30504
R-HSA-199550 P30504
R-HSA-8863892 P30504
R-HSA-983064 P30504
R-HSA-983363 P30504
R-HSA-983398 P30504
R-HSA-2159799 P30505
R-HSA-2220881 P30505
R-HSA-2220893 P30505
R-HSA-2220901 P30505
R-HSA-2220907 P30505
R-HSA-2220920 P30505
R-HSA-8863986 P30505
R-HSA-2159802 P30508
R-HSA-2220885 P30508
R-HSA-2220888 P30508
R-HSA-2220898 P30508
R-HSA-2220911 P30508
R-HSA-2220922 P30508
R-HSA-8863951 P30508
R-HSA-2159796 P30510
R-HSA-2220883 P30510
R-HSA-2220891 P30510
R-HSA-2220900 P30510
R-HSA-2220906 P30510
R-HSA-2220916 P30510
R-HSA-8863945 P30510
R-HSA-3318211 P30512
R-HSA-3318241 P30512
R-HSA-3318246 P30512
R-HSA-3318278 P30512
R-HSA-3318286 P30512
R-HSA-3318314 P30512
R-HSA-8863912 P30512
R-HSA-1236764 P30685
R-HSA-1236858 P30685
R-HSA-167751 P30685
R-HSA-198891 P30685
R-HSA-8863875 P30685
R-HSA-983104 P30685
R-HSA-983351 P30685
R-HSA-1236784 Q04826
R-HSA-1236849 Q04826
R-HSA-167736 Q04826
R-HSA-198886 Q04826
R-HSA-8863961 Q04826
R-HSA-983077 Q04826
R-HSA-983343 Q04826
R-HSA-2159803 Q07000
R-HSA-2220879 Q07000
R-HSA-2220887 Q07000
R-HSA-2220905 Q07000
R-HSA-2220913 Q07000
R-HSA-2220923 Q07000
R-HSA-8863943 Q07000
R-HSA-3318214 Q09160
R-HSA-3318239 Q09160
R-HSA-3318256 Q09160
R-HSA-3318277 Q09160
R-HSA-3318296 Q09160
R-HSA-3318306 Q09160
R-HSA-8863962 Q09160
R-HSA-1236844 Q29718
R-HSA-1236871 Q29718
R-HSA-167767 Q29718
R-HSA-8863893 Q29718
R-HSA-983048 Q29718
R-HSA-983329 Q29718
R-HSA-983361 Q29718
R-HSA-1236851 Q29836
R-HSA-1236860 Q29836
R-HSA-167759 Q29836
R-HSA-8863848 Q29836
R-HSA-983038 Q29836
R-HSA-983340 Q29836
R-HSA-983344 Q29836
R-HSA-2159801 Q29865
R-HSA-2220878 Q29865
R-HSA-2220889 Q29865
R-HSA-2220897 Q29865
R-HSA-2220909 Q29865
R-HSA-2220925 Q29865
R-HSA-8863854 Q29865
R-HSA-1236745 Q29940
R-HSA-1236897 Q29940
R-HSA-167760 Q29940
R-HSA-8863926 Q29940
R-HSA-983101 Q29940
R-HSA-983381 Q29940
R-HSA-983383 Q29940
R-HSA-2159797 Q29960
R-HSA-2220882 Q29960
R-HSA-2220890 Q29960
R-HSA-2220896 Q29960
R-HSA-2220908 Q29960
R-HSA-2220919 Q29960
R-HSA-8863965 Q29960
R-HSA-1236777 Q29963
R-HSA-1236824 Q29963
R-HSA-199597 Q29963
R-HSA-8863954 Q29963
R-HSA-983055 Q29963
R-HSA-983377 Q29963
R-HSA-983388 Q29963
R-HSA-2130296 Q29974
R-HSA-2130342 Q29974
R-HSA-2130450 Q29974
R-HSA-2130594 Q29974
R-HSA-2130664 Q29974
R-HSA-2130717 Q29974
R-HSA-2130741 Q29974
R-HSA-2214393 Q29974
R-HSA-882035 Q29974
R-HSA-1235088 Q30134
R-HSA-2130305 Q30134
R-HSA-2130311 Q30134
R-HSA-2130376 Q30134
R-HSA-2130402 Q30134
R-HSA-2130422 Q30134
R-HSA-2130495 Q30134
R-HSA-2130534 Q30134
R-HSA-2214392 Q30134
R-HSA-1235082 Q30167
R-HSA-2130304 Q30167
R-HSA-2130560 Q30167
R-HSA-2130660 Q30167
R-HSA-2130689 Q30167
R-HSA-2130694 Q30167
R-HSA-2130710 Q30167
R-HSA-2130729 Q30167
R-HSA-2214369 Q30167
R-HSA-1236786 Q31610
R-HSA-1236881 Q31610
R-HSA-167744 Q31610
R-HSA-8863862 Q31610
R-HSA-983053 Q31610
R-HSA-983356 Q31610
R-HSA-983367 Q31610
R-HSA-1236765 Q31612
R-HSA-1236878 Q31612
R-HSA-167738 Q31612
R-HSA-8863863 Q31612
R-HSA-983062 Q31612
R-HSA-983333 Q31612
R-HSA-983349 Q31612
R-HSA-1235086 Q5Y7A7
R-HSA-2130355 Q5Y7A7
R-HSA-2130381 Q5Y7A7
R-HSA-2130415 Q5Y7A7
R-HSA-2130428 Q5Y7A7
R-HSA-2130488 Q5Y7A7
R-HSA-2130536 Q5Y7A7
R-HSA-2130541 Q5Y7A7
R-HSA-2214389 Q5Y7A7
R-HSA-1236737 Q95365
R-HSA-1236856 Q95365
R-HSA-167754 Q95365
R-HSA-198888 Q95365
R-HSA-8863975 Q95365
R-HSA-983057 Q95365
R-HSA-983335 Q95365
R-HSA-2159800 Q95604
R-HSA-2220876 Q95604
R-HSA-2220894 Q95604
R-HSA-2220902 Q95604
R-HSA-2220910 Q95604
R-HSA-2220921 Q95604
R-HSA-8863852 Q95604
R-HSA-1235084 Q95IE3
R-HSA-2130351 Q95IE3
R-HSA-2130375 Q95IE3
R-HSA-2130468 Q95IE3
R-HSA-2130542 Q95IE3
R-HSA-2130585 Q95IE3
R-HSA-2130618 Q95IE3
R-HSA-2130645 Q95IE3
R-HSA-2214368 Q95IE3
R-HSA-1235087 Q9GIY3
R-HSA-2130306 Q9GIY3
R-HSA-2130369 Q9GIY3
R-HSA-2130509 Q9GIY3
R-HSA-2130607 Q9GIY3
R-HSA-2130616 Q9GIY3
R-HSA-2130659 Q9GIY3
R-HSA-2130713 Q9GIY3
R-HSA-2214385 Q9GIY3
R-HSA-1236741 Q9TNN7
R-HSA-1236832 Q9TNN7
R-HSA-197587 Q9TNN7
R-HSA-8863934 Q9TNN7
R-HSA-983059 Q9TNN7
R-HSA-983331 Q9TNN7
R-HSA-983402 Q9TNN7
R-HSA-197640 Q9TQE0
R-HSA-2130362 Q9TQE0
R-HSA-2130484 Q9TQE0
R-HSA-2130537 Q9TQE0
R-HSA-2130571 Q9TQE0
R-HSA-2130644 Q9TQE0
R-HSA-2130649 Q9TQE0
R-HSA-2130678 Q9TQE0
R-HSA-2214367 Q9TQE0

**Comment by deustp01** [comment]
The first item R-HSA-3318212 P01891 is one of the results of the massive UniProt merger of human major histocompatibility complex alleles into a small number of gene products. This is a known problem with a known (tedious, painful fix, put off until now). Do you have any easy way of identifying items on your list that are NOT deprecated human major histocompatibility complex gene products, as these will need a separate approach?

**Comment by nataled** [comment]
Do you mean this particular list? All items other than the TrEMBL entry indicated are human HLA entries.

**Comment by deustp01** [comment]
Yes, this list, and "all-HLA" is the answer I was looking for. Thanks.

**Comment by nataled** [comment]
Action taken is described in #232.

**Comment by deustp01** [comment]
More details - 

UniProt originally created large numbers of entries for HLA-A, -B, -C, and -DRB1 antigens, reflecting the enormous number of distinct HLA (histocompatibility) antigens. Human genome sequencing revealed that each of these antigen sets is due to an enormous amount of polymorphic variation of a single gene product. As a result, in 2019, UniProt obsoleted all but one each of HLA-A, -B, -C, and -DRB1 instance. Reactome, meanwhile, had separate entries for many of these allele instances, now obsolete, almost all used to create defined_set instances that were then used to annotate reactions involving HLA antigens.

The fix is to obsolete all of these allele instances in Reactome, with a _deletedInstance attribute in each case pointing form the allele instance to the surviving canonical UniProt sequence for HLA-A ([P04439](http://www.uniprot.org/uniprot/P04439)), HLA-B ([P01889](http://www.uniprot.org/uniprot/P01889)), HLA-C ([P10321](http://www.uniprot.org/uniprot/P10321)), and HLA-DRB1 ([P01911](https://www.uniprot.org/uniprotkb/P01911/entry))

As we do not currently have annotations to show different reactivities of different HLA alleles, e.g., as associated with differential susceptibility to autoimmune diseases, we chose not to annotate any allelic variants by associating geneticallyModifiedResidue instances with canonical forms of the proteins. And these in turn can be mapped to PRO terms created for the original full range of UniProt entries and not obsoleted when UniProt discontinued their terms. This can be done in the future if needed.

The cleanup checklist is [here](https://docs.google.com/spreadsheets/d/1h5fqpfh8v8dX9icx_-FhCeh80dnntoCq/edit#gid=1631278920) in a [folder ](https://drive.google.com/drive/u/0/folders/1Ky2OSit46FCWHI8yIJjU6m8UhSIR_xs2) with additional supporting documentation

**Comment by deustp01** [comment]
> The following accession is a TrEMBL entry fragment that is shorter than the indicated chain segment in Reactome. The issue can be fixed by replacing with the full-length entry P0DTE7:
> R-HSA-189001 Q5T084

This has now been fixed in Reactome as suggested.

**Comment by deustp01** [comment]
All the stale UniProt issues affecting HLA (many) and AMYB (one) have now been fixed, so this ticket can be closed.
