### ISSUE TITLE
Reactome proteoforms that point to deleted UniProt entries

### ISSUE THREAD

**Issue by deustp01** [geneontology/pathways2GO#232]
UniProt originally created large numbers of entries for HLA-A, -B, -C, and -DRB1 antigens, reflecting the enormous number of distinct HLA (histocompatibility) antigens. Human genome sequencing revealed that each of these antigen sets is due to an enormous amount of polymorphic variation of a single gene product. As a result, in 2019, UniProt obsoleted all but one each of HLA-A, -B, -C, and -DRB1 instance. Reactome, meanwhile, had separate entries for many of these allele instances, now obsolete, almost all used to create defined_set instances that were then used to annotate reactions involving HLA antigens.

The fix is to obsolete all of these allele instances in Reactome, with a _deletedInstance attribute in each case pointing form the allele instance to the surviving canonical UniProt sequence for HLA-A ([P04439](http://www.uniprot.org/uniprot/P04439)), HLA-B ([P01889](http://www.uniprot.org/uniprot/P01889)), HLA-C ([P10321](http://www.uniprot.org/uniprot/P10321)), and HLA-DRB1 ([P01911](https://www.uniprot.org/uniprotkb/P01911/entry))

As we do not currently have annotations to show different reactivities of different HLA alleles, e.g., as associated with differential susceptibility to autoimmune diseases, we chose not to annotate any allelic variants by associating geneticallyModifiedResidue instances with canonical forms of the proteins. This can be done in the future if needed.

The cleanup checklist is [here](https://docs.google.com/spreadsheets/d/1h5fqpfh8v8dX9icx_-FhCeh80dnntoCq/edit#gid=1631278920) in a [folder ](https://drive.google.com/drive/u/0/folders/1Ky2OSit46FCWHI8yIJjU6m8UhSIR_xs2) with additional supporting documentation

**Comment by deustp01** [comment]
Clean-up is complete, so this issue can be closed. @nataled

**Comment by nataled** [comment]
Just an FYI: PRO retained all those allelic variants that were deprecated in UniProtKB.

**Comment by nataled** [comment]
I have verified that, in all cases given in the first sheet of the indicated spreadsheet, the PRO entry for the deprecated UniProtKB entries is given by PR:<deprecated accession>.
