### ISSUE TITLE
Report for missing ChEBI IDs in release 83 work

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#236]
We would like to have a report that lists ChEBI identifiers that fail to be recognized during the Release 83 import. https://github.com/geneontology/pathways2GO/issues/221
If possible, the report should also include the model identifier and whether or not the model fails the ShEX.

**Comment by dustine32** [comment]
Here is the list of CHEBI classes in Reactome models that do not appear to be in NEO:
[nonresolving_chebi.txt](https://github.com/geneontology/pathways2GO/files/10922497/nonresolving_chebi.txt)

This list was made with a SPARQL query to check for any classes having a `CHEBI:` prefix but no `subClassOf` connection to chemical entity CHEBI:24431.

**Comment by nataled** [comment]
Some of these are subClassOf CHEBI:36342 "subatomic particle", which is a sibling of 'chemical entity'. In fact, one of them is 'subatomic particle' itself. Here is the list:
CHEBI:10545
CHEBI:30212
CHEBI:33233
CHEBI:33252
CHEBI:36338
CHEBI:36340
CHEBI:36341
CHEBI:36342
CHEBI:36347

The remainder are classed under 'chemical entity' (at least in CHEBI).

**Comment by ukemi** [comment]
Interesting. Thanks @nataled.

**Comment by ukemi** [comment]
Looking at the models, these don't seem to be the issue. I think I have determined what is causing most of the Shex problems. There is no shape for small molecule regulators.

**Comment by deustp01** [comment]
Thinking that tickets should set out well-delimited problems / chores, it might be best for sanity to close this ticket - diagnosis is done - and create a new ticket that refers to this one for the clean-up?

**Comment by ukemi** [comment]
- [ ] Shex violations- https://github.com/geneontology/go-shapes/pull/300
- [ ] Missing ChEBI identifiers analysis
- [ ] pH 7.3 checks
