### ISSUE TITLE
YeastPathways import: "source: null:*pathway-name" instead of "source: SGD:*pathway-name*"

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pathways2GO#242]
Spotchecking these YeastPathways models, and for Evidencethe source field for the CC term "occurs in (cytosol)" has a `null:` prefix before whatever pathway name: 
![Screenshot 2023-04-12 at 23 06 48](https://user-images.githubusercontent.com/13735608/232170036-cb560327-7a54-4000-b702-3dadacf8edc3.png)

Same for other models, like http://noctua-dev.berkeleybop.org/editor/graph/gomodel:PWY3O-123? - the green evidence box on the cytosol term has the `null:` prefix.  In the same model, the Evidence fields for the rest of the bits are fine, and show `source: SGD:SERSYN-PWY` or whatever the pathway is. 

@dustine32

**Comment by suzialeksander** [comment]
![Screenshot 2023-04-12 at 23 18 41](https://user-images.githubusercontent.com/13735608/232171128-2bd09f37-50a4-4f93-a942-b0dd712ede94.png)

**Comment by dustine32** [comment]
The `source` field issue should be handled once #126 is solved.

**Comment by dustine32** [comment]
Oh, I see now there's a conditional that sets `source` prefix depending on `providedBy` value and the case for SGD didn't match what we were currently supplying:
![image](https://user-images.githubusercontent.com/2678599/236964401-3585470f-6abb-4f90-a135-89bd1ef488c4.png)
https://github.com/geneontology/pathways2GO/blob/63b853ae044ede6d5e679a602e4460ac50ed78fe/exchange/src/main/java/org/geneontology/gocam/exchange/GoCAM.java#L209
AFAIK this discrepancy was only occuring for rule-inferred edges. I'll fix it by changing the conditional value to `https://yeastgenome.org`.
