### ISSUE TITLE
providedBy: URLs inconsistent between users from same group

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pathways2GO#243]
YeastPathways models in dev show two slightly different URLs for SGD contributors: 

contributor: GOC:sgd_curators
providedBy: https://yeastgenome.org

contributor: https://orcid.org/0000-0001-6787-2901
providedBy: http://www.yeastgenome.org

**Comment by suzialeksander** [comment]
looks like all the SGD curators have http://www.yeastgenome.org, and very technically that should probably be http**s**://www.yeastgenome.org/, but it's just the GOC:sgd_curators that's an outlier at current

@dustine32 I thought this would be an easy fix but I don't see where the "https://yeastgenome.org/" is assigned

**Comment by dustine32** [comment]
Just realized I fixed this as part of https://github.com/geneontology/pathways2GO/pull/250#issuecomment-1540818616.

**Comment by suzialeksander** [comment]
Fixed!
