### ISSUE TITLE
Header on the "clone evidence" popup has a gomodel: that doesn't match the model title 

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pathways2GO#244]
Leaving this for reference in case it becomes a bug: 
![Screenshot 2023-04-12 at 23 18 41](https://user-images.githubusercontent.com/13735608/232172666-f9fe0fa5-ead7-4796-92cd-4b12151d78a9.png)

The header on the "clone evidence" popup has a gomodel: that doesn't match the model title.  A bit confusing to the curator, but not wholly unexpected:

According to @dustine32: 

> Those (`gomodel:PSERTRANSAM-RXN` and `gomodel:YOR184W-MONOMER_PSERTRANSAM-RXN_controller`) are the IRIs for the reactions in the model. It may get confusing and/or conflicts if the same reaction is used in multiple models.

>I am used to seeing IRIs use the pattern `gomodel:{model_id}/{individual_id}` to prevent ID collisions so it might become a bug??

**Comment by dustine32** [comment]
Yes, new ID standard for YeastPathways - Ex: `gomodel:SERSYN-PWY/PSERTRANSAM-RXN`

**Comment by suzialeksander** [comment]
@dustine32, this seems to be more a "fun fact for those that know the lore" rather than seriously affecting the YP project, for now.  Is it ok to close? any tags/keywords that should be added to make this findable if it comes up again, or any reason to think this might be an issue for import anymore?

**Comment by dustine32** [comment]
@suzialeksander Yep, I think it's ok to close for now. I don't know how useful a label of "ID convention" would be but we can at least associate it with https://github.com/geneontology/pathways2GO/issues/189.
