### ISSUE TITLE
YeastPathways models have imaginary DB ref

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pathways2GO#254]
Less technical description: 
Currently the DB ref for a model is something like `SGD:SERSYN-PWY`, which isn't actually a SGD ID & doesn't appear to be mapped to anything.

More technical description:
Referencing https://github.com/geneontology/pathways2GO/issues/37 as it contains some history on how the `source` field was populated. I'm now realizing this becomes the [DB:Reference](http://geneontology.org/docs/gene-product-association-data-gpad-format/#dbreferences) (aka PMID of evidenced literature) column in GPAD and so should follow the [GPAD spec](http://geneontology.org/docs/gene-product-association-data-gpad-format/). To conform to the spec, this `source` needs to be a CURIE.

Note that `source` currently "works" for Reactome with an example CURIE `Reactome:R-HSA-112303` correctly [expanding](https://github.com/prefixcommons/biocontext/blob/bc1132de96a25d7625b071b0482e0328325b84a7/registry/go_context.jsonld#L39) and forwarding to its Reactome [pathway page](https://reactome.org/content/detail/R-HSA-112303). However, does this "work" for the GPAD reference column? While syntactically correct, is this value meaningful as a literature reference?

For YeastPathways, conveniently, identifiers.org already has `sgd.pathways` [registered](https://registry.identifiers.org/registry/sgd.pathways) so we can just use this. But do we need to add this to a context JSONLD such as [go_context.jsonld](https://github.com/prefixcommons/biocontext/blob/master/registry/go_context.jsonld)? Like:
```
        "sgd.pathways": "https://identifiers.org/sgd.pathways/", 
```

_Originally posted by @dustine32 in https://github.com/geneontology/pathways2GO/issues/126#issuecomment-1190839092_

**Comment by suzialeksander** [comment]
Two proposed options:
1. Have SGD add these 220 pathways (names like `LIPASYN-PWY-1` `PWY-5703`) to work in the yeastgenome.org search disambiguation (which is oddly in the dbxrefs.yaml under SGD_LOCUS): 

>       url_syntax: https://www.yeastgenome.org/search?q=[example_id]&is_quick=true
>       example_id: SGD_PWY:LIPASYN-PWY-1
>       example_url: https://www.yeastgenome.org/search?q=SGD_PWY:LIPASYN-PWY-1&is_quick=true

2. Add a new namespace in the dbxrefs.yaml like`SGD_PWY:` . This would go to https://pathway.yeastgenome.org/ and end up at https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=NIL&object=PWY3O-123&redirect=T

**Comment by suzialeksander** [comment]
SGD is opting for door #2, changing dbxrefs.yaml.  I'll put in a PR.

**Comment by suzialeksander** [comment]
@dustine32 the `SGD_PWY:` should now be a real thing, let me know if you need anything else on my end

**Comment by dustine32** [comment]
@suzialeksander Awesome, thank you! I'll update the code and get some new models into noctua-dev.
