### ISSUE TITLE
occurs_in for Yeast Pathways is incorrect

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pathways2GO#273]
Newly found issue: gomodel:YeastPathways_PWY-2201 / Pathway: folate transformations I

SHM1 and MIS1 (Mitochondrial C1-tetrahydrofolate synthase) should both be mitochondrial, but there are no "occurs_in mitochondria", they're all cytosol. I'm looking at the BioPax 3,  I don't see where the CC comes from except 

         <bp:cellularLocation>
          <bp:CellularLocationVocabulary rdf:ID="CellularLocationVocabulary2368">
            <bp:term rdf:datatype="http://www.w3.org/2001/XMLSchema#string">cytosol</bp:term>
            <bp:xref>
              <bp:UnificationXref rdf:ID="UnificationXref2369">
                <bp:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">GO:0005829</bp:id>

@dustine32 Is there a way to check if this is an annotation issue? Are there any models that have more than one CC, for example? Does the code apply the cellularLocation to everything in the model or just specified entities- I'm not incredibly fluent in BioPax.

**Comment by dustine32** [comment]
@suzialeksander As far as I can tell, this is an annotation issue. Yes, the BioPAX files have cytosol for all proteins but 3 models have plasma membrane (GO:0005886) for certain small molecules:
PWY3O-94
PYRIMID-RNTSYN-PWY
TCA-EUK-PWY

For the example proteins [SHM1](https://pathway.yeastgenome.org/gene?orgid=YEAST&id=YBR263W-MONOMER#) and [MIS1](https://pathway.yeastgenome.org/gene?orgid=YEAST&id=YBR084W#), I can't really tell on the pathway.yeastgenome.org pages (aside from having "mitochondrial" in the labels) what the cellular locations are. Like, is there a field that stores location in YeastPathways that then is meant to be exported out to the BioPAX?

**Comment by suzialeksander** [comment]
SGD will curate these manually. Closing.
