### ISSUE TITLE
Exclude "molecular event" for reactions that don't occur in yeast

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pathways2GO#284]
Email from @thomaspd 

> We’d had an email exchange about this last year, and I just noticed that we haven’t yet addressed this in the conversion code. Before we do anything, I wanted to revisit the issue again, in the context of a specific example pathway that still has a couple of “molecular events” instead of molecular functions, which means we weren’t able to make a GO-CAM activity (MF) because there’s no yeast gene product doing the catalysis:
> 
> https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=PATHWAY&object=YEAST-RIBOSYN-PWY&detail-level=2
> 
>  
> 
> The pathway has an entire branch of three consecutive “molecular events” in the GO-CAM, where each one is labeled with an E.C. number in YeastPathways. None of these three reaction steps in the pathway are associated with any yeast genes. The first reaction is labeled as E.C. 1.1.1.302, which is the same E.C. as RIB7, even though SGD annotators didn’t associate it with RIB7. The second reaction has a more general E.C. (3.5.4.-) but mousing over shows a specific reaction that may not be in E.C. The third reaction is labeled with E.C. 3.1.3.104. If I look for information about this entry at:
> 
> https://enzyme.expasy.org/EC/3.1.3.104
> 
> I see that it’s annotated as being found only in bacteria and plants. So I wanted to revisit my suggestion that we should handle these “molecular events” by leaving them out of the YeastPathways, since they appear, at least in this case, to correspond to reactions that are known to happen in some organisms but have not been demonstrated in yeast. I’m wondering if Pathway Tools just makes placeholders for reactions that could potentially exist even if they are actually absent from a particular organism.

@dustine32 if the molecular event is for a reaction that's not in yeast, they shouldn't be in the model.  Is this something you can control in the code?

**Comment by thomaspd** [comment]
After talking at the last GO managers meeting, and after looking at some more pathways where it appears like some of the missing gene products are genuine gaps that could be filled by curation, I think maybe we should go with Suzi's original suggestion to leave these in the automatic conversion, and then let curators manually remove the ones they think aren't found in yeast. @suzialeksander what do you think?

**Comment by suzialeksander** [comment]
I think this is fine- we'll have to look at each part individually anyway. 

To be completed by curation.
