### ISSUE TITLE
Make appropriate pathways cyclical 

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/pathways2GO#285]
On the managers call, @thomaspd mentioned the pathways that should be cycles are not because of limitations in the BioPax (steps). It would be nice if these could be fixed on import. 

@dustine32 does this sound feasible? What (if anything) would you need from curators- list of affected pathways? Not sure if this can be done on import/code side or should be part of the planned manual curation.

**Comment by dustine32** [comment]
@suzialeksander Yes, before actually trying this, it does sound feasible as long as we emit only one instance of each location-specific molecule (e.g., ChEBI) class. The code currently matches up only outputs of each pathway step with the inputs of their next steps. If we expand this to match inputs to inputs and outputs to outputs, this should solve branched and cyclical pathways.

Branched pathway example: [PWY3O-6635](https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=NIL&object=PWY3O-6635&redirect=T) superpathway of phosphatidate biosynthesis
Cyclical pathway example: [PWY3O-94](https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=PATHWAY&object=PWY3O-94) superpathway of TCA cycle and glyoxylate cycle

**Comment by suzialeksander** [comment]
That sounds like what Paul was saying. I think that would be ok, as long as it didn't get confused if some same molecules are in/outputs of different steps- so on the TCA cycle, "H2O + acetyl-CoA" as input with the output "H+ coenzyme A" occurs both from malate synthase and citrate synthase.

**Comment by suzialeksander** [comment]
Update: @dustine32 will try to work on this after the Reactome2GO meeting this week

**Comment by suzialeksander** [comment]
This is a task SGD curators are working on.
