### ISSUE TITLE
Add code to disentangle downstream events when the active unit is the same in two different reactions

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/pathways2GO#292]
From the 2023-10-12 Reactome2GO meeting at NYU:

In the [nuclear signaling by ERBB4 model](https://reactome.org/PathwayBrowser/#/R-HSA-1236394&SEL=R-HSA-1251985&PATH=R-HSA-162582,R-HSA-9006934), regulation of GFAP and S100b are an example of this situation.

**Comment by dustine32** [comment]
The red arrows below show how the two `causally_upstream_of` edges should really be connected:
![image](https://github.com/geneontology/pathways2GO/assets/2678599/07a83de9-1d30-4745-8b8d-06f47db1ec1f)

**Comment by ukemi** [comment]
@dustine32 discovered this is a data issue at source. The upstream reaction in Reactome is incorrect and needs to be changed to the S100B-gene binding and not the GFAP gene binding.

**Comment by deustp01** [comment]
> The upstream reaction in Reactome is incorrect

now fixed
