### ISSUE TITLE
Add active unit information from Reactome

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#31]
For some reactions, like '[activated human TAK1 phosphorylates MKK3/MKK6](https://reactome.org/PathwayBrowser/#/R-HSA-450294&SEL=R-HSA-450346&PATH=R-HSA-168256,R-HSA-168249,R-HSA-168898,R-HSA-168164)', Reactome says that a protein complex (or set) catalyzes the reaction, and then indicates a specific member of that complex (or set) as the 'active unit'.  In this case, the modified protein 'p-T184,T187-MAP3K7' is the active unit and 'Activated TAK complexes' is the 'complex'.  Note that several of the members of 'Activated TAK complexes' contain a MAP3K7.

To close this issue: 

- [x] identify the active unit (which will require accessing Reactome in another way than the BioPAX as this information is not in the BP level 3 export)
- [x] Make the 'enabled by' edge for the reaction (MF) link to this active unit protein.
- [x] Link the catalytic complex(es) to the reaction (MF) via 'contributes to' relationship(s).

**Comment by goodb** [comment]
@fabregat what do you think would be the best way to access the active unit information ?

**Comment by goodb** [comment]
I don't see a way to get the info. from the Web API but did manage to find it in the graph database.  Noting to self query will look something like: 
MATCH (reaction:Reaction{stId:"R-HSA-450346"})-[:catalystActivity]->(catalyst:CatalystActivity)-[:activeUnit]->(active_unit:PhysicalEntity)
RETURN reaction, catalyst, active_unit

**Comment by goodb** [comment]
Working now with information gathered from the graph database.  Uncomfortable about longevity of this solution..  Would prefer to use one standard and extend that standard as needed (e.g. by adding content into the BioPAX export even when its not in the specification - doing so should not break any semantic web capable code that consumes it.)

**Comment by fabregat** [comment]
To get the info using the [ContentService](https://reactome.org/ContentService), you will need two queries. Let's take the reaction you shared above (R-HSA-450346). The first query is

1) [`https://reactome.org/ContentService/data/query/R-HSA-450346/catalystActivity`](https://reactome.org/ContentService/data/query/R-HSA-450346/catalystActivity)

Its result is in TSV format containing **Identifier**, **DisplayName** and **SchemaClass**:

> 177696	protein serine/threonine kinase activity of Activated TAK complexes [cytosol]	CatalystActivity

Taking the first column, then you perform a second query

2) [`https://reactome.org/ContentService/data/query/177696/activeUnit`](https://reactome.org/ContentService/data/query/177696/activeUnit)

And its results, follows the same format, and it is

> R-HSA-202527	p-T184,T187-MAP3K7 [cytosol]	EntityWithAccessionedSequence

Please note that in case you need more info about the last EWAS, then you can query the ContentService:

3) [`https://reactome.org/ContentService/data/query/R-HSA-202527`](https://reactome.org/ContentService/data/query/R-HSA-202527)

Since you've also mentioned the [graph database](https://reactome.org/dev/graph-database), I strongly recommend you to go this way since it will be faster on your end ;)

The query you suggest is almost correct, and I say almost because for other identifiers corresponding to other types of reactions (BlackBoxEvent for example) it wouldn't work. In any case, the fix is very easy (please see in bold what I've changed):

> MATCH (reaction:**ReactionLikeEvent**{stId:"R-HSA-450346"})-[:catalystActivity]->(catalyst:CatalystActivity)-[:activeUnit]->(active_unit:PhysicalEntity)
> RETURN reaction, catalyst, active_unit

Related to extending the BioPax format in favour of the options above, maybe we could set a meeting to discuss how to go forward?

**Comment by goodb** [comment]
@fabregat thank you!  Indeed I'm happy that I ended up down the graphdb path.  It would have been quite slow the other way and this will clearly open up more possibilities.  (But see my email about problems getting your Java access project to build).  I updated my query to include ReactionLikeEvent and seems to be working - captures about 120 more relations.  

Yes, I'd like to talk about how to get this information into your BioPAX export somehow.  Although it would end up off-standard, an extension to the BioPAX ontology or even a hacky use of xrefs or comments could do the job for the short term and provide an example for extending the standard in the future.  It might also be worth talking with @cmungall about new standardized ways for sharing graph databases like your neo4j version.  Longer term, that work might end up replacing the BioPAX stuff, though I think that is likely a way off.

**Comment by goodb** [comment]
Need to convert to take the data out of a new provided statement in comments on Control And Catalysis entities.  e.g. activeUnit: #Protein26 .   This will replace the code that uses the graphdb.  Future versions of the biopax export will contain this information.  Note that the active unit e.g. #protein26 may or may not be otherwise linked to in biopax file, but should be present.

**Comment by goodb** [comment]
Question for @ukemi and @deustp01 when we have an active unit annotated on a complex that is not catalyzing but rather exerting a regulatory effect on the reaction, how should that be captured?  For catalysis we have the [enabled by / contributes to structure](https://github.com/geneontology/pathways2GO/issues/34#issuecomment-456606763).  What should we use for regulates?  e.g. protein involved_in_negative_regulation of reaction, complex has_part protein, complex ?relation? reaction  ?

**Comment by goodb** [comment]
I think I can answer my own question here.  The plan is to go ahead assert the involved_in_regulation triple for the active entity.  This happens in the first phase of processing.  It will be picked up in the second phase and converted to the pattern from #39

**Comment by goodb** [comment]
Test with RAF-independent MAPK1/3 activation

**Comment by cmungall** [comment]
Hmm, I haven't thought this one through but that relation is mostly
intended for inference rather than assertion

**Comment by deustp01** [comment]
In Reactome, "active unit" is an attribute of the catalyst activity class only, and is meant to be used when the physical entity doing the catalysis is a complex and one protein or subcomplex part is known to be the actual catalyst. We don't have an equivalent attribute on our regulator class (but it sounds like a good idea).

**Comment by goodb** [comment]
@deustp01 I'm seeing it in the biopax that @guanmingwu enhanced with the additional activity information.  For example, here is a biopax control structure showing negative regulation with an annotated active unit (PEA15) for the reaction "Phosphorylated MAPKs translocate into the nucleus" in pathway "RAF-independent MAPK1/3 activation"
<img width="611" alt="screen shot 2019-02-16 at 8 41 14 pm" src="https://user-images.githubusercontent.com/2086122/52908500-dfb9f780-322b-11e9-9320-b18a025ae1a9.png">

This kind of thing is present in both the test file he sent for this pathway and looks like it shows up 66 times for the full Homo Sapiens batch export.  

Is this an error?  I don't see any indication of active unit on the corresponding control element in the public interface or the [curatorial interface](http://reactomecurator.oicr.on.ca/PathwayBrowser/#/R-HSA-112409&SEL=R-HSA-5674387&PATH=R-HSA-162582,R-HSA-5683057,R-HSA-5684996) for that reaction.

**Comment by goodb** [comment]
For what its worth, this is what the end result of the current transformation looks like for this one.  Note that the involved_in_regulation triple (I mentioned above and start this process with) ends up being replaced with the [regulatory binding activity pattern](https://github.com/geneontology/pathways2GO/issues/39#issuecomment-464167940).  (Sorry Neo not loaded,  UniProtKB:Q15121 = PEA15.)

<img width="898" alt="screen shot 2019-02-16 at 9 18 01 pm" src="https://user-images.githubusercontent.com/2086122/52908752-d5e6c300-3230-11e9-9739-0a9774c4a127.png">

**Comment by deustp01** [comment]
@goodb The problem is at my end. Despite what I said on Saturday, "active unit" is an optional attribute of regulation instances and it has been used to annotate 578 of the 2108 regulation instances in our released database. The annotation criteria should be the same as for active unit annotations of catalyst activity: the physical entity associated with the activity is a complex of two or more different gene products and there is evidence that allows one of them (or a subcomplex) to be identified as the part of the complex that is directly doing the catalysis or regulation. 

I don't know how to do a query to filter out the non-human instances but they are a minority, so we have a new problem: why only 66 problem instances detected when it looks like there should be hundreds? Guanming will be back in about a week, I think.

Sorry.

**Comment by goodb** [comment]
@deustp01 Let me confirm the 66 number with a more careful test.  (I pulled that out with a very fast hack to see if there was more than one.. want to double check).  In the meantime, do you think the representation depicted in the figure above is suitable for representing this information in GO-CAM?

**Comment by ukemi** [comment]
My initial reaction to the figure above is that there is nothing enabling the binding reaction in the lower middle. It only has an input. That seems weird.

**Comment by goodb** [comment]
Okay, I made a mistake with the 66 number.  Shouldn't have reported that specifically before verifying.  

For the homo sapiens release that Guanming prepared for me in January I see:
7085 Control constructs of which 1713 contain active unit annotations.  
There were 5252 Catalysis events (1213 with active units) and 1833 regulatory events (with 500 active units).  
Also, there were 204 control events with more than one active unit annotated.  e.g. the catalyst in [the reaction 'Phosphorylation of PLC-gamma1'](https://reactome.org/PathwayBrowser/#/R-HSA-202403&SEL=R-HSA-202248&PATH=R-HSA-168256,R-HSA-1280218)

**Comment by goodb** [comment]
On the representation, it would be good if @ukemi could weigh in.  From my perspective I never really understood what was wrong with the initial entity involved_in_regulation_of function pattern but everyone pretty adamantly did not like that.  The only difference here as compared to [that one](https://github.com/geneontology/pathways2GO/issues/39#issuecomment-464167940) is that we have pulled the active unit out of its complex.  

According to the pattern, If the reaction there (Phosphorylated MAPKs translocate to the nucleus) had something enabling it, that something would be attached as an enabler of the binding

**Comment by ukemi** [comment]
We need to make sure that each of the above types of active entities are represented in the pathways that we systematically review. 

Can we get a reactome identifier and the corresponding models for:
A control construct that does not have an active unit.
A control construct that does have an active unit.
A catalysis event that does not have an active unit.
A catalysis event that does have an active unit.
A regulatory event that does not have an active unit.
A regulatory event that does have an active unit.

The reaction above is exactly why I have argued that kinase activity and phosphorylation represent a molecular function and a biological process respectively. In this case the activities of two independent kinases modify two different residues on the target protein. This is what I have always argued is the process of phosphorylation. @vanaukenk 
In an activity flow model where we don't allow the process to exist, I guess we could just have a branch that has both kinase activities and then those kinase activities flow back together to the next downstream function.

**Comment by ukemi** [comment]
> On the representation, it would be good if @ukemi could weigh in. From my perspective I never really understood what was wrong with the initial entity involved_in_regulation_of function pattern but everyone pretty adamantly did not like that. The only difference here as compared to that one is that we have pulled the active unit out of its complex.

It is misleading to me. It looks like the chemical is being regulated.

**Comment by goodb** [comment]
> It is misleading to me. It looks like the chemical is being regulated.

I don't really want to argue against everyone opposed to the use of the [involved_in properties](http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002428) but the relation is unambiguous - the continuant entity is involved in the regulation of the occurrent function.  Like many things, this may be confusing in the display.

**Comment by ukemi** [comment]
I completely agree that it is not technically wrong, but it blurs over the actual activity that is occurring. Don't you think we should state how the continuant is involved if we know? I don't want people to be mislead into thinking this represents, for example, AMP regulates PFK activity. We have worked so hard to tell people that something is happening regulates PFK activity.

I agree that the display makes it more confusing.

**Comment by deustp01** [comment]
I get the point that if the chemical citrate is the product of reaction 1, and that citrate molecule regulates reaction 2, the Reactome assertion that citrate regulates reaction 2 maps cleanly and reliably onto the assertion that reaction 1 regulates reaction 2. What about cases where reaction 2 is responsive to the level of a small molecule and that level is determined by the flux through several reactions, some generating citrate and some consuming it? There is certainly not a 1:1 mapping, and a many to one mapping, even with flags to identify positive and negative contributors is misleading without quantitative / stoichiometric features that neither of us want to indicate how much each of the contributing reactions contributes.

Generalizing, anywhere that there is a pipeline, A acts on B acts on C acts on D and the organization of the pipeline physically excludes participation by entities outside the pipeline, mapping entities to the reactions that produce them works cleanly. Whenever we're dealing with a system where there are several sources and sinks affecting the level of an entity that does something to another reaction / activity, it's hard to see how to get a reliable mapping, especially if the mapping is also supposed to yield a direction (i.e., the net effect is to raise citrate levels and thus promote / lower citrate levels and thus suppress a downstream activity).

Hard for me to see, anyway. If there's a fix I'm missing, we move on to implementing it in the Reactome to GO-CAM process.

**Comment by deustp01** [comment]
> Also, there were 204 control events with more than one active unit annotated. e.g. the catalyst in [the reaction 'Phosphorylation of PLC-gamma1'](https://reactome.org/PathwayBrowser/#/R-HSA-202403&SEL=R-HSA-202248&PATH=R-HSA-168256,R-HSA-1280218)

This looks like bad annotation practice, and that the curator is trying to make one reaction instance do the job of at least two, by cramming two distinct ways of providing catalytic activity into a single catalystActivity instance attached to a single reaction instance.

If Ben could provide the list of 204 control events with more than one active unit annotated, I will take a look to see if this initial reaction is right and if so, work with Reactome people to come up with a plan for changed annotation practice henceforth and cleanup of the legacy instances. My hunch is that clean-up of the annotations could probably be automated, but all the new reactions that will appear will need to be laid out manually in pathway diagrams and this part will be painful.

**Comment by goodb** [comment]
@deustp01 sorry again, it was 108 multi-active-unit reactions.  Got fooled as some of them appear in multiple pathways.  That probably inflated some of the other counts above.  Here is the list of reactions:
- [R-HSA-2976551 NOTCH2 stimulates GZMB transcription](https://reactome.org/content/detail/R-HSA-2976551)
- [R-HSA-210426 Glutamate synaptic vesicle docking and priming](https://reactome.org/content/detail/R-HSA-210426)
- [R-HSA-912458 Meiotic Strand Invasion](https://reactome.org/content/detail/R-HSA-912458)
- [R-HSA-8857583 LINC01139 promotes phosphorylation of HIF1A by PTK6 and LRRK2](https://reactome.org/content/detail/R-HSA-8857583)
- [R-HSA-168053 Phosphorylated MAPKs phosphorylate ATF-2](https://reactome.org/content/detail/R-HSA-168053)
- [R-HSA-452515 Expression of STAT3](https://reactome.org/content/detail/R-HSA-452515)
- [R-HSA-6803838 FGFR2c-specific alternative splicing produces FGFR2c transcript](https://reactome.org/content/detail/R-HSA-6803838)
- [R-HSA-8853515 OTULIN,USP5 cleaves UBC yielding ubiquitin](https://reactome.org/content/detail/R-HSA-8853515)
- [R-HSA-452958 Expression of SALL1](https://reactome.org/content/detail/R-HSA-452958)
- [R-HSA-8853503 UCHL3,USP7,USP9X cleaves RPS27A yielding ubiquitin](https://reactome.org/content/detail/R-HSA-8853503)
- [R-HSA-480509 Expression of EPHA1](https://reactome.org/content/detail/R-HSA-480509)
- [R-HSA-5617867 HOXB4 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617867)
- [R-HSA-9625520 MSTN gene expression is stimulated by FOXO1 and p-2S-SMAD2/3:SMAD4](https://reactome.org/content/detail/R-HSA-9625520)
- [R-HSA-168915 K63-linked ubiquitination of RIP1 bound to the activated TLR complex](https://reactome.org/content/detail/R-HSA-168915)
- [R-HSA-5617877 HOXA4 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617877)
- [R-HSA-452701 Expression of DPPA4](https://reactome.org/content/detail/R-HSA-452701)
- [R-HSA-6798004 TP53 stimulates BNIP3L expression](https://reactome.org/content/detail/R-HSA-6798004)
- [R-HSA-480520 Expression of SALL4](https://reactome.org/content/detail/R-HSA-480520)
- [R-HSA-8877345 IL2 gene expression is stimulated by RUNX1 and NFATC2 and repressed by FOXP3](https://reactome.org/content/detail/R-HSA-8877345)
- [R-HSA-156913 Regeneration of eEF1A:GTP by eEF1B activity](https://reactome.org/content/detail/R-HSA-156913)
- [R-HSA-3790130 Stimulation of IL6 transcription in senescent cells](https://reactome.org/content/detail/R-HSA-3790130)
- [R-HSA-3928578 EPH receptors autophosphorylate](https://reactome.org/content/detail/R-HSA-3928578)
- [R-HSA-5617874 HOXD4 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617874)
- [R-HSA-3238999 Activated human MKK3/MKK6 phosphorylates p38 MAPK complexed with MAPKAPK5](https://reactome.org/content/detail/R-HSA-3238999)
- [R-HSA-8877922 BGLAP gene expression is stimulated by RUNX2, WWTR1 and RB1 and inhibited by AR, YAP1 and ZNF521](https://reactome.org/content/detail/R-HSA-8877922)
- [R-HSA-5617672 HOXB3 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617672)
- [R-HSA-9625693 TRIM63 gene expression is stimulated by FOXO1 and FOXO3](https://reactome.org/content/detail/R-HSA-9625693)
- [R-HSA-4088305 FOXM1 stimulates PLK1 transcription](https://reactome.org/content/detail/R-HSA-4088305)
- [R-HSA-372505 Acetylcholine synaptic vesicle docking and priming](https://reactome.org/content/detail/R-HSA-372505)
- [R-HSA-8853514 UCHL3,USP7,USP9X cleaves UBA52 yielding ubiquitin](https://reactome.org/content/detail/R-HSA-8853514)
- [R-HSA-9011975 Estrogen-responsive MYC gene expression](https://reactome.org/content/detail/R-HSA-9011975)
- [R-HSA-9622604 BCL2L11 gene expression is stimulated by FOXO1,FOXO3,(FOXO4) and NF-Y](https://reactome.org/content/detail/R-HSA-9622604)
- [R-HSA-5213464 RIPK1 is phosphorylated](https://reactome.org/content/detail/R-HSA-5213464)
- [R-HSA-5690996 ERCC2 and ERCC3 DNA helicases form an open bubble structure in damaged DNA](https://reactome.org/content/detail/R-HSA-5690996)
- [R-HSA-380869 Release of docked dopamine loaded synaptic vesicle](https://reactome.org/content/detail/R-HSA-380869)
- [R-HSA-4088152 FOXM1 stimulates CDC25A transcription](https://reactome.org/content/detail/R-HSA-4088152)
- [R-HSA-210430 release of L-Glutamate at the synapse](https://reactome.org/content/detail/R-HSA-210430)
- [R-HSA-8939870 UCMA gene expression is stimulated by RUNX2 and SP7](https://reactome.org/content/detail/R-HSA-8939870)
- [R-HSA-6785986 DNA nucleases unhook the interstrand crosslink (ICL)](https://reactome.org/content/detail/R-HSA-6785986)
- [R-HSA-1676048 PI(4,5)P2 is phosphorylated to PI(3,4,5)P3 by PIK3C[1] at the plasma membrane](https://reactome.org/content/detail/R-HSA-1676048)
- [R-HSA-5685994 Long-range resection of DNA DSBs by EXO1 or DNA2](https://reactome.org/content/detail/R-HSA-5685994)
- [R-HSA-5617471 HOXA1 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617471)
- [R-HSA-8953556 E2F1 gene transcription is inhibited by E2F6](https://reactome.org/content/detail/R-HSA-8953556)
- [R-HSA-5617454 HOXB1 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617454)
- [R-HSA-1675928 PI4P is phosphorylated to PI(3,4)P2 by PIK3C2A/G at the Golgi membrane](https://reactome.org/content/detail/R-HSA-1675928)
- [R-HSA-5683077 RNF8 and RNF168 ubiquitinate KDM4A,B](https://reactome.org/content/detail/R-HSA-5683077)
- [R-HSA-3209109 E2F1/E2F2/E2F3 and SP1 stimulate transcription of p14-ARF mRNA](https://reactome.org/content/detail/R-HSA-3209109)
- [R-HSA-6806394 TP53 and AP-1 stimulate MSH2 expression](https://reactome.org/content/detail/R-HSA-6806394)
- [R-HSA-452894 Expression of SOX2](https://reactome.org/content/detail/R-HSA-452894)
- [R-HSA-9606163 p-SYK and LYN phosphorylate BTK](https://reactome.org/content/detail/R-HSA-9606163)
- [R-HSA-4088299 FOXM1 stimulates CCNB2 transcription](https://reactome.org/content/detail/R-HSA-4088299)
- [R-HSA-1963586 SRC family kinases phosphorylate ERBB2](https://reactome.org/content/detail/R-HSA-1963586)
- [R-HSA-1676024 PI is phosphorylated to PI3P by PIK3C2A/3 at the late endosome membrane](https://reactome.org/content/detail/R-HSA-1676024)
- [R-HSA-380574 Dopamine synaptic vesicle docking and priming](https://reactome.org/content/detail/R-HSA-380574)
- [R-HSA-6782131 RNA Pol II backtracking in TC-NER](https://reactome.org/content/detail/R-HSA-6782131)
- [R-HSA-452392 Transcription of POU5F1 (OCT4)](https://reactome.org/content/detail/R-HSA-452392)
- [R-HSA-5617486 HOXB2 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617486)
- [R-HSA-480470 Expression of ZIC3](https://reactome.org/content/detail/R-HSA-480470)
- [R-HSA-9615554 MIR137 gene expression is inhibited by MECP2 and SOX2](https://reactome.org/content/detail/R-HSA-9615554)
- [R-HSA-909729 Activation of JAK kinases](https://reactome.org/content/detail/R-HSA-909729)
- [R-HSA-452838 Expression of NANOG](https://reactome.org/content/detail/R-HSA-452838)
- [R-HSA-5690997 Ligation of newly synthesized repair patch to incised DNA in GG-NER](https://reactome.org/content/detail/R-HSA-5690997)
- [R-HSA-5696813 TSEN complex cleaves the intron from pre-tRNA](https://reactome.org/content/detail/R-HSA-5696813)
- [R-HSA-1678920 TLR processing at low pH](https://reactome.org/content/detail/R-HSA-1678920)
- [R-HSA-5227490 NoRC:HDAC:DNMT methylates cytosine of the rRNA genes](https://reactome.org/content/detail/R-HSA-5227490)
- [R-HSA-1675939 PI is phosphorylated to PI3P by PIK3C2A/3 at the early endosome membrane](https://reactome.org/content/detail/R-HSA-1675939)
- [R-HSA-380905 Serotonin loaded synaptic vesicle docking and priming](https://reactome.org/content/detail/R-HSA-380905)
- [R-HSA-452750 Expression of FOXD3](https://reactome.org/content/detail/R-HSA-452750)
- [R-HSA-1168638 Activated IKK phosphorylates I-kappaB](https://reactome.org/content/detail/R-HSA-1168638)
- [R-HSA-168136 Activated JNKs phosphorylate c-JUN](https://reactome.org/content/detail/R-HSA-168136)
- [R-HSA-6798268 TP53 and E2F4 inhibit CDC25C expression](https://reactome.org/content/detail/R-HSA-6798268)
- [R-HSA-3790137 Stimulation of IL8 transcription in senescent cells](https://reactome.org/content/detail/R-HSA-3790137)
- [R-HSA-9033505 PEX1:PEX6:PEX26:ZFAND6:Ub:PEX5S,L:PEX14:PEX13:PEX2:PEX10:PEX12 dissociates yielding cytosolic Ub:PEX5S,L and membrane PEX14:PEX13:PEX2:PEX10:PEX12](https://reactome.org/content/detail/R-HSA-9033505)
- [R-HSA-5682858 RNF8 and RNF168 ubiquitinate H2AFX](https://reactome.org/content/detail/R-HSA-5682858)
- [R-HSA-380901 Release of docked serotonin loaded synaptic vesicle](https://reactome.org/content/detail/R-HSA-380901)
- [R-HSA-9033485 PEX2:PEX10:PEX12 monoubiquitinates PEX5L at cysteine-11](https://reactome.org/content/detail/R-HSA-9033485)
- [R-HSA-5617866 HOXC4 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617866)
- [R-HSA-6803836 FGFR2b-specific alternative splicing produces FGFR2b transcript](https://reactome.org/content/detail/R-HSA-6803836)
- [R-HSA-9012650 JAK2 and LYN phosphorylate STAT5 in EPO:phospho-EPOR:phospho-JAK2:LYN:IRS2](https://reactome.org/content/detail/R-HSA-9012650)
- [R-HSA-9013978 Phosphorylation of IRF-3/IRF7 and their release from the activated TLR3 complex](https://reactome.org/content/detail/R-HSA-9013978)
- [R-HSA-8952232 BCL2L11 (BIM) gene transcription is stimulated by RUNX3](https://reactome.org/content/detail/R-HSA-8952232)
- [R-HSA-4088298 FOXM1 stimulates CCNB1 transcription](https://reactome.org/content/detail/R-HSA-4088298)
- [R-HSA-8848804 HIF1A,EPAS1 promote PTK6 gene expression](https://reactome.org/content/detail/R-HSA-8848804)
- [R-HSA-1675961 PI is phosphorylated to PI3P by PIK3C2A/3 at the Golgi membrane](https://reactome.org/content/detail/R-HSA-1675961)
- [R-HSA-8953946 PEX2:PEX10:PEX12 monoubiquitinates PEX5S,L at cysteine-11](https://reactome.org/content/detail/R-HSA-8953946)
- [R-HSA-5632668 SMO translocates to the cilium](https://reactome.org/content/detail/R-HSA-5632668)
- [R-HSA-72095 Internal Methylation of mRNA](https://reactome.org/content/detail/R-HSA-72095)
- [R-HSA-3215144 TP53 in complex with EP300, PRMT1 and CARM1 stimulates GADD45A transcription](https://reactome.org/content/detail/R-HSA-3215144)
- [R-HSA-372529 Release of acetylcholine at the synapse](https://reactome.org/content/detail/R-HSA-372529)
- [R-HSA-450333 Activated human MKK3/MKK6 phosphorylates p38 MAPK complexed with MAPKAPK2 or MAPKAPK3](https://reactome.org/content/detail/R-HSA-450333)
- [R-HSA-168162 Phosphorylation of human JNKs by activated MKK4/MKK7](https://reactome.org/content/detail/R-HSA-168162)
- [R-HSA-452338 Expression of TDGF1 (CRIPTO)](https://reactome.org/content/detail/R-HSA-452338)
- [R-HSA-5617483 HOXA2 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617483)
- [R-HSA-480515 Expression of FGF2](https://reactome.org/content/detail/R-HSA-480515)
- [R-HSA-5617676 HOXA3 gene is transcribed](https://reactome.org/content/detail/R-HSA-5617676)
- [R-HSA-6782227 Ligation of newly synthesized repair patch to incised DNA in TC-NER](https://reactome.org/content/detail/R-HSA-6782227)
- [R-HSA-6785361 Monoubiquitination of FANCD2:FANCI](https://reactome.org/content/detail/R-HSA-6785361)
- [R-HSA-5655965 POLK and POLZ cooperate in elongation of mispaired primer termini](https://reactome.org/content/detail/R-HSA-5655965)
- [R-HSA-166245 Phosphorylation of IRF-3/IRF7 and their release from the activated TLR complex](https://reactome.org/content/detail/R-HSA-166245)
- [R-HSA-1676109 PI4P is phosphorylated to PI(3,4)P2 by PI3K3C[2] at the plasma membrane](https://reactome.org/content/detail/R-HSA-1676109)
- [R-HSA-5687464 MRN and RBBP8 resect DNA DSBs in MMEJ](https://reactome.org/content/detail/R-HSA-5687464)
- [R-HSA-5213466 RIPK3 is phosphorylated](https://reactome.org/content/detail/R-HSA-5213466)
- [R-HSA-416588 Activation of Rho by LARG and PDZ-RhoGEF](https://reactome.org/content/detail/R-HSA-416588)
- [R-HSA-9013567 HES1 gene expression is stimulated by NOTCH3 and STAT1](https://reactome.org/content/detail/R-HSA-9013567)
- [R-HSA-202248 Phosphorylation of PLC-gamma1](https://reactome.org/content/detail/R-HSA-202248)
- [R-HSA-8853529 OTULIN,USP5 cleaves UBB yielding ubiquitin](https://reactome.org/content/detail/R-HSA-8853529)
- [R-HSA-9033499 PEX1:PEX6:PEX26:ZFAND6 dissociates Ub:PEX5L and PEX7 from PEX14:PEX13:PEX2:PEX10:PEX12 and translocates PEX5L and PEX7 from the peroxisomal membrane to the cytosol](https://reactome.org/content/detail/R-HSA-9033499)
- [R-HSA-9014342 K63-linked ubiquitination of RIP1 bound to the activated TLR complex](https://reactome.org/content/detail/R-HSA-9014342)

**Comment by ukemi** [comment]
Looks like we will have plenty to do next week. If you don't get around to these, we can look together.

> If Ben could provide the list of 204 control events with more than one active unit annotated, I will take a look to see if this initial reaction is right and if so, work with Reactome people to come up with a plan for changed annotation practice henceforth and cleanup of the legacy instances. My hunch is that clean-up of the annotations could probably be automated, but all the new reactions that will appear will need to be laid out manually in pathway diagrams and this part will be painful.

The difficulty in annotating a reaction here is that choosing which one comes first might not be known or even consistent. That's why I would invoke a process with two kinase activities as parts. Not that I stubbornly argue a point.  :)

**Comment by ukemi** [comment]
> I get the point that if the chemical citrate is the product of reaction 1, and that citrate molecule regulates reaction 2, the Reactome assertion that citrate regulates reaction 2 maps cleanly and reliably onto the assertion that reaction 1 regulates reaction 2. 

But our view since the beginning has been that it is not the citrate regulating reaction 2, but that the citrate is taking part in something that is happening that regulates reaction 2. That's why we have processe 'regulation of x'. Since we are gene-centric, we express the something that is happening in the context of what genes are doing. So the PFK **binding** the citrate is what is regulating the kinase activity. I think this also cleans up the mass action difficulties. If PFK binds citrate, it negatively regulates the kinase activity.

**Comment by ukemi** [comment]
PS. It makes total sense from a reaction point of view that the citrate (product of some reaction) is able to negatively regulate some downstream reaction.

**Comment by ukemi** [comment]
> @deustp01 sorry again, it was 108 multi-active-unit reactions. Got fooled as some of them appear in multiple pathways. That probably inflated some of the other counts above. Here is the list of reactions:

OK. Some of these are definitely processes from a GO perspective.

**Comment by ukemi** [comment]
@goodb. What about splitting out the regulatory processes into a separate model, but referring to the same Reactome pathway. Would that give us the best of both worlds? It would get rid of the clutter that you find undesirable and would give me the explicit process-based representation.

**Comment by goodb** [comment]
I'd really prefer to keep a 1 to 1 relationship between Reactome pathways and GO-CAM model.  

@ukemi I find the clutter and layout mess annoying from a UI perspective, but that is a separate issue from the modeling.  We should not let weaknesses in the UI translate into weaknesses or hacks in the data model.  The UI can be fixed once the structures in the model are stable.  (Worst case is that I spend a week and hack together a new layout algorithm that is aware of the recent changes.  Best case is that we get a client UI developer involved that has more power to control the system and can do more expand/contract operations on the graph entities...)

**Comment by goodb** [comment]
After further pondering, I am slowly coming around to what you are referring to as the process-based representation for this case.  The key for me is that it matches up better with the structure of everything else happening in the GO-CAM kb and this is really important for query.  

As an aside, the structures that are being established here should be stored somewhere as templates for curators once they are agreed upon...

**Comment by deustp01** [comment]
> The difficulty in annotating a reaction (or two) here is that choosing which one comes first might not be known or even consistent. That's why I would invoke a process with two kinase activities as parts. Not that I stubbornly argue a point. :)

I think that splitting a reaction in two, to get two reactions each with a single active unit, with generate a bifurcation and merger like the generation of two triose phosphates. So putting them together into a process wouldn't help, I suspect.

**Comment by deustp01** [comment]
"Since we are gene-centric, we express the something that is happening in the context of what genes are doing. So the PFK **binding** the citrate is what is regulating the kinase activity."

OK. We will need to look at a sample of regulation instances to be sure that we can translate Reactome's "entity X regulates an activity" into GO-CAM "entity X interacts with the enabler of the activity and that regulates the activity". Note the swapping of "binds" for "interacts": sometimes we do know that the interaction takes the form of binding, but we probably can't guarantee this. Indeed, there are likely to be at least some cases where the data say that an activity increases or decreases when an entity is present (so "entity regulates activity" is valid) but we have no data as to mechanism (so "binds" goes beyond the data).

**Comment by deustp01** [comment]
"split out regulation" etc.

I think the way we were going last week and also here, we aren't really doing this. We are more nearly looking for ways of collapsing the whole Reactome annotation of a regulatory process that affects glycolysis or BMP signaling into a simple assertion that X entity regulates Y activity in the process being converted into GO-CAM. If there's a lot of Reactome annotations hidden inside that simple assertion, that's lost for now and can be brought back in a future UI that enables navigation between GO-CAM models. Our goal now is to make GO-CAMs that are good templates for future GO curation, so suppression of some human-specific, possibly out-of-scope annotations seems OK, especially as the surviving regulation stubs can be used in the future to reassemble the lost pieces.

**Comment by ukemi** [comment]
If we can't invoke binding, then I think we should explore your idea above. We could invoke a regulatory process in which the entity is simply a participant. When you curate one of these types of regulatory events, is it always because the entity is somehow involved in regulating the whole pathway?

**Comment by ukemi** [comment]
So maybe Ben's original representation is the best for now, which essentially said entity X is somehow involved in the regulation of MF A. Sorry to be going round and round with this, I thought we could always assert binding in these representations.
