### ISSUE TITLE
Fatty AcylCoA biosynthesis

### ISSUE THREAD

**Issue by deustp01** [geneontology/pathways2GO#315]
Fix Reactome - RHEA charge discrepancies - see "[fatty acyl CoA biosynthesis cleanup R-HSA-75105](https://docs.google.com/document/d/1GkwB54FIJ9XzLqcDEYYQ9-epnOZhrN3DmwW7i0Cct7w/edit)" in the David_and_Peter_notes folder for reaction-by-reaction details

**Comment by deustp01** [comment]
Fixes are done, as logged "[fatty acyl CoA biosynthesis cleanup R-HSA-75105](https://docs.google.com/document/d/1GkwB54FIJ9XzLqcDEYYQ9-epnOZhrN3DmwW7i0Cct7w/edit)"

@ukemi could you review?

**Comment by ukemi** [comment]
Yep. Will start tomorrow morning.

**Comment by ukemi** [comment]
I checked all the participants and the GO MF xrefs. Comments are in line on your document.

**Comment by deustp01** [comment]
Review finished. Some tangential issues notes in Google document, but this ticket can be closed.
