### ISSUE TITLE
Make protein sets OWL Union entities in GO-CAMs

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#32]
Reactome represents group entities like '[glucokinase and hexokinases](https://reactome.org/PathwayBrowser/#/R-HSA-70326&SEL=R-HSA-450097&PATH=R-HSA-1430728,R-HSA-71387)'.  So far these have been treated as complexes in the GO-CAM converter which is incorrect.  

To close issue:

- [ ] in the GO-CAM, create an OWL union class containing each member to represent the group 
- [ ] add any relations previously linked to the complex representation to the union entity
- [ ] confirm that this renders in Noctua, if not, generate a new Noctua ticket

**Comment by goodb** [comment]
(note from Geneva meeting:

See pyruvate kinase tetramer - it is a set of complexes.  Make a union of the complexes as the controller entity.  In reaction phosphoenolpyruvate + ADP => pyruvate + ATP from glycolysis.  Complexes need to maintain has_part relations to proteins.  
Tabular annotations from this one should look like: 
Gene_product enables  MF )
See also 'part_of o enables -> contributes_to' https://github.com/geneontology/minerva/issues/110

**Comment by goodb** [comment]
See 'p-S189,T193-MAP2K3, p-S207,T211-MAP2K6 ' in the reaction: 'Phosphorylated MKK3/MKK6 migrates to nucleus' in the pathway 'activated TAK1 mediates p38 MAPK activation' for another example of a protein set (that is not a complex).

**Comment by goodb** [comment]
This is working according to issue description (hence closed it), but no one has confirmed they like the output.  Ping @ukemi @thomaspd @cmungall See e.g. http://noctua-dev.berkeleybop.org/editor/graph/gomodel:284362402 and look for 'union'

**Comment by vanaukenk** [comment]
@bgood 
From 2019-03-01 discussions at NYU: given that the sets identify the gene products or complexes that are individually capable of performing the reaction, we can't think of a better way to represent this.
Still to do: make sure that the resulting annotations (in GPAD) are correct.
Note that the above model is currently failing reasoning due to logical inconsistency.

**Comment by deustp01** [comment]
Sets are supposed to be ordered lists. Here is an edge case. Reaction R-HSA-73548 "(d)CMP or UMP + ATP <=> (d)CDP or UDP + ADP (CMPK1)" has as input the set [dCMP, CMP, UMP], and as output the set [dCDP, CDP, UDP]. The intended meaning is that dCMP can be converted to dCDP, or CMP can be converted to CDP, or UMP can be converted to UDP. The first item on the input list becomes the first item on the output list, and so forth.

Further, this reaction is catalyzed by a set of two enzymes, which is intended to mean that each of the two enzymes is capable of catalyzing each of the three reactions listed above.

**Comment by goodb** [comment]
@vanaukenk apologies for reasoning problems in noctua-dev.  I have a request in to fix them.  (Not the fault of the models.)  If there is a specific question I can answer, I can run tests in my local environment.  I can tell you right now though that the gpad output is not going to contain genes from within the union or intersection constructs as it stands.  The export code will need to be adapted to look in there.  How would you want the output to look like - for sets/complexes ?

@deustp01 any ordering of members within sets such as these is lost in the BioPAX translation.  Though more verbose, I think it would be more useful computationally to break shorthand reaction definitions apart into the different reactions that represent.  Of course that is a Reactome decision to make.
