### ISSUE TITLE
Weirdness in NADPH regeneration (R-HSA-389542) import

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#331]
If I look at the import of this model:
http://noctua.geneontology.org/editor/graph/gomodel:R-HSA-389542?
And the pathway in Reactome:
https://reactome.org/PathwayBrowser/#/R-HSA-8978934&SEL=R-HSA-389542&PATH=R-HSA-1430728,R-HSA-196854

I see an oddity.  Reaction R-HSA-5690911 is in the pathway, but is missing from the model.

**Comment by ukemi** [comment]
Mouse models:
http://noctua.geneontology.org/editor/graph/gomodel:67369e7600004463?
http://noctua.geneontology.org/editor/graph/gomodel:67369e7600004490?

**Comment by ukemi** [comment]
When to include a pathway and when not to include a pathway. According to PMID:21527585, IDH1 activity is a major source of NADPH in human tissues, but contributed relatively poorly in mouse. In mouse the pentose phosphate pathway seems to be a major contributor. Should we include 'minor' players as pathways in GO-CAM models for MODs or would that be misleading? @deustp01 @sjm41 @vanaukenk  what do you think about this? Would you go ahead and make the mouse pathway? This is not the first time I have run into this, but it is the most extreme case. Since we can't quantify how much a pathway contributes to overall metabolic flux, it might be that sometimes pathways are misleading even though they are possible.

**Comment by deustp01** [comment]
This one can be argued several ways. First, pathway descriptions, both process description and activity flow, are qualitative - events happen or not; we don't have good tools for consistently annotating amount of activity. That would suggest we set a minimum threshold, and if the best available data suggest it's not met, we don't annotate that possible event sequence as part of the pathway. Second, however, while we can capture tissue specificity we often don't, and we never capture physiological state except indirectly by annotating regulatory processes that are in fact state specific (e.g., effects of regulatory signals from insulin and glucagon on glycolysis and gluconeogenesis). Continuing on the gluconeogenesis example, the major source of the carbon skeletons varies substantially according to whether the individual mammal has been fasting for a short or a long period or alternatively is acidotic. (Hence the tangle of events at the start of [gluconeogenesis ](https://reactome.org/PathwayBrowser/#/R-HSA-70326&SEL=R-HSA-70263&PATH=R-HSA-1430728,R-HSA-71387) where we capture all of these alternative ways of getting to PEP / phosphoenolpyruvate)

<img width="1021" alt="Screenshot 2024-12-09 at 9 28 10 AM" src="https://github.com/user-attachments/assets/306fb540-02cb-4bf1-8a3b-013a92ad53c3">

**Comment by ukemi** [comment]
That's a really good point @deustp01. I am very tempted to include these pathways as well. Especially since according to the measurements in this paper, in some tissues the contribution is greater than in others. But again, as you say, even with tissue specificity it's hard to decide on a cut off. I think it's ok to include them, especially since I also made links from the 'major' enzymes to the process in the pentose phosphate shunt. I'd rather include the potential complexities of the biology than omit them. If they are omitted then we will never see them.

**Comment by ukemi** [comment]
It's interesting that mouse might not be a good model specifically in glioma because of the low contribution in the CNS, but it might be ok for other aspects of physiology.

**Comment by deustp01** [comment]
And NAD(P) turnover is a classic textbook edge case. Glycolysis generates NADH and, if not coupled to another process that consumes it and regenerates NAD+, glycolysis stalls. Hence in mammals the fermentation to lactate in red blood cells and exercising muscle, which then travels to the liver to enter either the TCA cycle or gluconeogenesis. And clinically, ethanol can only be metabolized by two steps of oxidation, to acetaldehyde and then acetate, costing two NAD+ per ethanol molecule, depleting the supply of NAD+ for the rest of metabolism.

**Comment by dustine32** [comment]
@ukemi This rxn could be missing in the prod Noctua model because those models are really old, still on Reactome release 85 whereas Noctua-dev is on release 90. I currently see this rxn on the noctua-dev [model](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-389542?). Perhaps the reaction was added in Reactome between these releases?

We should probably schedule an update of Noctua prod to the latest release soon after we sort through what issue code changes should be merged before generating the models.

**Comment by ukemi** [comment]
Yes. One thin g I would like to do on one of the weeds calls is see where we stand with respect to tickets and try to get an updated load done.
