### ISSUE TITLE
Provides input for OR positive regulates

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#36]
Currently, the converter code maps each 'nextStep' relation asserted in the input BioPAX to a 'provides_direct_input_for' relation between the reactions/MFs.  nextStep is overly generic for that specific of a mapping.  For example, when the relationship is more of a signaling relation than a metabolic relation, then directly_positively_regulates in a more appropriate relation.  

- [x] convert nextStep relations from BioPAX into RO 'Causally Upstream Of'.  
- [x] Add a new rule:  If reaction1 **has_output** E and reaction2 **has_input** E and reaction1 nextStep reaction2 then reaction1 **provides_direct_input_for** reaction2
- [x] Add another new rule: If reaction1 **has_output** E and reaction2 **enabled_by** E and reaction1 nextStep reaction2 then reaction1 **directly_positively_regulates** reaction2

**Comment by goodb** [comment]
@ukemi I'm looking at 'activated TAK1 mediates p38 MAPK activation  https://reactome.org/PathwayBrowser/#/R-HSA-450294&SEL=R-HSA-450302&PATH=R-HSA-168256,R-HSA-168249,R-HSA-168898,R-HSA-168164 as a test case for this one.  The first cut only puts one regulates relation in between 'Phosphorylated MKK3/MKK6 migrates to nucleus' and 'Activated human MKK3/MKK6 phosphorylates p38 MAPK complexed with MAPKAPK2 or MAPKAPK3'.  Which reactions in this pathway should be linked by positive regulates (and which by provides input for) ?  Just want to set up a test.

**Comment by ukemi** [comment]
There is already a test case in the canonical glycolysis pathway. I'm seeing individuals that are given parents to both the terms and to the regulation terms. Peter and I are focusing on glycolysis as the test case. @huaiyumi  is looking at the MAPK pathway.

**Comment by goodb** [comment]
Okay fair enough @ukemi .

**Comment by goodb** [comment]
@balhoff if you look at the text of the issue linked here, I'm wondering if the rules for deepening the specificity of the relations in question should fall out of property chains in the RO rather than custom rules.  It looks like there is already one in place that would cover the 'directly provides input for' case but it uses an obsolete relation:  'obsolete has direct output' o 'has direct input'  ?

**Comment by ukemi** [comment]
How specific is this to Reactome's representation? I think that would be the deciding factor.

**Comment by goodb** [comment]
For the moment I went ahead and added the rules locally.  Even if/when the property chains exist, Noctua users don't really have a good way of seeing their results and I think that is important at this stage.

**Comment by balhoff** [comment]
> @balhoff if you look at the text of the issue linked here, I'm wondering if the rules for deepening the specificity of the relations in question should fall out of property chains in the RO rather than custom rules.

@goodb I think that would be good but I'm not sure where to look. It sounds like this is resolved for the time being though.
