### ISSUE TITLE
each edge in a reactome model should have one identical evidence statement linking it to the source pathway

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#37]
Each edge in the GO-CAM should be linked to an evidence statement with the source being the reactome unique identifier for the corresponding pathway record.  e.g. reactome:R-HSA-450302 
(Noctua ought to expand that the way it does for PMIDs to e.g. https://reactome.org/content/detail/R-HSA-450302 ).

**Comment by goodb** [comment]
This is important for producing gpad - see 'annotation preview' or gpad export in noctua.  Currently nothing comes up for reactome models - a common source is needed.

**Comment by goodb** [comment]
@ukemi @deustp01 @vanaukenk The conversion code currently digs pubmed references out of xrefs on the Reactome entities (pathways, reactions, controllers).  These are applied a little haphazardly as they are attached to entities in Reactome and they need to be moved onto relations in go-cam.  You can see examples on the BP has_part MF relations for most models.  

Should these pubmed references be taken out?  In a sense they are redundant with the reactome source reference that I am adding in now which itself includes them.

**Comment by deustp01** [comment]
"redundant" as in you already cite the R-HSA-###### identifier of the relevant event as a reference, so a user can follow that ID to the Reactome page that has all the literature references with PMIDs?
If that's what you mean, then yes, exactly, adding the PMIDs to the GO-CAM is redundant and also haphazard because each PMID almost certainly contributes only a part of the total evidence that supports the GO-CAM model and, as discussed fully already, there is no way to figure out computationally which PMID supports which part.

**Comment by goodb** [comment]
Yup that is what I meant.  Okay.  I will drop the pmids.

**Comment by ukemi** [comment]
We need to be sure in our systematic reviews to see how this affects the GPAD output of a model. I suspect that if the reference is removed, no annotation will be generated. If we want annotations from these, we will need to find something to add. @goodb when you tweak your code, does it generate a new model or overwrite an old one? I have created template documents for some of the models that we will review and added them to the folder @huaiyumi created.  

Note we should all start watching this repository so no one gets left out of a conversation.

**Comment by ukemi** [comment]
I see that @goodb already pointed out the GPAD issue above. @vanaukenk do you know what reference is currently cited for Reactome-based annotations in GO?

**Comment by goodb** [comment]
This ticket was generated because the current approach doesn't generate any GPAD.  When this is finished, the GPAD should come out fine because all of the relations will have the same reference to the reactome:R-HSA-###### identifier.

**Comment by goodb** [comment]
Pathways are overwritten in noctua-dev when updates are made.  I suggest manually crafted example pathways go into the main noctua as it is more stable (you can still tag them as dev).

**Comment by ukemi** [comment]
I just checked, it is the URL that is the ref. So theorhetically if all of this works, we should be able to regenerate the Reactome annotation file from the models. That's something we should check. Maybe the annotations will improve. Who knows?

**Comment by goodb** [comment]
I will try to keep them stable, but until things are moved out of
noctua-dev and onto noctua I can't guarantee it.
