### ISSUE TITLE
add startsWith and endsWith to models

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#42]
This will make it possible to automate type inference and checking with OWL definitions for biological processes like 'GO:0007213' 'G protein-coupled acetylcholine receptor signaling pathway'.  Defined as:
'signal transduction'
 and ('starts with' some 'G protein-coupled acetylcholine receptor activity')

**Comment by goodb** [comment]
The plan right now is to use the ordering provided by Reactome via the BioPax nextEvent structure.  The code will look at the graph and seek out linear structures.  Loops will not have starts and ends.  Islands can't be starts and ends.  

A node will be called a start if no causal relations flow into it and at least one flows out of it.
A node will be called an end if at least one causal relations flow into it and no relations flow out of it.  

@cmungall : this formulation makes it possible for a process to have multiple starting and ending functions.  Is that okay?  We could be more cautious, and not assign start/end when there are multiple if this is a problem.  It seems reasonable however that a process could have multiple initiators as well as multiple endpoints.

**Comment by cmungall** [comment]
That looks like a very closed world definition.

A process should have 1 start and 1 end, and these should be consistent with starts and ends defined in the ontology

**Comment by goodb** [comment]
Looking at BMP Signaling I don't think this is likely to work very well in general.  The algorithm applied to that pathway generates three starting points:
- I-Smad competes with R-Smad1/5/8 for type I receptor
- The ligand trap binds the ligand BMP2, blocking BMP signalling
- Formation of a heteromeric BMP receptor complex

Probably only one "Formation of a heteromeric BMP receptor complex" is close to the right intent.  Similar problems for termination.  

We could work harder on a set of rules to isolate simple pathways that follow a linear structure and have singular starts and ends.  But, not really sure its worth it.  Right now it looks to me like this might be one thing we need to kick back to @deustp01 and Reactome curators.  Perhaps they can annotate specific pathway initiators and terminators directly.  But.. the general model of having a process only have 1 start and 1 end does not seem to jive with how pathways are represented.  Perhaps it is not a useful construct for these kinds of models.
