### ISSUE TITLE
🐛 in conversion of bmp related to regulation rule

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#49]
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:1847456024

<img width="838" alt="screen shot 2019-02-13 at 11 34 43 am" src="https://user-images.githubusercontent.com/2086122/52738425-7e6ffb00-2f83-11e9-8373-7d706a89b147.png">

**Comment by goodb** [comment]
should be positively regulates

**Comment by goodb** [comment]
Looks like part of the issue comes up because BMP:BMPR is listed as both an input to 'Type II receptor phosphorylates type I receptor' and its catalyst.

**Comment by goodb** [comment]
Other part is that splitting up the active unit on the complex confused the rule.

**Comment by goodb** [comment]
Fixed.  but note:
1. Currently this is the only inferred positively regulates relationship for the bmp signaling pathway (according to the rule that if R1's output enables R2 then R1 positively regulates R2).  
2. Since the complex in question here is listed by Reactome as both a catalyst and an input to R2, both positively regulates and provides direct input for relations are asserted.  

![screen shot 2019-02-14 at 10 02 23 am](https://user-images.githubusercontent.com/2086122/52807314-f4399c80-303f-11e9-86c7-77e381213f0a.png)

**Comment by ukemi** [comment]
We are going to have to think about this double-edge.

**Comment by deustp01** [comment]
The biology we want to capture is complicated. First, a physical entity does something that activates it. e.g. a receptor binds a ligand. Then that activated entity carries out a function that results in a chemical change to itself, e.g. the activated receptor - ligand complex catalyzes its own phosphorylation. And typically the physical entities in these events are complexes and different components of the complex have different functions, e.g., ligand-binding and kinase-activity. But indeed the ligand-receptor complex both enables the kinase function and is the input for the kinase reaction, and that double role is a key feature of the biological process. If it helps, it is probably OK to assert that the receptor protein is the enabler and the kinase - the ligand molecule doesn't have a direct role in either.

Per the BMP discussion, I guess the ligand-binding step would be modeled in GO-CAM as positive regulation of the phosphorylation (kinase) step.

**Comment by deustp01** [comment]
The GO-CAM import from Reactome of IRE1-mediated branch of the ER Unfolded Protein Response http://noctua-dev.berkeleybop.org/editor/graph/gomodel:1254400507 has an example of this.

**Comment by vanaukenk** [comment]
@goodb 

From 2019-03-01 discussion at NYU:
Each of the two relations between the reactions shown in the BMP and IRE1 models is actually correct, and therefore, we think we should keep them both.
