### ISSUE TITLE
Open Questions Feb 2019

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#53]
Here is a consolidated list of unresolved questions in need of finalization from biodata owners

1. When Reactome asserts that an entity regulates a reaction (not including catalysis), how should this be represented in GO-CAM?  See: https://github.com/geneontology/pathways2GO/issues/31#issuecomment-465056160 and https://github.com/geneontology/pathways2GO/issues/39#issuecomment-464167940 
2. How should Reactome "Sets" be represented in GO-CAMs?  The current formulation is to create OWL Union[1] constructs for sets.  See https://github.com/geneontology/pathways2GO/issues/32 .  
3. Following from 2., how should complexes be represented?  For complexes, the current formulation is to use an OWL Intersection[1] statement.  See https://github.com/geneontology/pathways2GO/issues/34#issuecomment-456529351 
4. Can a reaction both 'directly provide input for' and 'positively regulate' another reaction?  See https://github.com/geneontology/pathways2GO/issues/49#issuecomment-463730529 
5. When Reactome annotates different locations for the components of a reaction, how should this be represented in GO-CAM?  Currently all entity locations are collapsed into reaction occurs_in statements.  See https://github.com/geneontology/pathways2GO/issues/51  
6. An unresolved question arose at the feb. 27 meeting with respect to the stoichiometry of complexes.  Right now, complexes are reduced to a non-redundant set of proteins.  So a dimer like IRE1 * 2 just looks like a single IRE1 protein in the GO-CAM model.  This loses some information that could be captured.  Do we still want to keep the models this way or should we try to catch this information?

[1] Note that the use of OWL constructs is valid in the OWL sense, does not break Noctua, and seems logically sound.  However, Noctua users can not currently create these constructs within the editor, it is difficult to see the protein members of the constructs, and they probably do not make it out of the current GPAD output.  The alternative prior representation of Complex has_part protein also has display problems (folding does not work) and is ambiguous with respect to the difference between a Set (logical union) and a complex (logical intersection).  IMO these constructs are the way forward because they are unambiguous and we should grow the Noctua stack to better support them.  But this needs a decision and a resource commitment to happen.  (Also need to make sure that these representations mesh with any potential logical definitions for complexes with the GO CC.)

**Comment by goodb** [comment]
Not sure why I can never find @deustp01 in github person search - e.g. to assign him a question.

**Comment by cmungall** [comment]
probably needs to be added to repo..

**Comment by vanaukenk** [comment]
6\. An unresolved question arose at the feb. 27 meeting with respect to the stoichiometry of complexes.  Right now, complexes are reduced to a non-redundant set of proteins.  So a dimer like IRE1 * 2 just looks like a single IRE1 protein in the GO-CAM model.  This loses some information that could be captured.  Do we still want to keep the models this way or should we try to catch this information?

From related discussions on #49 , we think that it is not necessary to capture more than one instance of an entity for homooligomerization reactions.  That would be consistent with GO's decision not to try to represent stoichometry in the GO-CAM models.

**Comment by vanaukenk** [comment]
An example of a regulation representation for question one is here:

http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00001531

**Comment by goodb** [comment]
@vanaukenk can you point me to the specific reaction modeled there with the negative regulation ?

**Comment by vanaukenk** [comment]
R-HSA-71670  and R-HSA-70467

**Comment by goodb** [comment]
Consolidating answers:
> 
* When Reactome asserts that an entity regulates a reaction (not including catalysis), how should this be represented in GO-CAM?  See: [#31 (comment)](https://github.com/geneontology/pathways2GO/issues/31#issuecomment-465056160) and [#39 (comment)](https://github.com/geneontology/pathways2GO/issues/39#issuecomment-464167940)
  * Construction of a +-regulation process node, linked to entities via has_participant.  See 
http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00001531
* How should Reactome "Sets" be represented in GO-CAMs?  The current formulation is to create OWL Union[1] constructs for sets.  See #32 .
  * Confirmed.  Will continue to use the OWL Union construct.  It is not a high priority (or perhaps even desirable) to let GO curators create these.  
* Following from 2., how should complexes be represented?  For complexes, the current formulation is to use an OWL Intersection[1] statement.  See [#34 (comment)](https://github.com/geneontology/pathways2GO/issues/34#issuecomment-456529351)
  * Complexes will be represented with their members linked via has_part relations (as in the original formulation).  We will not use the Intersection construct - leaving it implicit here has it is everywhere else.
* Can a reaction both 'directly provide input for' and 'positively regulate' another reaction?  See [#49 (comment)](https://github.com/geneontology/pathways2GO/issues/49#issuecomment-463730529)
  * Yes, we will allow both.  
* When Reactome annotates different locations for the components of a reaction, how should this be represented in GO-CAM?  Currently all entity locations are collapsed into reaction occurs_in statements.  See #51
  * For transport reactions, we seem to be missing a location annotation on the reaction itself.  When this is present, the reaction node will 'result in transport across' the annotated location for the reaction.  The entities being transported will be assigned has_target_end/start location assertions.  If the entity is a protein, the reaction will be classified as 'protein transport', else if the entity is a complex, the reaction will be classified as 'transport'.
  * For non-transport reactions, we will only have access to location information on the physical entities.  Unless transport can be inferred based on having the same input and outputs in different locations, the reaction will be annotated as 'occurs_in' all of the locations of all of the physical entities involved.  Multi-occurs_in statements may be fed back to Reactome for curation consideration but will be allowed in the converted models.  
* An unresolved question arose at the feb. 27 meeting with respect to the stoichiometry of complexes.  Right now, complexes are reduced to a non-redundant set of proteins.  So a dimer like IRE1 * 2 just looks like a single IRE1 protein in the GO-CAM model.  This loses some information that could be captured.  Do we still want to keep the models this way or should we try to catch this information?
  * The conclusion is to keep the code as is, let it collapse dimers etc. into the minimal protein set.  Do not attempt to capture any stoichiometry.

**Comment by goodb** [comment]
Action items:
- [ ] **entity regulates a reaction**. convert model from https://github.com/geneontology/pathways2GO/issues/39#issuecomment-464167940 to http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00001531 
- [ ] update **rules for detecting transport** to include complexes - switch from localization to transport terms per https://github.com/geneontology/pathways2GO/issues/55  
- [ ] **convert complexes** from intersections to collections of has_part relations.  (= give up on looking at these models in Noctua or somehow solve that problem)

**Comment by goodb** [comment]
Think all of the issues are addressed as requested.  Closing now and working on full rebuild for noctua-dev for testing.
