### ISSUE TITLE
complex transport

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#55]
The reaction [phospho-R-Smad1/5/8:Co-Smad transfers to the nucleus](https://reactome.org/PathwayBrowser/#/R-HSA-201451&SEL=R-HSA-201472&PATH=R-HSA-162582,R-HSA-9006936)   brings up 2 questions:

1. The reaction itself seems to be annotated with a location: nuclear envelope GO:0005635 .  I don't see this information in the BioPAX and this is inconsistent with my understanding that Reactome only attaches localization information to physical entities. Should this be in the BioPAX ?  
2. Right now, we have a rule that translates the movement of individual proteins into instances of the biological process 'establishment of protein localization'.  This rule does not apply to complexes hence these reactions are usually classified as generic molecular functions.  Should we add a rule to map complex transport to a GO BP term - e.g. even the term 'transport' or 'localization' would be more descriptive than what we have and could potentially enable some inferences.

**Comment by ukemi** [comment]
We can't see any reason why this rule shouldn't apply to complexes. We assume that the the process itself has no functions or enablers associated with it.

**Comment by deustp01** [comment]
Issue 1. Reactome annotation convention is that when a physical entity is relocated from one side of a membrane to the other, the relocation reaction is located in the membrane. The rationale is that that is where the transporter, known or not, is located. I need to check with Lisa Matthews to confirm this curation usage (and how we enforce compliance), and with Guanming to find out how this information is represented in the BioPax export.

**Comment by goodb** [comment]
@ukemi what BP term should be used when the entity moving is a complex ?

**Comment by ukemi** [comment]
Issue#2: Would it make more sense to map it to 'protein transport' ? For the SMAD example since the reaction occurs in the nuclear envelope you could say transport and 'results in transport across' some 'nuclear envelope'. This is consistent with the way these are expressed in the ontology. For complexes we could just say that it is transport. It's a little unsatisfying in that there may not be an active transport, but we think this works.

**Comment by deustp01** [comment]
BioPax from Guanming - there is basically no compartment attribute (called cellularLocation) defined for BiochemicalReaction class in BioPAX. I guess this is smart move actually since in theory the cellularLocation of a reaction should be able to inferred from its participants based on some rules. For example, in that case at least three compartments should be really included: cytosol, nuclear envelope, and nucleoplasm. I doubt if there is a need for us to really specific an exact location where the reaction occurs, which most likely should be defined by the actual kinetic mechanism.

Which gets to the second overlapping issue, comprehensive and consistent annotation of locations of the physical entities involved in a reaction. This part is a work in progress.

**Comment by ukemi** [comment]
So if we want to capture where the reaction takes place, we will need to elucidate it in some way from where the reactants and products are located. I think this will be possible once we have the spatial relations for cellular components in GO. But for now, an easy inference is if they are in the same place, the reaction is occurring there. 

If the entity is a complex, I think we decided that the BP 'transport' should be used. Then we can use extensions to indicate the complex with the appropriate has_part relationships to the complex and the gene products.

**Comment by deustp01** [comment]
... And if they are in different places there should either be an entity with transport properties involved in the reaction or it's a potential curation mistake that should be flagged for review at Reactome.

**Comment by goodb** [comment]
@deustp01 is this another case where the knowledge in Reactome is simply richer than the BioPAX model as was the case with the active unit annotations?  If Reactome specifically annotates a location for a reaction, then it seems important enough to come through in one way or another in an export.  Alternately, if, as you seem to suggest above, it would be better to stay with the strict BioPAX model of only asserting locations for physical entities, then shouldn't Reactome itself do so and eliminate these location assertions on Reactions?

**Comment by deustp01** [comment]
@goodb you're getting at the curation "work in progress" from my comment late Friday, above. This is a euphemism covering the fact over the time we've been in business there have been various views about where a reaction is "located" when its participants have multiple locations (taking each GO_ cell_component term used to locate a physical entity as a separate location). Should we try to come up with some sort of center of mass location, or apply some sort of biological rule to identify the "key" compartment in the list analogous to distinguishing "primary inputs" of a process from all the others?

What happens in the GO-CAM conversion if you say that the location of a reaction is the sum of the locations of its participants?

You can actually ignore the instance that set this off, where a cytosolic input becomes a nuclear output with no annotated involvement of anything in the nuclear envelope, that we localized to the nuclear envelope. This is an example of a well-defined (in my mind at least) group of shorthand annotations where we have deliberately omitted steps and we will either be able to fix then in bulk or come up with a rule to identify and skip them.

**Comment by goodb** [comment]
> What happens in the GO-CAM conversion if you say that the location of a reaction is the sum of the locations of its participants?

The function in the GO-CAM will 'occur_in' multiple different locations.  This makes @ukemi and @cmungall (minimally) uncomfortable with respect to the semantics of the occurs_in relationship.  But, as it stands, nothing in the system breaks when they are there.  This is the pattern that is in place now.

**Comment by ukemi** [comment]
I'm wondering if we can't do something more clever than have them in two locations and then feed that back to Reactome as part of the data exchange. For example is there a way we can infer cytosolic side of membrane from locations in the cytosol and membrane?
