### ISSUE TITLE
Implement rules for non-protein entities regulating molecular functions

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#56]
When Reactome states that a protein, complex, set or small molecule regulates a reaction,

Create a generic MF node that is enabled by the entity.
Make the MF node a part of regulates_biological function node.
Make the regulates biological function node regulate the reaction.  
Make the regulates biological function node a part of a generic biological process.
Make the generic biological process regulate the pathway.

**Comment by ukemi** [comment]
Hi Ben. There has been a bit of back-peddling on the small molecule. I would still go with my initial vote on a regulatory process that has a participant of the small molecule. If it is a protein or a complex, it enables a function that is part of the regulatory process.

**Comment by goodb** [comment]
This is what it looks like now.  Lets decide how to change this today...  

![Screen Shot 2019-03-20 at 11 04 37 AM](https://user-images.githubusercontent.com/2086122/54708207-225b4200-4b00-11e9-9166-bd55a1a0846d.png)

My personal vote for what its worth.. :

molecule involved_in_regulation_of molecular_function

**Comment by goodb** [comment]
The conclusion for today is to roll back to the representation based on the assumption that the molecules execute their regulatory function by binding something.  See [picture and original thread where this was discussed](https://github.com/geneontology/pathways2GO/issues/39#issuecomment-464167940).  

To summarize the rule.  When Reactome indicates a small molecule M +- regulates a reaction R enabled by entity E in pathway P:

1. Generate a node N with RDF:type binding (GO_0005488).  Then add the relations:
2. N enabled by E
3. N has input M
4. N directly +- regulates R 
5. N part of a new generic node gBP with type Biological Process
6. gBP directly +- regulates P

Caveat emptor: the binding assertion is going beyond what Reactome actually knows.  The consensus is that this will be true most of the time and that we should go with this model as it is the closest we can get to the activity flow structure favored by the project leads.  It is possible that Reactome will add this information where it is known to future releases.

**Comment by goodb** [comment]
I think this is done.  @ukemi see below for screenshots of with and without the reasoner.  Give me a thumbs up and I will close the issue and work on a push to dev with this and the occurs_in changes incorporated.  (and will filter the diseases..)  

![Screen Shot 2019-03-22 at 11 28 31 AM](https://user-images.githubusercontent.com/2086122/54845312-48b2e600-4c96-11e9-83b9-7c10b8a0bb7f.png)

![Screen Shot 2019-03-22 at 11 30 45 AM](https://user-images.githubusercontent.com/2086122/54845332-50728a80-4c96-11e9-9ed0-5baac45ada19.png)

**Comment by ukemi** [comment]
We should check a few more examples, but this looks good.

**Comment by goodb** [comment]
done as requested above.  re-open if issues found or new pattern desired.

**Comment by vanaukenk** [comment]
@goodb @ukemi 
Can we discuss this representation on tomorrow's call?  I have some questions about the instance-level representation of the different complexes wrt which complex binds the small molecule vs which complex's activity is directly negatively regulated.  Thx.

**Comment by goodb** [comment]
The meeting last week resulted in some disagreement regarding the desirability of some of the inferences that result from the current representation.  Consider three different classifications of the pyruvate kinase tetramer generated in association with the reaction 'phosphoenolpyruvate + ADP => pyruvate + ATP'.  **Depending on the context,** the complex is classified as 'enzyme activator complex', 'pyruvate kinase complex' or just left as the asserted 'protein-containing complex'.  

![Screen Shot 2019-04-01 at 12 41 48 PM](https://user-images.githubusercontent.com/2086122/55357007-dd7cc700-5480-11e9-8e43-0153f22e33c6.png)

Most on call did not like the 'enzyme activator complex' classification.  Once we worked through why that was inferred, it was not deemed illogical however.  The concern is that, apart from the context provided by its placement within the model, that annotation would not make a lot of sense all by itself.  [Another thread about the classification of protein complexes](https://github.com/geneontology/pathways2GO/issues/59#issuecomment-478097169) hit on similar issues and concerns with some suggestions that the problem might best be addressed by altering the Gene Ontology itself.  

(As an aside, this may be a useful example to return to in future discussions of the proper use of the GO-CAM models (e.g. consider gpad export); reducing a complex graphically structured model to a flat list of gene tags loses information and could generate confusing or even incorrect results.) 

@ukemi came up with three alternatives that could work around this problem (with his preference ending on the 3rd.).  Copied from his email: 

1. The stand-alone annotation is misleading, but would be ok if we added a contextual annotation extension. So the annotations would become:
    a. Pkm part_of 'enzyme activator complex' with an AE (has_part F1,6BP, acts_to_regulate pyruvate kinase activity, acts_to_regulate canonical glycolysis). The latter two AE relations would have to be new I think and are similar to ones David OS had proposed as qualifiers.
    
    b. Pkm contributes_to 'enzyme activator activity' with an AE (has_input F1,6BP, regulates pyruvate kinase activity, regulates canonical glycolysis)

2. The core annotations to the enzyme activator terms is simply incorrect. The pyruvate kinase is in not an enzyme activator because enzyme activators necessarily work on other molecules and not themselves. As Jim pointed out, this means that the logical definition of 'enzyme activator activity' in GO is not sufficient. The logical definition is molecular_function directly_positively_regulates some 'catalytic activity'. It is not sufficient because in the cases where the molecular function (F1,6BP binding) directly positively regulates the catalytic activity (pyruvate kinase activity) of the same molecule, this is not an enzyme activator activity. The solution here would be to remove the logical definitions of enzyme activator activity, enzyme regulator activity etc. This would remove the existing reasoning in the ontology and we would need to assert the direct children, but at this point that wouldn't be too difficult. We could explore Jim's idea of having a new relation for molecules that regulate themselves. He suggested modulates, but I think that will open up a whole can of worms similar to regulates. For now it might just bet better to maintain this part of the hierarchy by hand and the relations between the entities is well specified in the GO-CAM models.

3. Enzyme activator activity logical definition: molecular_function and directly_positively_regulates some 'catalytic activity'.
directly_positively_regulates definition: Process(P1) directly
  postively regulates process(P2) iff: P1 positively regulates P2
  via direct physical interaction between an agent executing P1 (or
  some part of P1) and an agent executing P2 (or some part of P2).
  For example, if protein A has protein binding activity(P1) that
  targets protein B and this binding positively regulates the
  kinase activity (P2) of protein B then P1 directly positively
  regulates P2.    There is not direct physical interaction between the agent executing P1 and the agent executing P2 in the Pkm example. The agent is the same entity executing P1 and P2. Therefore the relationship between the ATP binding and the pyruvate kinase activity should not use the directly_negatively_regulates relation. We should relax this to just Negatively_regulates. See http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00002088

Thoughts from the group? Discuss on Wednesday or save for in person meeting ?

**Comment by vanaukenk** [comment]
Discussed on call 2019-04-03.
@deustp01 @goodb @vanaukenk and huaiyu agree that option 3 above is the appropriate way to model regulation by small molecules.

**Comment by goodb** [comment]
Implemented as described above.  Looks like it is working as intended.  Same reaction as above:

<img width="798" alt="Screen Shot 2019-04-03 at 2 08 52 PM" src="https://user-images.githubusercontent.com/2086122/55513312-3e8bd280-561a-11e9-96a3-acf2cbd18d23.png">

Notes:
- Only the complex that directly enables the primary reaction (not the inferred binding reactions related to it) gets classified (here a 6-phosphofructokinase complex).  Other instances of these complexes have no inferred types.
- The top level BP nodes of which the inferred binding functions are parts are classified as regulators.
