### ISSUE TITLE
Document transformation rules for Cambridge GO meeting

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#57]
Get something - e.g. a slide deck ready such that interested parties can see the current rules for transforming reactome into GO-CAMs.

**Comment by goodb** [comment]
@ukemi unless you have something else in mind, I'm going to use the [existing Google Slidedeck](https://docs.google.com/presentation/d/1_UAQN09WPCA5win5mbMs1ORMALNwiRwMBgZDPuyJEW8/edit#slide=id.p3) to capture the rules and relevant screenshots.  Let me know if this is okay with you or if you have another preferred approach.  (Can be exported as .ppt if you prefer)

**Comment by ukemi** [comment]
Hi @goodb. I wasn't planning to bring my laptop with me, an experiment. Instead I'd like to have all of the slides in the meeting folder on the Google drive. Basically @deustp01 will give an introduction to Reactome curation and represenation and then I will go through the rules with examples. Ideally we will have slides that represent: rules for extracting molecular functions, rules for extracting biological processes, rules for extracting cellular components and rules for making causal connections between functions. The ideal slide would have a brief description of the rule, a screen shot of how the information looks in Reactome and a screen shot of how the information looks in GO-CAM.

**Comment by goodb** [comment]
@ukemi okay then it sounds like Google Slideshow is a good format for this.  Will continue on there today.

**Comment by goodb** [comment]
Note from today's meeting.  Beyond capturing rules of transformation, this project is generating general purpose templates for how to model different aspects of biology within the GO-CAM framework.  For example, how to model small molecular regulation of a process.  We should attempt to capture these patterns or 'templates' in a way that makes it easy for curators to see them, use them, and contribute to them.  As a first step, we can put them on the wiki.  Ideally we would see deeper integration with the go-cam editing interface.  Curators could choose templates to use to build skeletons for their models as well as comment on or even directly extend the templates as needed.

**Comment by ukemi** [comment]
Thanks @goodb. I am going to download it and do a bit of culling so the talk won't be too long, but these look good. I will add another version to the meeting folder.

**Comment by ukemi** [comment]
OK @goodb. I have removed a bunch of the specific rule slides because I think it will take too much time to go through every one of them. I have uploaded a new deck to the meeting Google folder. I had one question about slide 24. The figure at the right indicates that the reaction is happening in two places. Don't we want to show an example where this resolves nicely to one location?

**Comment by deustp01** [comment]
@ukemi @goodb Looks good to me. Small things - I replaced the screenshot of a bit of the BMP pathway on slide 1 with one that shows the events as corrected by our discussions last month, and added comments on slides 10 and 15.

**Comment by ukemi** [comment]
Awesome. @deustp01 you can update me on last week's discussion when we are in Cambridge.

**Comment by goodb** [comment]
@ukemi my apologies.  Those slides aren't quite finished yet.  It looks like you have merged together the new ones I was working on in the beginning of the doc with the old ones that were being replaced at the end of the doc and may not be up to date.  And now we have three versions..

I'm going to go through the one that Peter was most recently working on and make sure what is there is correct with what is currently working.  https://docs.google.com/presentation/d/1m0Xxyoalrtt2XFgkZLUPKOlrUstG5Lax7fvpLvOHJvM/edit#slide=id.p1  

Sorry, I should have been more on top of this.  The review for the new slides ended up identifying a couple bugs that distracted me..  (noctua-dev has the latest translation with those bugs cured now.)  

Let me know if you want to hop on skype and discuss before the meeting.

**Comment by goodb** [comment]
> OK @goodb. I have removed a bunch of the specific rule slides because I think it will take too much time to go through every one of them. I have uploaded a new deck to the meeting Google folder. I had one question about slide 24. The figure at the right indicates that the reaction is happening in two places. Don't we want to show an example where this resolves nicely to one location?

If we are talking about the same slide 24, I believe that the slide is out of date and has already been replaced by [Slide 15 - 'Inferring Occurs_in'](https://docs.google.com/presentation/d/1m0Xxyoalrtt2XFgkZLUPKOlrUstG5Lax7fvpLvOHJvM/edit#slide=id.p15)

**Comment by goodb** [comment]
@ukemi and @deustp01 hold on edits/comments on slides please.  Let me get through updating the [Google Slides version in the meeting drive](https://docs.google.com/presentation/d/1m0Xxyoalrtt2XFgkZLUPKOlrUstG5Lax7fvpLvOHJvM/edit#slide=id.p15) that you generated so its in sync.

**Comment by deustp01** [comment]
Meanwhile, I have posted a draft of the "Reactome" slide set to the "presentations" folder on the Google drive  https://drive.google.com/drive/folders/1uTDBjMGYJUIQ9OOWp5P28rFem6WwPJEQ
Comments?

**Comment by goodb** [comment]
@deustp01 Depending on your view of the audience's interests, I think it might be worthwhile to mention the BioPAX export when you bring up interoperability.  The fact that you do make use of the BioPAX standard (however problematic it can be) has made it possible for me to write code that not only works on Reactome, but also on most other pathway databases.  Just like the work on identifier alignment, it  really does increase interoperability systemically, resulting in a lot of saved work.  

It may be a bit down the road, but I also think it might be worth talking about the potential for using the GO-CAM conversion as the main way that you generate the GPAD files shared with and then by the GO consortium.  That would touch on other conversations the software team is having about the pipeline and various places where rules for validating annotations/models should be put into place.

**Comment by deustp01** [comment]
David will be talking immediately after me about the GO-CAM project, so I expect the GO-CAM to GPAD, and validation material will make more sense to the audience as part of his talk. I will add a slide to mine to cover exports of data from Reactome and highlight BioPax there as a link to David and GO-CAM.

**Comment by ukemi** [comment]
Hi @goodb . So just to be sure, the slides I am supposed to use are the ones on the meeting drive? I pared them down because I don't think it is necessary to give curators all of the rules we have generated, just give them examples. I was definitely going to mention the GPAD files at the end as future work. Most of the people at the meeting are gene annotators, not ontology developers or software engineers.

**Comment by goodb** [comment]
@ukemi Please use [the current Google Slides](https://docs.google.com/presentation/d/1m0Xxyoalrtt2XFgkZLUPKOlrUstG5Lax7fvpLvOHJvM/edit#slide=id.p1) (not the ppt file) that are in the Google Drive for the meeting as your starting point for today.  I'd suggest just editing them directly and presenting from the web unless that is too painful for you.

**Comment by ukemi** [comment]
I'm actually not bringing my laptop to the UK (an experiment), so presenting from the web is the best way for me to go.

**Comment by goodb** [comment]
@ukemi great. That way any other changes we want to make can be sure to be in sync.  

can we delete the .ppt file from the drive to avoid potential confusion ?

**Comment by ukemi** [comment]
Sure.

**Comment by goodb** [comment]
And yes.. unless you have 90 minutes it will probably take some more pruning.  My objective was to give a complete coverage of the rules as they exist now to give you a starting point and a reference.  

The only slides I added back currently have yellow backgrounds so you can find them easily.

**Comment by ukemi** [comment]
Do you have time for a quick skype?

**Comment by goodb** [comment]
yes.  hopping on now

**Comment by deustp01** [comment]
Added BioPax slide to Reactome_overview_draft; replaced earlier pptx and GoogleSlides version of file with this new one.

**Comment by goodb** [comment]
Closing issue with outputs:
1. [Slides capturing all of the current operational rules](https://docs.google.com/presentation/d/1_UAQN09WPCA5win5mbMs1ORMALNwiRwMBgZDPuyJEW8/edit#slide=id.g562cc2b479_0_0) for transforming reactome to go-cam.  This one is meant to live on and capture future changes as they come in.  
2. [Slides that @ukemi will present](https://docs.google.com/presentation/d/1m0Xxyoalrtt2XFgkZLUPKOlrUstG5Lax7fvpLvOHJvM/edit#slide=id.p1) to the group (shorter, subset of rules).  This one will just be used for this meeting.  
3. [Slides that @deustp01 will present regarding the state of Reactome](https://docs.google.com/presentation/d/1R0fYnD6paYkXlEX7_hIpMNnbkB9tCm_mki6Lm0N0ZYU/edit#slide=id.p1) and its integration with GO and RHEA.
