### ISSUE TITLE
duplication of active unit nodes

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#60]
When there are multiple incarnations of proteins with the same uniprot identifier in a complex or set that catalyzes a reaction and one instance of that protein is annotated as an active unit, multiple instances are generated in the OWL model.  

![Screen Shot 2019-04-02 at 9 55 36 AM](https://user-images.githubusercontent.com/2086122/55421298-ca740080-552d-11e9-94e6-5fd290a82c88.png)

See R-HSA-450346

**Comment by goodb** [comment]
Could be related.  There are some duplications of complex members from nested complexes.  e.g. see multiple PKMs and PKLRs 

![Screen Shot 2019-04-02 at 11 54 55 AM](https://user-images.githubusercontent.com/2086122/55428613-48d89e80-553e-11e9-8c38-d06f5b0cf220.png)

**Comment by deustp01** [comment]
Something to discuss on the call tomorrow, along with your issue on #56 ? Using Zoom like last week since David won't be joining?

**Comment by goodb** [comment]
@deustp01 I think these here are just some error on my part- most likely in how I collapse hierarchical complexes.  I'd suggest focusing the group discussion on the unsolved modeling questions like #56 .  Yes, I think we decided on Zoom for these calls, even when David is around.  Kimberly updated the calendar item with the link.

**Comment by goodb** [comment]
@deustp01 and maybe @thomaspd if you are listening here.  I am assuming that when we collapse a complex complex down into a parts list, we want to end up with a non-redundant set as determined by the uniprot (and chebi) identifiers used for the entities in question.  If that is incorrect somehow we should discuss today, otherwise I know what I need to fix here.

**Comment by thomaspd** [comment]
Yes, that's correct.  We want the list, not the stoichiometry.

**Comment by deustp01** [comment]
We need to discuss a bit today. I suspect there are some edge cases, to be ignored or accommodated.

**Comment by deustp01** [comment]
Edge case: a complex contains 3 molecules of protein ABC1 and two of phospho-ABC1. Is that two entries on the parts list or only one? If only one, there's a fairly large risk of losing useful biology information about the complex and also connectivity to the activities that enable ABC1 covalent modification and thereby enable the activity of the complex or the regulation of the complex.

**Comment by goodb** [comment]
@deustp01 so far we have no useful way of distinguishing between ABC1 and phospho-ABC1 in the GO-CAM representation.  Same for any other kind of modification.  As I understand it, this decision results from a consortium-wide determination not to annotate specific modified forms?   This is something we could figure out how to do in GO-CAM if we want to.  It is probably one of the larger sources of information loss in the conversion right now.

**Comment by goodb** [comment]
For the pyruvate kinase tetramer example above, it looks like the code is actually behaving itself but the labels in the display are hiding it.  Looking without the labels at the ids, they are a non-redundant set.  However, we see different versions of proteins with the same root id and label, e.g. P14618-1 and P14618-2.

<img width="223" alt="Screen Shot 2019-04-03 at 2 20 20 PM" src="https://user-images.githubusercontent.com/2086122/55513996-db02a480-561b-11e9-9d05-07c8a2628bc8.png">

Given that these are considered different entities in Noctua/Neo and are present for independent curation, it seems that things are as they should be.  (Some indication on the label that they are different forms would be nice but that is in Neo's purview).  

<img width="336" alt="Screen Shot 2019-04-03 at 2 24 50 PM" src="https://user-images.githubusercontent.com/2086122/55514288-86135e00-561c-11e9-908a-5cf1659d26e4.png">

**Comment by goodb** [comment]
Think I have solved the original problem, which was definitely an edge case.  

![Screen Shot 2019-04-04 at 12 33 07 PM](https://user-images.githubusercontent.com/2086122/55583103-f336fa00-56d5-11e9-8135-e0460a61a91e.png)

Still investigating to ensure all complexes really are non-redundant.

**Comment by goodb** [comment]
The code is relying on a BioPAX PaxTools interpretation of equality for PhysicalEntities to avoid redundancy in the members of sets and complexes.  This is in the BioPaxtoGO.flattenNest method.  For now, this seems to be working well.  If we want to change behavior, that is where to do it.
