### ISSUE TITLE
ensure all models are OWL logically consistent

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#64]
Apoptosis induced DNA fragmentation 

trace

GO-CAM model is not logically consistent, please inspect model and try again!
 Entities = OWL:Nothing include:

http://model.geneontology.org/R-HSA-140342/R-HSA-211223_R-HSA-211190_controller
http://model.geneontology.org/R-HSA-140342/R-HSA-211223_R-HSA-211186_controller
inferred inconsistent:<http://model.geneontology.org/R-HSA-140342/R-HSA-211223_R-HSA-211186_controller> active caspase-3
Explanation:
IF
?x1	enabled by	?x2
THEN
	?x2	capable of	?x1
IF
?x1	#type	nucleoplasm part
THEN
	?x1	#type	nuclear part
IF
?x1	#type	nuclear part
?x1	#type	cytosolic part
THEN
	?x1	#type	#Nothing
IF
?x1	#type	caspase complex
THEN
	?x1	#type	cytosolic part
IF
?x1	enabled by	?x2
THEN
	?x2	enables	?x1
IF
?x1	#type	protein-containing complex
THEN
	?x1	#type	Cellular Component
IF
?x1	#type	protein-containing complex
?x1	capable of	?x2
?x2	#type	cysteine-type endopeptidase activity
THEN
	?x1	#type	caspase complex
IF
?x1	#type	http://model.geneontology.org/R-HSA-211223
THEN
	?x1	#type	protein-containing complex
IF
?x2	occurs in	?x3
?x1	enables	?x2
THEN
	?x1	part of	?x3
IF
?x1	#type	Cellular Component
?x1	part of	?x2
?x2	#type	nucleoplasm
THEN
	?x1	#type	nucleoplasm part
FACTS
	Cleavage of DFF45 (224) by caspase-3	occurs in	http://model.geneontology.org/R-HSA-140342/13f0c4c5-7aa7-4258-a8b7-eececf2cbbb3
	Cleavage of DFF45 (224) by caspase-3	enabled by	active caspase-3
	active caspase-3	#type	http://model.geneontology.org/R-HSA-211223
	Cleavage of DFF45 (224) by caspase-3	#type	cysteine-type endopeptidase activity
	http://model.geneontology.org/R-HSA-140342/13f0c4c5-7aa7-4258-a8b7-eececf2cbbb3	#type	nucleoplasm

inferred inconsistent:<http://model.geneontology.org/R-HSA-140342/R-HSA-211223_R-HSA-211190_controller> active caspase-3
Explanation:
IF
?x1	enabled by	?x2
THEN
	?x2	capable of	?x1
IF
?x1	#type	nucleoplasm part
THEN
	?x1	#type	nuclear part
IF
?x1	#type	nuclear part
?x1	#type	cytosolic part
THEN
	?x1	#type	#Nothing
IF
?x1	#type	caspase complex
THEN
	?x1	#type	cytosolic part
IF
?x1	enabled by	?x2
THEN
	?x2	enables	?x1
IF
?x1	#type	protein-containing complex
THEN
	?x1	#type	Cellular Component
IF
?x1	#type	protein-containing complex
?x1	capable of	?x2
?x2	#type	cysteine-type endopeptidase activity
THEN
	?x1	#type	caspase complex
IF
?x1	#type	http://model.geneontology.org/R-HSA-211223
THEN
	?x1	#type	protein-containing complex
IF
?x2	occurs in	?x3
?x1	enables	?x2
THEN
	?x1	part of	?x3
IF
?x1	#type	Cellular Component
?x1	part of	?x2
?x2	#type	nucleoplasm
THEN
	?x1	#type	nucleoplasm part
FACTS
	Caspase 3-mediated cleavage of DFF45 (117)	#type	cysteine-type endopeptidase activity
	Caspase 3-mediated cleavage of DFF45 (117)	occurs in	http://model.geneontology.org/R-HSA-140342/89f16cae-495e-451b-a4c3-bbc99f4a22be
	Caspase 3-mediated cleavage of DFF45 (117)	enabled by	active caspase-3
	active caspase-3	#type	http://model.geneontology.org/R-HSA-211223
	http://model.geneontology.org/R-HSA-140342/89f16cae-495e-451b-a4c3-bbc99f4a22be	#type	nucleoplasm

**Comment by goodb** [comment]
nutshell.  if we have cysteine-type endopeptidase activity , enabled by a protein complex, it can not occur in the nucleoplasm.  The complex is inferred to be a caspase complex and caspase complexes are asserted to be cytosolic - and thus not nucleoplasmic.  Note that this is specific to the case where complexes (not proteins) are the enabler.

An ontology-related problem that we've seen before.  @ukemi input on GO-CAM modeling here?  

This will crop up a bit more often given the new conversion rules because complexes that are all composed of the same protein e.g. a dimer, are now typed as complexes (the way Reactome thinks) whereas in the previous conversion these would have been reduced to a single protein and not caused the problem.

**Comment by ukemi** [comment]
This may be an error in GO. I am investigating the ability of caspases to work in the nucleus. Back when I worked on this, we thought the caspase cleaved the activator in the cytosol and the active DNAse translocated to the nucleus. That may have changed based on the reference in the reactome model.

**Comment by goodb** [comment]
Here are the other reactome models that Arachne finds to be inconsistent under the current ontology set up.  I haven't checked them all, but suspect the same or similar issues:

Synthesis_of_Lipoxins_(LX)
Synthesis_of_5-eicosatetraenoic_acids
Apoptotic_cleavage_of_cellular_proteins
Breakdown_of_the_nuclear_lamina
Apoptosis_induced_DNA_fragmentation
Synthesis_of_Leukotrienes_(LT)_and_Eoxins_(EX)
tRNA_modification_in_the_nucleus_and_cytosol

I intend to go ahead and upload a complete conversion given what we've discussed.  It will include these so we can work through them in noctua-dev.

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/issues/17486

**Comment by ukemi** [comment]
This is all good, not that there are mistakes, but that we can find them this way.

**Comment by goodb** [comment]
Its really not too bad for 1782 models..

**Comment by goodb** [comment]
Note there are more over here:  https://github.com/geneontology/go-ontology/issues/17573

**Comment by goodb** [comment]
As of the conversion on October 29, 2019, all models were logically consistent.  I will leave this issue open pending potential changes related to 139 models that are [not valid according to the shex schema](https://github.com/geneontology/pathways2GO/issues/69)  and other potential short term changes.

**Comment by ukemi** [comment]
Interesting that something we did made R-HSA-2142700 logically consistent.

**Comment by goodb** [comment]
@ukemi can you remind me why R-HSA-2142700 was problematic before ?  

Looking at Apoptosis induced DNA fragmentation from above in the thread, I'm actually not sure why it is now being called consistent.  The go-cam looks the same with regard to the problem with the caspase complex wanting to be cytosolic according to the ontology while the function is occurring in the nucleoplasm.  Did we lose disjointness axioms from goplus somehow ?

![Screen Shot 2019-11-06 at 11 29 52 AM](https://user-images.githubusercontent.com/2086122/68332400-96485b80-008b-11ea-865a-41b70ea40e15.png)

**Comment by ukemi** [comment]
The ALOX5:ALOX5AP:LTC4S was in the nuclear membrane, but catalyzed the reaction in the cytosol.

**Comment by ukemi** [comment]
Yes, this was the issue? @balhoff, did the axioms change?

**Comment by balhoff** [comment]
Could this relate to the ontology changes to the "part" terms? I can imagine that this would impact Arachne, since it doesn't deal with existential restrictions as well as ELK.

**Comment by goodb** [comment]
@balhoff somehow we are missing the inference that an instance of a caspase complex is a cytosolic part.  

Here are all the inferred types coming back for one of the trouble makers.  The inferred-type-with-all ought to have 'cytosolic part' according to the definition of caspase complex, but its missing.  Any idea why?  Its getting other inferences from the same level - e.g. endopeptidase complex 

"id": "gomodel:R-HSA-140342/R-HSA-211223_R-HSA-211186_controller",
        "type": [
          {
            "type": "class",
            "id": "gomodel:R-HSA-211223",
            "label": "active caspase-3"
          }
        ],
        "inferred-type": [
          {
            "type": "class",
            "id": "GO:0008303",
            "label": "caspase complex"
          },
          {
            "type": "class",
            "id": "gomodel:R-HSA-211223",
            "label": "active caspase-3"
          }
        ],
        "inferred-type-with-all": [
          {
            "type": "class",
            "id": "GO:0008303",
            "label": "caspase complex"
          },
          {
            "type": "class",
            "id": "BFO:0000004",
            "label": "independent continuant"
          },
          {
            "type": "class",
            "id": "BFO:0000002",
            "label": "continuant"
          },
          {
            "type": "class",
            "id": "BFO:0000001",
            "label": "entity"
          },
          {
            "type": "class",
            "id": "GO:0005575",
            "label": "cellular_component"
          },
          {
            "type": "class",
            "id": "BFO:0000040",
            "label": "material entity"
          },
          {
            "type": "class",
            "id": "GO:1902494",
            "label": "catalytic complex"
          },
          {
            "type": "class",
            "id": "GO:0032991",
            "label": "protein-containing complex"
          },
          {
            "type": "class",
            "id": "gomodel:R-HSA-211223",
            "label": "active caspase-3"
          },
          {
            "type": "class",
            "id": "GO:1905369",
            "label": "endopeptidase complex"
          },
          {
            "type": "class",
            "id": "BFO:0000030",
            "label": "object"
          },
          {
            "type": "class",
            "id": "GO:1905368",
            "label": "peptidase complex"
          }
        ],

**Comment by ukemi** [comment]
So I think @balhoff is on the right track.

**Comment by goodb** [comment]
In most recent update (Nov. 21), the same 7 files listed above were called inconsistent by the conversion code for the same reasons.  (Nothing else failed the owl check).  However, these are all being called consistent by the current Noctua-dev server instance.  It is possible that the conversion code is using an older GO-Plus then what is live on the server.  I'm guessing this is driving the differences.  Based on above, I'm not sure which is more correct.  Will re-execute test with updated ontology.

**Comment by goodb** [comment]
All previous errors seem to be fixed by update to october 31 version of go-plus.owl

**Comment by ukemi** [comment]
Close?

**Comment by goodb** [comment]
Yes, will check this again when all the "final" (ha ha..) rule changes are added and re-open if needed.
