### ISSUE TITLE
Multiple part_of relations between regulation and the core process

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#66]
In the BMP pathway (R-HSA-201451) @deustp01 made some edits where he took the reactions that regulate the pathway and directly asserted them to be associated with the GO regulation process. Now in the import, these reactions have part of relationships to both 'negative regulation of BMP signaling pathway' and to 'BMP signaling pathway'. We have to build into the strategy that if a reaction is directly mapped to a GO term, then the only part_of relationship between that reaction and a GO process should be the one that is asserted.

**Comment by deustp01** [comment]
@ukemi 's point corresponds to our practice in generating a GAF: to find the biological process term to associate with proteins involved in s specific reaction (so at the extreme leaf end of the event hierarchy), the script looks first for a term associated with the reaction itself. It there is none, the script looks for one associated with the parent pathway that contains the reaction and uses that one. If it still finds nothing, it may look to the grandparent pathway (I'm not sure) but if it still finds none, it fails gracefully and generates no biological process annotation for that protein in that functional context.

So by adding a regulation term to a reaction within a signaling pathway, I force the Reactome GAF-generation script to put a regulation process term on the proteins involved in that reaction and to ignore the fat that the parent signaling pathway has a signaling process term on it.

Can the GO-CAM generation procedure mimic this behavior?
