### ISSUE TITLE
missing some conversions from causally upstream of to directly positive regulates

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#74]
I think we might be missing some conversions from causally upstream of to directly positive regulates as a result of the recent removal of the contributes to relations linking complexes to functions.  Check on e.g. 
https://reactome.org/content/detail/R-HSA-8875555 http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-8875555

**Comment by deustp01** [comment]
Losing information is bad but, practically, before running head on at this one, I'd like to get a better sense of how many of our complexes that enable something and that do not have an annotated active unit, could be inferred to have one based on the GO molecular function annotations from non-Reactome sources of the components of the complex. If such inference is possible for a lot of them, then we cut the information loss without requiring anything more on the GO side and improve the quality of Reactome annotation (an example of the superior cross-validation that this whole project will provide).

**Comment by goodb** [comment]
This problem mainly arises primarily when we do have active unit annotations as in the following:

<img width="817" alt="Screen Shot 2019-10-07 at 9 43 07 PM" src="https://user-images.githubusercontent.com/2086122/66368047-ab768100-e94b-11e9-8d3e-68c7b77f3209.png">

According to the previous line of thought, the downstream reaction here should positively regulate the other reaction because the complex it produces catalyzes the downstream reaction.  The current rule is fooled because the active unit is placed in the enabler slot and isn't in the output slot of the other reaction.  

If we do want positive regulation in this case, instead of the default causally upstream of, I have the fixed rule ready.  Let me know what you prefer @ukemi @deustp01 .

**Comment by ukemi** [comment]
I think to be consistent with what we are suggesting to annotators for conventional GO-CAM models, we want this to be a regulation. @vanaukenk correct me if I am wrong. So in this case, the binding would positively regulate the GEF activity of the C3G (RAPGEF1).
