### ISSUE TITLE
Implement testing framework for pathways2go

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#76]
Add general tests that apply to all models:

- [x] Model is logically consistent (OWL Reasoner)
- [x] Model is consistent with regard to shex schema
- [x]  add to continuous integration test (travis) framework.  
- [ ] Add specific tests for each of the conversion rules.  Avoid situations like https://github.com/geneontology/pathways2GO/issues/74 

Tests:
inputs = biopax files, 
outputs = go-cam models
tests (on generated in-memory go-cam models)
query for expected matches against each rule
one test per rule.

**Comment by goodb** [comment]
Noting that generic OWL and shex testing framework is in place and running in travis.  Next steps are specific tests for individual rules.

**Comment by ukemi** [comment]
You probably already thought of this, but it might be nice to incorporate this into the import pipeline that @dustine32 is using for the MGI and Wormbase imports. Tagging @vanaukenk

**Comment by goodb** [comment]
@ukemi I know @dustine32 has been using the shex validator for a while and he also has access to an owl consistency checker.  @dustine32 if you want to do this automatically on PRs via travis, I can show you how to set it up, pretty easy.  (BTW @dustine32 I've moved all shex validation code into minerva and it is now accessible via the minerva command line utility - though make sure you check out the dev branch for now).

**Comment by goodb** [comment]
finished framework and first round of tests.  Closing the general issue, will re-open specific issues for future test failures, rule changes or additional tests.
