### ISSUE TITLE
Revisit representation of non-catalytic regulation as binding functions

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#77]
There has been some back and forth on this.  Currently (Oct 2019) we convert regulation by small molecules in Reactome to regulation by binding reaction in go-cams.  Like this in Glycolysis.  

![Screen Shot 2019-10-14 at 3 22 01 PM](https://user-images.githubusercontent.com/2086122/66786901-da827a80-ee96-11e9-91aa-e7ee3cc78e1c.png)

![Screen Shot 2019-10-14 at 3 20 18 PM](https://user-images.githubusercontent.com/2086122/66786916-e1a98880-ee96-11e9-9481-e75bdc689266.png)

The regulating molecule is made to bind with the catalyzing molecule in the new reaction and this reaction is made to regulate the original reaction and to be part of an unnamed biological process that regulates the parent pathway/process.  

Confirming that this is the desired structure?

**Comment by goodb** [comment]
The rule that produces this structure currently isn't unique to small molecules, it also impacts proteins, complexes etc.  It comes into play whenever Reactome employs their 'regulated by' structure.  You can see an example of this on noctua dev now http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-4641262  for the reaction 'Beta-catenin is released from the destruction complex'

![Screen Shot 2019-10-24 at 3 25 55 PM](https://user-images.githubusercontent.com/2086122/67530257-65bbf700-f673-11e9-8adf-cb3f9ecaf39a.png)

1. **Confirming again that this is the desired pattern for any non-catalytic control event?**

This particular reaction illustrated a rule that was broken for the last release to noctua-dev: If reaction1 has_output M1 and reaction2 is regulated by M1, then reaction1 regulates reaction2.  With this rule working, the above reaction looks like this:
![Screen Shot 2019-10-24 at 3 23 20 PM](https://user-images.githubusercontent.com/2086122/67530424-e24ed580-f673-11e9-9f9d-0590d8961ba3.png)

note the new regulatory relationship between Phosphorylation of LRP5/6 cytoplasmic domain by CSNKI and Beta-catenin is released from the destruction complex:
![Screen Shot 2019-10-24 at 3 26 36 PM](https://user-images.githubusercontent.com/2086122/67530487-0f02ed00-f674-11e9-90bb-7a76b079aa32.png)

2. **Confirming that this rule is operating correctly on this pathway?**

**Comment by ukemi** [comment]
Staring at this and pondering it over and over I have to admit that it's still a bit unsettling to me. I think we need to brainstorm about the translation of these kinds of feedback pathways. I'm going to put together a few slides for the next call. If we don't have time to discuss it, then we can look at it at the meeting. I think my unease stems from the fuzzy distinction between the regulatory functions and the process. The resulting model with the kinase function being a causal part of the process and the binding being part of an outside regulatory process seems incorrect. As Ben pointed out yesterday on the call, if this pathway is all part of the degradation process then I think the inferred binding that essentially occurs downstream of the casein kinase activity should be incorporated into the pathway (or maybe even not be represented in the GO-CAM model). Still thinking... It would be nice to see a few more of these type of feedback loops and how they are represented in both Reactome and the GO-CAM translation.

**Comment by ukemi** [comment]
Still thinking about this after the call on Wednesday. I've decided to go back to the start and follow the instances. In this case, even though we have the rule to invoke the binding as a separate regulatory process, in this case the enabler of the binding is a subcomplex of the kinase activity. If we follow the instances of the entities through the causal pathway, then the regulatory step would be directly downstream of the kinase activity. This is because the output of the kinase reaction is the same instance as the supercomplex that is the input of the regulatory step. We can look a this in New York, but given that at the moment we are allowing binding activities in the model, I would suggest that in these special cases:
If the output of a reaction is a protein containing complex AND part of the protein containing complex (using part_of as being reflexive here) regulates the next step in the pathway, then the catalytic activity directly_provides_input_for a binding MF and that binding MF regulates the next MF. 
Thoughts?

**Comment by deustp01** [comment]
End-point / scope-creep here too? Is it actually a useful feature of version 1 to get a sense of some kinds of causal interactions, e.g., ornate feed-forward regulatory loops, that we can identify in the Path2GO process but not yet fully parse into GO-CAM?

**Comment by ukemi** [comment]
Let's think about my proposal above and look at it in this context. I think it solves the issue, but discussion for NYC. To me the goal of this phase of the project is to faithfully represent the information in the Reactome human models in the GO-CAM environment. How do we define 'faithful'? Faithful is the conversion of Reactome-supplied information into GO-CAM with no errors that make the biology inconsistent between the two representations. Future considerations would be making the faithfully converted models fully compliant with GO-CAM causal representation. I think we are a long way towards this, but we still need to iron out the binding issues.

**Comment by goodb** [comment]
@ukemi how does this interpretation of what you say above look to you?  This version appeals to my sensibilities in terms of minimizing information loss and maintaining causal flow.  I like it better than the current version as it directly connects the binding reaction to the flow.  

![Screen Shot 2019-11-15 at 9 53 39 AM](https://user-images.githubusercontent.com/2086122/68964341-f5922400-078d-11ea-8e1d-0337c7fdc555.png)

**Comment by ukemi** [comment]
This is exactly what I was trying to describe above. Glad it makes sense to you too! I also think it fits the Reactome graph better. With respect to @deustp01's comment above about feedback loops, I think this falls into the same category as the way I had previously thought about cycles. In an instance-based representation there is no such thing because as soon as you complete a turn, you are beginning a second instance. It's kind of like a clock. One turn of the minute hand doesn't start the same hour over again, it starts a new hour. I thought a lot about this wrt the TCA cycle. Does that make sense? So I think we should never really be faced with a cycle issue.

If this doesn't make sense, let's brainstorm about it in NYC.

**Comment by goodb** [comment]
I guess I'm still not really following the feedback loop issue.  We certainly have models that incorporate loops of causal relations between functions.  e.g. I believe glycolysis does this, yes?  

Personally, I find it confusing when the causal relations are applied to the root process node of a model.  It begs the question of specifically how the functions (or other processes) that are the source of these arcs are influencing the primary process described by the model.

**Comment by ukemi** [comment]
> I guess I'm still not really following the feedback loop issue. We certainly have models that incorporate loops of causal relations between functions. e.g. I believe glycolysis does this, yes?

I didn't think so. Let's look again. If it does, doesn't it become problematic with respect to upstream versus downstream.

> Personally, I find it confusing when the causal relations are applied to the root process node of a model. It begs the question of specifically how the functions (or other processes) that are the source of these arcs are influencing the primary process described by the model.

I think the issue you might behaving here is that all the models have some aspect of subjectivity in which we determine causal events that are part of a process versus those that are outside the process. At least that's what I think you are getting at.

**Comment by goodb** [comment]
There are loops there in glycolysis, but none are fully feed-forward.  There is a negative regulation step in each one - which totally makes sense.  In fact, if we do have any pathways that loop through positive regulation steps, but do not introduce some negative regulation somewhere then we probably know we are missing something.  This is testable when we have all the pathways in a reasoned environment.  
![Screen Shot 2019-11-15 at 2 48 41 PM](https://user-images.githubusercontent.com/2086122/68982217-0016e280-07bb-11ea-82ac-68a4fe51e801.png)

> I think the issue you might behaving here is that all the models have some aspect of subjectivity in which we determine causal events that are part of a process versus those that are outside the process. At least that's what I think you are getting at.

Yes I  think that is on track.  My view of a go-cam model is of a functional description of a process based on the organization of its constituent events.  If an event is considered to be outside of the process that the go-cam is about, then it seems wrong for it to be part of that model and it seems vague to have it exert causal influence over the process as a whole.  Ideally such an event would exist in a separate go-cam model representing whatever process it was deemed to be a part of.  And then, if it exerted a causal impact on the other process, the relevant function node or nodes within both processes that specifically mediated that relationship could be identified and the models joined at that level.

**Comment by ukemi** [comment]
When I look at glycolysis (R-HSA-70171), I don't see the cycles. I see the linear glycolytic pathway with the impinging regulatory processes and some side reaction leading into other metabolic processes. It looks like a textbook example to me.

**Comment by ukemi** [comment]
Just chatted with @goodb and we figured out what is going on in the diagram above. The ATP that is being generated by the phosphoglycerate kinase is resulting in negative regulation of PFK edge because ATP negatively regulates the phosphofructokinase reaction. Although technically correct, this seems very misleading to me. It would be more satisfying if the ATP were linked to the regulatory binding reaction as an input. I think we will have to look at this closer in NYC.

**Comment by deustp01** [comment]
This specific one may require a deep dive into old biochemistry: what is the ATP concentration needed to half-inhibit PFK; what is the normal range of cytosolic ATP concentrations in fed / fasting / starved states? Certainly, with or without this sort of kinetic evidence, the textbook says that it is the cellular ATP pool that modulates PFK activity, to slow glycolysis when the cellular energy charge (ATP is a proxy) is high, so ATP from glycolysis contributes to this pool but only a little compared to major energy sources like oxidative phosphorylation. Neither Reactome nor GO-CAM may have really good tools to handle this - we can imagine using pathway annotations to feed a quantitative modeling simulation that allows users to manipulate all the parameters that we can't really handle.

On my to-do list: look at all the small-molecule regulations of glycolysis, and the textbook-asserted role of each.

**Comment by ukemi** [comment]
This is going to be an interesting discussion. @goodb and I touched on this pool idea yesterday. The one thing that I think is definitely out is to say that the enzyme that generates the ATP, phosphoglycerate kinase, is directly negatively regulating the PFK. What's happening is that the phosphoglycerate kinase is making a molecule, ATP, that is the 'regulatory molecule'. 

@deustp01 how much do you know about the Warburg effect? Seems like this is a case of glycolytic regulation that might be useful. But your point is also well taken that I don't think that the activity of any of the ATP generating enzymes in glycolysis will ever be prominent enough to cause the regulation to happen. I think the regulation happens in the more global context of cellular ATP pools that are far more effected by other processes. Note this is also represented with PFK generating ADP and positively regulating itself.  See the above diagram.

**Comment by deustp01** [comment]
> There are loops there in glycolysis, but none are fully feed-forward. There is a negative regulation step in each one - which totally makes sense. In fact, if we do have any pathways that loop through positive regulation steps, but do not introduce some negative regulation somewhere then we probably know we are missing something. This is testable when we have all the pathways in a reasoned environment.

The glycolysis process contains a classic pure feed-forward regulatory loop: the output of the PFK1 reaction, fructose-1,6-bisphosphate, positively regulates the reaction catalyzed by pyruvate kinase. Other factors regulate the activity of PFK1 enzyme, but to the extent that PFK1 is active and fructose-2,6-bisphosphate gets generated, that product positively regulates pyruvate kinase activity. (The textbook also comments that such simple feed-forward regulation is unusual.)

Maybe a tangent, but I can't find this loop in the GO-CAM model http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-70171#. Pyruvate kinase activity is present, of course, as are three small molecules that negatively regulate it and the one that positively regulates it, and the function that generates the positive regulator is present, but I don't see any connection between the function (extreme left of screenshot) and its positively-regulating output (leftmost regulator in the row of them along the bottom):
<img width="1207" alt="Screen Shot 2019-12-02 at 1 10 22 PM" src="https://user-images.githubusercontent.com/12737623/69984118-5f3c5d00-1506-11ea-8e8c-8461aeef7096.png">

**Comment by ukemi** [comment]
I think we resolved this in NYC. As far as I know, for the very interesting case above using the fructose-1,6-bisphosphate, @deustp01 is going to model that explicitly in Reactome having the creation of it by PFK1 be the preceding event in the regulation. For the other examples of the 'pools' of metabolites, they will remain as is and will not satisfy the causal rule.

**Comment by deustp01** [comment]
yes, exactly. I don't see a reliable way to instruct a reasoning tool to distinguish a pool with only one input source, like fructose-1,6-bisphosphate here, from a pool with multiple input sources, like ATP or NADH here, so manual tagging is needed - done already in this case.

Reasoning tools could reliably identify candidates for manual tagging, e.g., every time an input / catalyst / regulator physical entity is detected for a reaction that is not already identified as an output of an immediately preceding reaction, generate a report noting all reactions that have the physical entity (same chemical identity, same location, same [future] cell type) as output - possible round-trip quality improvement feature for version 2.

**Comment by goodb** [comment]
For the record, before closing, two issues arose here.  

One was the original reason for the ticket - the modeling for Reactome's use of the "regulated by molecule" structure.  When this is asserted in Reactome, we create a binding node in the go-cam model that has the regulating molecule (and if present, the catalyst of the reaction) as the input(s) and assert that function has the regulating effect on the reaction and that the binding event is part of a generic biological process that regulates the parent pathway in the same way the binding event regulates the reaction.  I believe we have settled on this structure for now, as depicted in https://github.com/geneontology/pathways2GO/issues/77#issuecomment-560517411 

The second issue, also mentioned in that comment, was about a rule that attempted to infer regulatory relationships between reactions.  This was the rule: If Reaction1 has output Molecule1 and Molecule1 regulates Reaction2 then Reaction1 regulates Reaction2.  Even when constrained to operate only within the context of a pathway, this rule was producing false positives - especially for reactions with very common reactants like ADP.  The rule was modified with the additional constraint that Reaction1 must also be directly causally upstream of Reaction2 (which is asserted by Reactome in the form of their "preceding event" relationship).  This eliminated the spurious matches detected in Glycolysis while still finding some reasonable cases that fit the structure.
