### ISSUE TITLE
filter reactions that involve a drug

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#84]
See context from [here](https://github.com/geneontology/pathways2GO/issues/69#issuecomment-567986756)

Use the presence of an IUPHAR identifier on a physical entity within the reaction as a sign.  Remove these reactions from the export.

**Comment by goodb** [comment]
@deustp01 do you want to take out the reaction or the whole pathway when a drug is detected?

**Comment by deustp01** [comment]
Yes, for Path2GO version 1. That should leave a complete and fully connected set of normal reactions given current Reactome curation practices and scope.

**Comment by goodb** [comment]
@ukemi moving over to this issue from your comment https://github.com/geneontology/pathways2GO/issues/69#issuecomment-569675827  .  Just double checking question above - do we take out the reactions or the pathways that contain such reactions?  I think @deustp01 said the reactions in email, but want confirmation.

**Comment by deustp01** [comment]
Remove reactions that involve drugs (any entity that has an IUPHAR identifier as a cross-reference and any complex that has a drug as a component). There may be some pathways that consist entirely of reactions involving drugs (I don't think so, but am not certain) so these would disappear. I expect (but again am not completely sure) that removing the drug-containing reactions from all other pathways will leave a "normal" reaction set that is connected.

**Comment by ukemi** [comment]
From the few that I have looked at, there is an underlying normal pathway if the drugs are removed.

**Comment by deustp01** [comment]
@ukemi that is definitely the intention. I'll e-mail the two curators who've done all the drug annotation so far to confirm.

**Comment by goodb** [comment]
@deustp01 looking at R-HSA-1963589 "ERBB2 forms heterodimers with ligand-activated ERBB receptors..".  That reaction is negatively regulated by a complex that contains the drug pertuzumab.  There are no other drugs in its inputs or outputs.  This case makes me think that it would make sense to take out the regulator but leave the rest of the reaction intact - thus maintaining a lot of connectivity for this pathway.  What do you think?

**Comment by ukemi** [comment]
This makes sense to me. In effect we have treated the regulation as a separate causal statement in the other models. @deustp01 do you agree?

**Comment by deustp01** [comment]
Yes, exactly. Remove the drug-binds-protein reaction and the regulation-by-drug assertion to preserve a normal event. This should be a general problem / fix because, as discussed previously, it makes sense to create a reaction in which a drug binds a normal protein and then a separate regulation instance in which the drug:protein complex regulates the reaction that would have been mediated by the plain normal protein (same as saying that BMP ligand binds trap protein and ligand:trap complex then negatively regulates BMP - ligand binding).

**Comment by goodb** [comment]
New rules then:

1. If a reaction contains a drug as an input or output, or the reaction contains a complex that contains a drug as an input or output, then delete the reaction.
2. If a reaction is regulated by a drug or a complex that contains a drug, then delete the regulates relationship, but keep the reaction.  

Yes?

An aside.  R-ALL-9649879 AZ5104 appears to be a drug with no IUPHAR id, just a PubChem id.  Should I add a check for PubChem?  Does Reactome annotate physical entities that are not drugs to PubChem ids ?

**Comment by deustp01** [comment]
Those rules sounds right. I've e-mailed the curator to ask about R-ALL-9649879 AZ5104.

**Comment by deustp01** [comment]
For R-ALL-9649879 AZ5104
"Occasionally we annotate a drug before IUPHAR has annotated it. In those cases, we cross-reference PubChem and switch to IUPHAR when an IUPHAR record becomes available."

There are no simpleEntities (small molecules) in human Reactome that have PubChem reference entities, only a handful (21) of drugs, but this is not a guarantee of future behavior. Would it be ptractical to retrieve a list of all physical entities that belong to the drug class and use the list to find and exclude all reactions with list members as inputs or outputs and all regulation instances with list members as the physical entities that do the regulating?

**Comment by goodb** [comment]
I could, but it would be much better if we can get it to work via what is coming through the BioPAX.  That could be accomplished with the xref to chebi root drug idea.

**Comment by deustp01** [comment]
Yes, it’s a choice between a custom hack that should be completely reliable and a BioPAX – rule approach that will almost always work and that, in the worst case, will be the basis of yet another GO-CAM QA check on Reactome annotations. Go for the BioPAX – rule.

**Comment by goodb** [comment]
To do it consistently we would need to change the BioPAX export to include the annotation to the chebi drug term.  From the current BioPAX export, there is no way to know these entities are drugs except through knowledge of the IUPHAR or PubChem identifiers.  

I think there may be a general comment to be made here for the paper about the need to use ontologies to define meaning for interoperability rather than relying on implicit knowledge of identifiers.  This is similar to the untyped physical entity situation which, I hope, was largely resolved through your work adding upper level types to those entities.

**Comment by ukemi** [comment]
My worry is that the non-rigidity of the ChEBI roles would raise its head here. If we calculate on ChEBI, we would eliminate reactions with many chemicals that only sometimes act as drugs, ATP.

**Comment by goodb** [comment]
Not sure how that would happen?  I'm suggesting that Reactome apply a BioPAX:RelationshipXref to chebi:drug for the 225 entities in their class https://reactome.org/content/schema/Drug  .  I don't think that set would contain ATP unless I am pretty severely mistaken.  Am I??

This information would not be represented in the GO-CAM models at this time, it would only be used in the filtering step.  If we did want to include drugs, we could model them via the role pattern that CHEBI supports, but that isn't necessary at this time.  (And this would only show up in the underlying physical entity OWL ontology (REO)).  

In any case, if not chebi, there must be a biopax-compatible semantic pattern for saying "this thing here is a considered a drug in the context of this pathway".

**Comment by deustp01** [comment]
I'm probably missing something here. [This](https://reactome.org/content/schema/objects/Drug) is a list of all entities that we have classed as "drug" (219 chemical drugs and 6 protein drugs). (Ben's link is to the definition of the class.) By making an entity a member of this class we are asserting that its rigid role is drug - none of these physical entities plays any part in any normal reaction or regulation.

Someday we may trip over cases where an entity with a normal physiological function can also be used as a drug. Maybe ATP is an example, or a steroid hormone.

However, that is not the case for any of these 225 entities and I expect such situations to be rare because they involve administering a non-physiological amount of a substance (out of scope for Reactome because we don't annotate quantitative phenomena) or delivering it to a specific tissue site (out of scope until we start to annotate tissues). Even then, so long as the drug is used to modulate a disease reaction, not a normal one, the reactions will be out of scope.

**Comment by ukemi** [comment]
It looks like my concern is unfounded. I we are restricting the classification of drug to be only those that are asserted by Reactome then we are fine. I was concerned about inadvertently picking up the ChEBI drug classifications as a side product. This would be bad.

**Comment by goodb** [comment]
This is working now.  No reactions with drugs as inputs or outputs are included in the conversion.  When drugs are listed as controllers, the controllers are ignored.
